### ISSUE TITLE
JEI in cheat mode upon starting a new world

### ISSUE THREAD

**Issue by pha3l** [FTBTeam/FTB-Sky-Adventures#1]
* **Modpack Version**: 
1.0.0
* **Issue**: 
Title says it all.  Not a huge deal but probably worth fixing in the next update.

* **Link to Log or Crash File Paste**: 
N/A

* **Is it Repeatable?**: 
Yes

* **Mod/s Affected**: 
JEI

* **Known Fix**:

**Comment by tfox83** [comment]
By default cheats are disabled when you create a new world.  Thats because you enabled cheats in your world.  Its a feature of JEI.

**Comment by pha3l** [comment]
I can confirm that Allow Cheats is set to off in the world creation screen.  JEI's cheat mode is still enabled each time I create a new world.

**Comment by tfox83** [comment]
strange, I just created 6 new world and JEI cheat mode is disabled.  Also had two other people test with same results.

**Comment by pha3l** [comment]
Odd indeed.  I haven't added any mods or altered the pack downloaded via the Twitch client in any way, and I just tried it half a dozen times as well.  Feel free to close the issue since apparently it's something on my end!

**Comment by twsx** [comment]
Just to provide some additional input:

My JEI was *not* in cheat mode, both with or without cheats enabled on world creation.

On another note: Is it intended for tfox's grave to be in the temple in a fresh world, instantly giving you the Philo Stone? 😅

**Comment by tfox83** [comment]
The grave is intended.
