### ISSUE TITLE
All crates give 64k ME storage

### ISSUE THREAD

**Issue by mitchell-abbott** [FTBTeam/FTB-Sky-Adventures#100]
* **Modpack Version**: FTBSkyAdventures-1.2.0-1.12.2

* **Issue**: All crates from quest rewards at giving 4x 64kME storage cells. While playing tonight, I opened 6 epic crates and 1 legendary. All I receive now are 4x 64k ME storage cells.

* **Is it Repeatable?**: Across the 7 crates I opened post update, yes

**Comment by tfox83** [comment]
Its in a pool along with 8 other item/blocks.  Its all based on chance/luck.
