### ISSUE TITLE
End Cake not working

### ISSUE THREAD

**Issue by Cr1t1calReaper** [FTBTeam/FTB-Sky-Adventures#106]
* **Modpack Version**: 1.2.0

* **Issue**: End Cake doesnt seem to work, cant take me to the End and it doesnt accept eye of ender (idk if it's supposed to accept eye of ender)

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: It didnt work in 1.1.0 either, and restarting game, client and pc doesn't change anything.

* **Mod/s Affected**: Ex Nilo Creatio 1.12-0.2.4

* **Known Fix**: No clue, I just wanna go to the End

Im playing in singleplayer in case that affects it somehow.

Best regards
C1t1calReaper

**Comment by tfox83** [comment]
You must be hungry to eat it once placed in world.
