### ISSUE TITLE
Equivalent Storage (Not an Issue just a suggestion)

### ISSUE THREAD

**Issue by xSquibbyx** [FTBTeam/FTB-Sky-Adventures#108]
Any plans to add this Equivalent Storage mod into the pack at a later date or version.

Personally I like having my EMC and Refined Storage integrated as I believe many others do. I understand the possibilities of lag due to EMC value changes and item number changes but I feel that there are more advantages than disadvantages in this situation

**Comment by tfox83** [comment]
We removed during testing due to the amount of hard crashes and issues with the mod.
