### ISSUE TITLE
Yellorium Block (Heat Source) not craftable

### ISSUE THREAD

**Issue by twsx** [FTBTeam/FTB-Sky-Adventures#11]
* **Modpack Version**: 1.0.0

* **Issue**: The Yellorium Block is registered as a heat source for the Crucible. But, unless I'm missing something, there's no way of getting to it. The only way to craft it is with 9 Yellorium Ingots, which are dict'd out in favor of IC2 Uranium Ingots.

* **Mod/s Affected**: Ex Nihilo, Extreme Reactors

* **Known Fix**: Edit: Just thought of that: Not a fix, but considering that you can so easily get to Cyanite Blocks (which are 15x as opposed to Yellorium Blocks' 10x) through the Uranium+Sand recipe, the Yellorium Blocks could be removed as a heat source all together.

**Comment by tfox83** [comment]
removed yellorium block as a heat source, thanks
