### ISSUE TITLE
Crash: Transfer Node attempting to insert item into Bookcase

### ISSUE THREAD

**Issue by JoeCoolFlyingAce** [FTBTeam/FTB-Sky-Adventures#110]
* **Modpack Version**: 1.1.0

* **Issue**: Crashes when Transfer Node attempts to insert an item(tested with Polished Andosite) into a Bookcase(tested with Oak)

* **Link to Log or Crash File Paste**: https://pastebin.com/XmdPcQZZ

* **Is it Repeatable?**: Yes. Crashed a server, and verified in single player.

* **Mod/s Affected**: Extra Utilities 2, Bibliocraft

* **Known Fix**: Don't connect a Bookcase to an Extra Utilities Transfer Pipe.

**Comment by JoeCoolFlyingAce** [comment]
- **Modpack Version**: Still happens on 1.2.1

**Comment by tfox83** [comment]
this has been reported, but now fix.  Please advoid that setup for now
