### ISSUE TITLE
World stuck loading at 0%

### ISSUE THREAD

**Issue by IsoEeli** [FTBTeam/FTB-Sky-Adventures#111]
* **Modpack Version**: 1.2.0 and 1.2.1

* **Issue**: I couldn't load my world, it would freeze at "0%"

* **Link to Log or Crash File Paste**:

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: MineTogether

* **Known Fix**: I disabled MineTogether and my world loaded correctly

**Comment by iKurama** [comment]
Something freezing in modded and in vanilla is "normal". Sometimes it just needs a restart.

**Comment by tfox83** [comment]
Please try a fresh install
