### ISSUE TITLE
Compartment chest crashing game

### ISSUE THREAD

**Issue by theilsomers** [FTBTeam/FTB-Sky-Adventures#112]
* **Modpack Version**: 1.0.0 and 1.2.1

On SP Sky Adventures version 1.0.0 and 1.2.1 i'm using the compartment chest for help with bees genetic storage and twice now I have crashed when entering the chest. The crashing is sporadic but glancing through the crash log I see something about unstable ingot expecting and explosion. Not very versed in reading crash logs so I thought I would send this too you, if you need the rest of the crash log let me know.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/6e2db563

* **Is it Repeatable?**: has happened twice so far not sure how I have gotten it to happen to be able to reproduce

**Comment by tfox83** [comment]
seems he has fixed this in dev.
