### ISSUE TITLE
Void Ore Miner Tier 5 not registering in the quest book

### ISSUE THREAD

**Issue by thaimichael** [FTBTeam/FTB-Sky-Adventures#113]
* **Modpack Version**:  1.2.1-1.12.2 beta running on the multiplayer server

* **Issue**: Void Ore Miner Tier 5 not registering in the quest book

After placing and using Void Ore Miner Tier 5 tried to pick up and register it as complete and it does not register.
Tried relogging same issue.
Tried restarting my client same issue.
There appears to be an NBT tag added once the block has been placed in world and picked up.
Tried in single player world registers complete if not placed once placed can no longer resister.

**Comment by Scarsz** [comment]
Burn it in trans tablet, take it back out, turn in quest

**Comment by thaimichael** [comment]
cannot anymore tier 5 and tier 6 Void Ore Miner EMC removed in this version.

**Comment by Scarsz** [comment]
Love how trigger happy FTB devs are with removing EMC from items. Only solution to this would just be crafting another, I guess.

**Comment by tfox83** [comment]
fixed in next version
