### ISSUE TITLE
Roost Refined Iron Chicken

### ISSUE THREAD

**Issue by TheAetherConfluence** [FTBTeam/FTB-Sky-Adventures#114]
* **Modpack Version**: 1.1.0

* **Issue**: Roost has a Refined Iron Chicken from IC2 that breeds from two iron chickens.  The Refined Iron Chicken cannot render and has an error texture. Also the chicken should be removed because I keep getting Refined Iron Chickens instead of Iron Chickens.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Roost

* **Known Fix**: Remove the Refined Iron Chicken from the pack(?)

**Comment by Kite1024** [comment]
I disagree with removing the chicken as an option. It does have a texture issue though.

How many times did you breed the two iron chickens without getting -any- iron chickens?

**Comment by tfox83** [comment]
fixed in next version
