### ISSUE TITLE
End Cake not bringing me to the end

### ISSUE THREAD

**Issue by Kuperus** [FTBTeam/FTB-Sky-Adventures#115]
* **Modpack Version**: 1.1.0

* **Issue**: End Cake not working

* **Is it Repeatable?**: Tried it multiple times

usually when you eat endcake, you are transported to the end dimension, but right now i can`t eat any of the cake... the cake is complete, i tried hitting it with ender eyes that it might not have been completed… but nothing happens.

**Comment by Mordaii** [comment]
You need to be missing hunger.  Can you try again when you are hungry?

**Comment by Kuperus** [comment]
ow how can i be so stupid :) you are completely right.
