### ISSUE TITLE
[Crash] Applied Energistics 2 Advancement tab crash

### ISSUE THREAD

**Issue by remco082000** [FTBTeam/FTB-Sky-Adventures#116]
* **Modpack Version**: 
1.2.0 & 1.2.1

* **Issue**: 
When going to the advancements tab for Applied Energistics 2, the game crashes.

* **Link to Log or Crash File Paste**: 
https://pastebin.com/QEYAGkHi

* **Is it Repeatable?**: 
Yes

* **Mod/s Affected**: 
Applied Energistics 2 (rv6-stable-3)

* **Known Fix**: 
n/a

**Comment by InQuognito** [comment]
Same thing happens here. Just gotta avoid that tab until they patch it, I guess. It sucks though.

**Comment by dougburkhalter** [comment]
Having the same issue here as well. Running 1.2.1.

**Comment by tfox83** [comment]
fixed in next update
