### ISSUE TITLE
Can't load up mudpack

### ISSUE THREAD

**Issue by bsmop1** [FTBTeam/FTB-Sky-Adventures#117]
* **Modpack Version**: 1.2.1

* **Issue**: when I click play in twitch it loads up the old Minecraft launcher which creates an error every time I try to load it

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/8dbc73c0

* **Is it Repeatable?**: yes

* **Mod/s Affected**: none

* **Known Fix**: none

**Comment by tfox83** [comment]
You would need to report this to twitch.
