### ISSUE TITLE
Incorrect cost for Creative Energy Source

### ISSUE THREAD

**Issue by GalaxyGirl230** [FTBTeam/FTB-Sky-Adventures#118]
* **Modpack Version**: 1.0.0 (Minecraft 1.12.2  |  Forge 14.23.4.2765)

* **Issue**: Incorrect cost displayed for buying the Creative Energy Source. Quest name says "$15,000" but actual cost is $21,400.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes (If you call it repeatable)

* **Mod/s Affected**: FTB Quests and Good Ol' Currency Mod

* **Known Fix**: 2 options  |  Option 1 - Change Quest Title to "$21,400."  |  Option 2 - Change turn in cost from 214 $100 Bills to 150 $100 Bills.

-Spaceguy230
-Don't Forget To Be Awesome!

P.S. Sorry if this was already posted here. I looked through and didn't see anything, but I'm blind sometimes.

**Comment by iKurama** [comment]
https://github.com/FTBTeam/FTB-Sky-Adventures/issues/58

**Comment by GalaxyGirl230** [comment]
Thank you. I missed this one.
