### ISSUE TITLE
CareerBees/Gendustry server Crash

### ISSUE THREAD

**Issue by AcidaliaP** [FTBTeam/FTB-Sky-Adventures#119]
* Sky Adventures 1.1.0

* When putting an assassin queen bee, made in the gendustry Advanced Mutatron, into the gendustry Industrial Apiary, the server crashed and continues to crash, until the apiary is edited out.

* I'm not the server admin, so I can't find the logs.
* Other players have experienced the same phenomenon.

* CareerBees - 0.4.0
  Gendustry - 1.6.5.8

* Apiary must be edited out via world edit.
  Possibly adding something to the tool tip?

**Comment by Electrofried** [comment]
Am server admin, have log files. many many log files from server crash loop.
https://pastebin.com/tCGi7MZd

**Comment by Mordaii** [comment]
Just taking a quick peek,

Are you trying to power this with IC2?  I would try with different type of power if so.
From the crash log
-"ic2.core.block.wiring.TileEntityCable cannot be cast to forestry.api.apiculture.IBeeHousing"

Have you also searched the bug reports for the forestry and gendustry mods yet?  There might be a fix there.

Also, in the forge configs you and set these 2 params so you don't need world edit.  This dangerous, but I've never had it go crazy on me ...yet.

B:removeErroringEntities=true
B:removeErroringTileEntities=true

This automatically removes the blocks and keeps the server running.

Best wishes on fewer crashes.

**Comment by Electrofried** [comment]
It is not ic2 related, any TE in range of the bee will cause the issue, instantly if using gendustry apiaries.

https://github.com/rwtema/Careerbees/issues/23

open issue on the github for months with no action.
