### ISSUE TITLE
MP players join with creative by default

### ISSUE THREAD

**Issue by KingDan27** [FTBTeam/FTB-Sky-Adventures#12]
* **Modpack Version**: 1.0.0

* **Issue**: in myultiplayer players start in creative mode.

* **Link to Log or Crash File Paste**: none avail

* **Is it Repeatable?**: yes

* **Mod/s Affected**: none

* **Known Fix**: edit level.dat file and change GameType from 1 to 0 for the Server Upload Files

**Comment by KingDan27** [comment]
also set allowCommands to 0 in the same .dat file as this makes it so players can pull items out of jei even out of creative mode

**Comment by tfox83** [comment]
fixed
