### ISSUE TITLE
Ender shard not programming when hitting Ender Dragon

### ISSUE THREAD

**Issue by malmrose** [FTBTeam/FTB-Sky-Adventures#120]
* **Modpack Version**: 1.1

* **Issue**: Hitting the Ender Dragon does damage to him, but never programs the Ender Shard.

* **Is it Repeatable?**: Yes. I was able to kill him twice hitting him with only the Ender Shard.

**Comment by knoteye** [comment]
If this is for WOOT,  I just read that they disabled the Ender Dragon.

**Comment by malmrose** [comment]
Chaos Guardian was disabled. I haven't heard of the Ender Dragon being disabled.

**Comment by tfox83** [comment]
fixed in dev
