### ISSUE TITLE
Bloodmagic deaths do not trigger open blocks graves or deaths to be saved.

### ISSUE THREAD

**Issue by Electrofried** [FTBTeam/FTB-Sky-Adventures#121]
* **Modpack Version**: Sky Adventures 1.1.0

* **Issue**: Die from blood magic self sacrifice while using the dagger of sacrifice.
No grave is created. No openblocks death is registered and the /ob_inventory restore function lists no file at the time of death.

* **Link to Log or Crash File Paste**: no logs are generated beyond "Player died due to magic"

* **Is it Repeatable?**:  Unfortunately yes

* **Mod/s Affected**: OpenBlocks-1.12.2-1.8 and BloodMagic-1.12.2-2.3.3-101

* **Known Fix**: restoring player inventory via FTBu backups.

**Comment by tfox83** [comment]
there is no fix at this time, however it has been reported multiple times
