### ISSUE TITLE
Remove EMC-value from Akashic Tome

### ISSUE THREAD

**Issue by Yusunoha** [FTBTeam/FTB-Sky-Adventures#123]
Modpack Version: 1.1.0

Issue: Sooo, I started a new world and did something dumb... as soon as I crafted a transmutation table I started throwing everything with an EMC value into the table, including the Akashic Tome that contained all the manuals... 

Now, I can just pull out another Akashic Tome from the table, but it doesn't contain the manuals. No problem right? Just craft all the manuals yourself and put them into the Tome. 

Well... it's not quite that easy. Not all manuals will go into the Tome, and not all manuals are easily craftable due to overlapping recipes or resources that you can't obtain early on.

Link to Log or Crash File Paste: No log because it's not a crash.

Is it Repeatable?: Yup, just throw your Tome into the table and voila.

Mod/s Affected: AkashicTome-1.2-10 & ProjectE-1.12-PE1.3.1B

Known Fix: Either add a command that'll give you a new Akashic Tome with all the manuals inside and remove the EMC-values from the manuals, or the faster method, just remove the EMC-value from the Akashic Tome.

**Comment by CorruptedLink01** [comment]
Put 1 dirt in a crafting table to get the Tome with all the manuals

**Comment by tfox83** [comment]
fixed in dev
