### ISSUE TITLE
Cannot hand certain items in for quests

### ISSUE THREAD

**Issue by theplastichero** [FTBTeam/FTB-Sky-Adventures#124]
I have been having a problem where I cannot hand certain items in for quests, the reinforced drum of xp has been a problem as I have tried 5 times by filling a brand new drum each time but it wont accept it also I could not hand in a teir 6 viod miner so far I have just had to cheat them in to have the quest accept it, even though I had only just mae the miner it still would not accept it

**Comment by tfox83** [comment]
fixed in update
