### ISSUE TITLE
TiC Aluminum Brass has no EMC value

### ISSUE THREAD

**Issue by bassberry** [FTBTeam/FTB-Sky-Adventures#126]
* **Modpack Version**: 1.2.1

* **Issue**: The Aluminum Brass ingot from TiC doesn't have an EMC value anymore, although there is no hint in the changelog that it got removed again. I don't know if this is intended and just not stated in the changelog, or if the custom EMC value was removed by mistake again.
I guess the entry `tconstruct:ingots|5` with 128 emc got removed from `custom_emc.json` accidentally, since it was just between `minecraft:gold_nugget|0` and `tconstruct:nuggets|5` before all the nuggets got removed from the list again.

* **Known Fix**: Re-add `tconstruct:ingots|5` to `custom_emc.json` for 128 emc.

**Comment by tfox83** [comment]
fixed in dev
