### ISSUE TITLE
Vanilla rails dupe=free emc

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [FTBTeam/FTB-Sky-Adventures#127]
* **Modpack Version**: ANY

* **Issue**: duping rails with vanilla slimeblock contraption make for free emc

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: yes

* **Mod/s Affected**: projectE

* **Known Fix**: remove emc value from rails, powered rails and carpets

**Comment by iKurama** [comment]
https://github.com/FTBTeam/FTB-Sky-Adventures/issues/103
