### ISSUE TITLE
Refined Storage Crafting Grid Money Dupe

### ISSUE THREAD

**Issue by blitzyuk** [FTBTeam/FTB-Sky-Adventures#128]
version 1.1.0

I have found a money dupe with an unpowered  Refined Storage Crafting Grid. Placing any of the notes or coins into the crafting table part and shift clicking the note will dupe it and you are able to get full stacks of the desired item.

Actually made a gif image showing the dupe https://i.imgur.com/s6Kjb5t.gifv

This is repeatable with all the currency from Good Ol' Currency Mod

no known fix

**Comment by iKurama** [comment]
https://github.com/raoulvdberge/refinedstorage/issues/2017
https://github.com/raoulvdberge/refinedstorage/issues/1989

**Comment by blitzyuk** [comment]
So Guessing since those 2 threads were closed last month it still isn't fixed.

**Comment by iKurama** [comment]
The version mentioned as 'dev' is version 1.6.6. In version 1.2.0, RS has been updated to version 1.6.8.

TL:DR: It has been fixed in 1.2.0 and every version ahead of it.
https://gyazo.com/3570fb74d7d6d5367e2cad63e55b43f8

**Comment by dingsbums** [comment]
It's still possible to dupe. 

Put money in unpowered crafting grid. Shit-click it out. When you right click the grid the recipe is still filled. 

https://imgur.com/a/wyA0I8D

P.S.: Works of course with other items, not only money.

**Comment by tfox83** [comment]
fixed in latest update
