### ISSUE TITLE
Request:Please add extra cells.

### ISSUE THREAD

**Issue by Avi-E-Koenig** [FTBTeam/FTB-Sky-Adventures#129]
Neither ae2 nor refined storage can have patterns requiring fluids.

This makes automating certain complex recipes like flux armor,thrusters etc needlessly difficult.

your consideration on this matter is most appreciated :)

**Comment by tfox83** [comment]
Extra Cells is built into AE2 now.  What ever functions didnt make the merge I have no control of.

**Comment by jk1895** [comment]
This mod has these things... _extra_ big _cells_. And of course the fluid assembler. So, no, Extra Cells is not built into AE2 and it is absolutely essential. I added it by my self.
