### ISSUE TITLE
Refined Storage Disk

### ISSUE THREAD

**Issue by type0780** [FTBTeam/FTB-Sky-Adventures#13]
Modpack Version: 1.0.0

Issue: The 64K Storage Disk from Refined Storage you get from the Quest Rewards are not working in the Disk Drive. It does not recognize the Disk

 Is it Repeatable?: Yes

Mod/s Affected: Refined Storage

![2018-10-17_08 20 08](https://user-images.githubusercontent.com/43846007/47066286-dc632080-d1e5-11e8-85ef-baf53e7f2435.png)

**Comment by ProsperCraft** [comment]
Same here- the one you craft has more data.

![2018-10-17_13 55 12](https://user-images.githubusercontent.com/4427684/47112729-6cb85a00-d214-11e8-8b7f-be9f51375dd3.png)
![2018-10-17_13 55 14](https://user-images.githubusercontent.com/4427684/47112731-6d50f080-d214-11e8-9d6b-8ef606f28a30.png)

**Comment by tfox83** [comment]
Changed to drop 64k components in next update.  Also added recipe to recover said component from null NBT disks given before update
