### ISSUE TITLE
Hatchery Egg Won't Craft Into Regular Egg

### ISSUE THREAD

**Issue by jessep13** [FTBTeam/FTB-Sky-Adventures#130]
* **Modpack Version**: 1.1.0

* **Issue**: When I put a hatchery egg into the crafting grid, it doesn't output any regular egg (by regular, i mean the egg present in vanilla minecraft). JEI however states that this is supposed to give out a regular egg, and i'm using the correct type of egg for it, as when I click on the plus button to automatically set the ingredients in the right place for the recipe, it places the egg i tried to use without JEI in the correct spot, but it still doesn't give out any regular egg. I'm unsure if this problem is only from Hatchery (which isn't an external mod, but instead a mod in the modpack) or from this modpack.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/811b844c (Note: I did use MultiMC to download the modpack, hence why its stated on the top of the log)

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Might be Hatchery itself, but I don't know. Could also be JEI being misleading

* **Known Fix**: No

**Comment by tfox83** [comment]
fixed in dev
