### ISSUE TITLE
Unable to turn in Witchwater repeatable quest

### ISSUE THREAD

**Issue by charles7926** [FTBTeam/FTB-Sky-Adventures#131]
* **Modpack Version**: 
1.2.1  and 1.1.0
* **Issue**: 
Unable to turn in witchwater repeatable quest.  Have an iron drum full of witch water and the quest will not accept it.

* **Is it Repeatable?**:
Yes

**Comment by knoteye** [comment]
Might be late, but make sure the barrel is completely full. I was having issues, barrel was half a bucket short.

**Comment by tfox83** [comment]
Correct, make sure its completely full.
