### ISSUE TITLE
Suggested: Remove EMC From Chisel Blocks

### ISSUE THREAD

**Issue by Eifekk** [FTBTeam/FTB-Sky-Adventures#132]
I have used the tome from the quest rewards to unlock all transmutation recipes. upon searching for planks I've noticed that all the chisel varieties of planks have an emc value. this really clutters the search and makes it difficult to browse the wood types. and is highly unnecessary since you can literally chisel an entire inventory with a single shift+click. I suggest removing the emc value on all chiselled blocks, only retaining it on the original blocks.

edit: same thing with searching cobblestone and such.

**Comment by tfox83** [comment]
At this time I am leaving EMC on them as it doesnt cause any issues.
