### ISSUE TITLE
Sky Adventures world crash

### ISSUE THREAD

**Issue by Maxipyke** [FTBTeam/FTB-Sky-Adventures#133]
https://paste.feed-the-beast.com/view/5246008d
That's the crash log.

**Comment by iKurama** [comment]
Can you recreate the crash without using Optifine?

**Comment by Maxipyke** [comment]
My pc is a potato i cant pllay that pack without using Optifine.

27 Eki 2018 Cmt 19:26 tarihinde iKurama <notifications@github.com> şunu
yazdı:

**Comment by Maxipyke** [comment]
Okay i'll
