### ISSUE TITLE
Crash looking at advancements (and it repros)

### ISSUE THREAD

**Issue by DelfCo** [FTBTeam/FTB-Sky-Adventures#135]
* **Modpack Version**: 1.2.1

* **Issue**: Looking through advancements UI. Last thing I did was click on the AE2 tab.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/e2792faf

* **Is it Repeatable?**: Yes. At least, when I restarted the save, and clicked the same AE2 Advancements tab, it crashed again, and the crash file shows the same stack.

* **Mod/s Affected**: Not sure. This is stock Sky Adventures, nothing modded by me.

* **Known Fix**: no known fix

**Comment by DelfCo** [comment]
I see that this is a dupe of issue [#116](https://github.com/FTBTeam/FTB-Sky-Adventures/issues/116).

**Comment by DelfCo** [comment]
I've tried this a couple of different ways, and it's going to the AE2 tab that does it, no matter which tab I'm coming from.

**Comment by tfox83** [comment]
fixed in dev
