### ISSUE TITLE
[Suggestion] Please add Equivalent Energistics or Equivalent Integrations

### ISSUE THREAD

**Issue by jk1895** [FTBTeam/FTB-Sky-Adventures#136]
Hello,
please add [Equivalent Energistics](https://www.curseforge.com/minecraft/mc-mods/equivalent-energistics) or [Equivalent Integrations](https://www.curseforge.com/minecraft/mc-mods/equivalent-integrations) to the pack.

It would be very cool when you could add one of these mods. Maybe even both. I prefer Eqivalent Energistics but the other one is also working with Refined Storage and could be the better choice.

Is there a specific reason why you didn't add these mods so far?

Thank you for your time and the great modpack!

**Comment by Schildos** [comment]
#9 , #108

Was removed due to being unstable during testing

**Comment by jk1895** [comment]
Equivalent **Storage** was unstable not Energistics or Integrations.

**Comment by jk1895** [comment]
Short additional information.

I tested both mods and Equivalent Energistics is out because it creates lag when you have learned the book of wisdom and the more items are in the pack. The lag is noticeable by placing and breaking AE2 suff. 

Equivalent Integrations don't care how many items you have learned and is working like a charm. This is really a great mod. It shows how many items you can create depending on your EMC value stored in your transmutation table. Absolutely great.

Please try it if you don't know this relatively new mod. I had no crashes or other problems so far...

Greetings

**Comment by Deadpsycho** [comment]
Please add Equivalent Integrations

**Comment by klaaswhite** [comment]
@jk1895 in your last comment, did you mean integrations or energistics is buggy?
You said 2 times integrations

**Comment by jk1895** [comment]
Oh sorry! What a dumb mistake! I edited my post. Buggy was Equivalent
Energistics.
Thank you for mentioning it.


Am Mi., 12. Dez. 2018 um 18:09 Uhr schrieb klaaswhite <
notifications@github.com>:
