### ISSUE TITLE
Exception with Nature Compass and fast crafting

### ISSUE THREAD

**Issue by MasterYinan** [FTBTeam/FTB-Sky-Adventures#137]
* **Modpack Version**: 1.2.1 (Beta)

* **Issue**: Nature Compass causes an Exception when you try to click the "plus" sign to automatically add all the ingredients to the crafting grid.

Error Message ist:

Connection Lost
Internal Exception: java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes

* **Is it Repeatable?**: Yes

**Comment by twsx** [comment]
Note: I think this happens with all recipes that contain saplings.

**Comment by tfox83** [comment]
Fixed in dev
