### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by 0dikpah** [FTBTeam/FTB-Sky-Adventures#138]
* **Modpack Version**: FTB Sky Adventures 1.12
Crashes when i start my world

[crash-2018-10-27_23.50.58-server.txt](https://github.com/FTBTeam/FTB-Sky-Adventures/files/2522228/crash-2018-10-27_23.50.58-server.txt)

**Comment by 0dikpah** [comment]
please fix..iv'e been playing many hours on my world :(

**Comment by tfox83** [comment]
Please try a fresh install, am not able to reproduce.
