### ISSUE TITLE
FTB Quests - Cfg to allow multiple party rewards?

### ISSUE THREAD

**Issue by cauliflower69** [FTBTeam/FTB-Sky-Adventures#14]
As the title. Is there a cfg to allow multiple party rewards?

**Comment by tfox83** [comment]
nope, its disabled pack wide as it breaks the currency system

**Comment by MathiasDeWeerdt** [comment]
> nope, its disabled pack wide as it breaks the currency system

Would it be possible to make the wallet claim-able more then once, since other players could really use the wallet.
