### ISSUE TITLE
Roost Breeder UI visual glitch related to TC Smeltery

### ISSUE THREAD

**Issue by perlguy** [FTBTeam/FTB-Sky-Adventures#140]
* **Modpack Version**: 1.2.1

* **Issue**:  UI glitch with breeders - items go invisible a random amount of time after opening UI.  Items are not gone, just not  visible.

* **Is it Repeatable?**: 

I was able to reduce the problem to breeders located in the same chuck with a TC smeltery.  The smeltery has to be 3x3 and at least 6 high (54 slot inventory).  Tested in a new world, cheating the items in from JEI, and saw the same behavior.

* **Mod/s Affected**:  Roost and Tinker's.

* **Known Fix**: put smeltery in a chunk by itself... or keep it smaller than 3x3x6

This issue also exists in StoneBlock 1.0.25 (I'm playing both at the moment and found this reported there first - added similar comments there before coming back here to report it).  I vaguely remember having this problem before with other inventories in some previous pack but never bothered to narrrow down the cause before.

Trying to breed chickens with them randomly disappearing as you inspect their stats is really annoying, which prodded me to figure out the cause.  I'm just going to move my smeltery to a dedicated chunk as I don't use it much at this stage, but since I was able to narrow down the conditions to reproduce it, I thought you (and possibly others) would like to know.  

Thanks for the great pack!

**Comment by twsx** [comment]
Note: This is a general problem with inventories near smelteries, and not specific to Roost.

**Comment by tfox83** [comment]
No fix at this time.
