### ISSUE TITLE
crash before load

### ISSUE THREAD

**Issue by zoxec** [FTBTeam/FTB-Sky-Adventures#141]
Hi, I have this problem with loading the game, it crashes before start playing. I repeated downloading the modpack but it didn´t work. Always crash at the same spot. There is a picture of last file downlanded before crash. 1.12.1 modpack
![vystrizek](https://user-images.githubusercontent.com/44546583/47615978-f68ae180-dab6-11e8-971b-2b158a9f017e.PNG)
there is log https://paste.feed-the-beast.com/view/d16d576c
Please help me with this problem.

**Comment by Espergium** [comment]
You don't need a crash log for this one as it's in plain sight. You are only allocating 1.8gb of ram to this minecraft install and it can't finish booting up because of it. Try 4gb as a minimum.

The steps to do this are different based on what launcher you use.

**Comment by zoxec** [comment]
I am using this launcher 
![ds](https://user-images.githubusercontent.com/44546583/47634675-a5303000-db52-11e8-9fb1-73db924efebd.PNG)
Do you know how to increase my ram? I think I have 8GB in my pc

**Comment by zoxec** [comment]
Oh I found it in options, thanks for your time

**Comment by Espergium** [comment]
Ok. That launcher is bad.

I strongly recommend you get that thing off your computer right now as it is a hacked launcher. Get the official FTB launcher or the twitch client. Not only that, the website you got this from hides all the downloads behind adfly links---he's literally stealing money off of FTB and editing the launchers with who knows what.

Support beyond this is null and void and your computer security is at full risk. If you're using a cracked client then buy the game. There is no support for hacked or cracked accounts.
