### ISSUE TITLE
Applied energistics crashing pack

### ISSUE THREAD

**Issue by BigBadTom** [FTBTeam/FTB-Sky-Adventures#142]
* **Modpack Version**: 1.2.1 - 1.12.2

* **Issue**: autocrafting plant gather in AE system, as soon as i press start the pack crashes

* **Link to Log or Crash File Paste**: https://paste.dimdev.org/uhuvifotoz.mccrash

* **Is it Repeatable?**: the issue is repeating in my world after re building the me system and re making the patterns

* **Mod/s Affected**: crash screen shows applied energistics

* **Known Fix**: set computer on fire....... a problem gone is a problem fixed right?

**Comment by tfox83** [comment]
Fixed in dev
