### ISSUE TITLE
Quests Certus Quartz Crystal and Charged Certus Quartz Crystal still have 25 cents as reward

### ISSUE THREAD

**Issue by remco082000** [FTBTeam/FTB-Sky-Adventures#143]
* **Modpack Version**: 
1.2.1

* **Issue**: 
The quest rewards for Certus Quartz Crystal and Charged Certus Quartz Crystal still have 25 cents as reward, but the v1.2.0 states this is no longer the case.

* **Link to Log or Crash File Paste**: 
Not applicable

* **Is it Repeatable?**: 
Yes

* **Mod/s Affected**: 
FTB Quests / Good Ol' Currency Mod

* **Known Fix**: 
Change the quest rewards

**Comment by tfox83** [comment]
fixed in dev, thanks
