### ISSUE TITLE
No bats? 

### ISSUE THREAD

**Issue by AnimeNerdDJBROS** [FTBTeam/FTB-Sky-Adventures#145]
* **Modpack Version**: 1.1.0

* **Issue**:  I have been trying to craft an angel ring but none have spawned and it's been days since I made the mob farm (I started first day it was released and had the mob farm since maybe day 2)

* **Link to Log or Crash File Paste**: No crash nor log connected to it

* **Is it Repeatable?**: not really that type of bug just not spawning a mob.

* **Mod/s Affected**: None unless you count not being able to make an angel ring.

* **Known Fix**: No known fix, which is why I brought it here.

**Comment by iKurama** [comment]
You need to make dark rooms around y50-y60 (roof has to be 64, if that's your maximum)

**Comment by AnimeNerdDJBROS** [comment]
k

**Comment by AnimeNerdDJBROS** [comment]
y 64 is the bottom of it for mine.
