### ISSUE TITLE
Lamps crashing server

### ISSUE THREAD

**Issue by Necrocat7** [FTBTeam/FTB-Sky-Adventures#146]
* **Modpack Version**: 1.1.0

* **Issue**: My friend wanted to crate a floor with inverted black lamps, so he tried to wand them and it crashed/ lagged the world/server and his "creative world he went to test the issue out on.

* **Link to Log or Crash File Paste**: [crash-2018-10-28_19.38.06-server.txt](https://github.com/FTBTeam/FTB-Sky-Adventures/files/2523430/crash-2018-10-28_19.38.06-server.txt)

* **Is it Repeatable?**:  The issue was repeatable.

**Comment by tfox83** [comment]
Please try a fresh install, I am not able to reproduce
