### ISSUE TITLE
quest screen dont work properly

### ISSUE THREAD

**Issue by voidegg** [FTBTeam/FTB-Sky-Adventures#147]
ver :1.2.1

when i open the quest book my screen messed up.

![2018-10-29_16 12 25](https://user-images.githubusercontent.com/42865598/47655575-ef86d080-db95-11e8-8375-b71358c804f3.png)

**Comment by iKurama** [comment]
Could you restart the game?

**Comment by voidegg** [comment]
i can but i need to guess where the button is

**Comment by tfox83** [comment]
Please try a fresh install of the pack and have at least 4GB assigned to java.
