### ISSUE TITLE
rtp command crashes MP server

### ISSUE THREAD

**Issue by unlimitedsola** [FTBTeam/FTB-Sky-Adventures#148]
* **Modpack Version**: 
1.2.1

* **Issue**: 

when executing `rtp` command, server crashes because of ticking times out

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

yes

* **Mod/s Affected**: 

* **Known Fix**: 

none

**Comment by unlimitedsola** [comment]
I dead in the temple trap, after then, I respawned at lobby island instead of the island for my team.
so I was finding a way to teleport to my island, and I accidentally executed the `rtp` command which causes server crashing

**Comment by iKurama** [comment]
I don't recall that any mod adds that command. Sponge isn't supported either.

**Comment by lachian** [comment]
FTBU is one of the main mod's in this pack and it adds a few commands (check their config to see all that it can be en- or dis-abled) including /rtp for random teleport.
