### ISSUE TITLE
I died. How do i get the questbook back

### ISSUE THREAD

**Issue by Sn0wflame** [FTBTeam/FTB-Sky-Adventures#149]
* **Modpack Version**: 
1.1.0
* **Issue**: 
I died. How do i get the questbook back
* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Sn0wflame** [comment]
i lost my things to the void. gravestone is not there

**Comment by remco082000** [comment]
In version 1.2.0 and up you can craft it, see #67 
Also, if the grave didn't spawn, you should be able to get your items back with the command /ob_inventory restore if you want.

**Comment by Sn0wflame** [comment]
Thank you

**Comment by ProsperCraft** [comment]
You don't need a questbook, change drop item to delete, then map questbook to q

**Comment by tfox83** [comment]
craftable in 1.2.0+
