### ISSUE TITLE
Server lag 

### ISSUE THREAD

**Issue by avidgamer5918** [FTBTeam/FTB-Sky-Adventures#150]
* **Modpack Version**: 1.2.1

* **Issue**: server lag which I think is cased by Reborn Storage 

* **Link to Log or Crash File Paste**: https://pastebin.com/W1MHKjRs

* **Is it Repeatable?**: n/a
* **Mod/s Affected**:Reborn Storage 

* **Known Fix**: had to disable the server watchdog by changing the max tick time to -1 which fixed the server crashing but not the lag.

**Comment by ProsperCraft** [comment]
We got it to the point where the server hard locked, here is my report- 
https://github.com/raoulvdberge/refinedstorage/issues/2068

**Comment by avidgamer5918** [comment]
I did some profiles with lag goggles removed a rs cable from a reborn storage auto crafter and got rid of a bunch of mobs that were in one area and that seem to solve the problem.
