### ISSUE TITLE
Cant craft bee hives with carpenter.

### ISSUE THREAD

**Issue by angrylightning** [FTBTeam/FTB-Sky-Adventures#151]
* **Modpack Version**: 1.2.1

* **Issue**:  Jei shows ways to craft bee hives but the carpenter won't register there's a recipe when you put the ingredients and recipe in

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Forestry 

* **Known Fix**:

**Comment by remco082000** [comment]
Just to be sure; you have 1 bucket of seed oil in the carpenter?
![image](https://user-images.githubusercontent.com/22686088/47737459-457c7680-dc71-11e8-809b-28a8622584ff.png)

**Comment by angrylightning** [comment]
![2018-11-05_12 52 17](https://user-images.githubusercontent.com/44616196/48016569-f2377780-e0f9-11e8-8511-6b1e682ff2ea.png)
I did it still wasn't working

**Comment by tfox83** [comment]
try a fresh install, it is working fine for me and my testers.
