### ISSUE TITLE
Squids don't drop any ink sacs

### ISSUE THREAD

**Issue by flann** [FTBTeam/FTB-Sky-Adventures#152]
* **Modpack Version**: 
 
1.2.1

* **Issue**: 

I have a little squid farm > 64 blocks from spawn at level 55. See the attached image. It spawns LOTS of squids and kills them pretty effectively, but after a very long time AFK, I haven't got a single ink sac.

Image: 
![2018-10-31_06 17 49](https://user-images.githubusercontent.com/7347487/47789188-814b2680-dcd9-11e8-8efe-2c1515bf65ef.png)

* **Link to Log or Crash File Paste**: 

No crash

* **Is it Repeatable?**: 

Yep. I can run for a very long time with no drops.

* **Mod/s Affected**: 

? Sorry, don't know what would influence this.

* **Known Fix**: 

Don't know how to fix. Any workaround?

**Comment by iKurama** [comment]
You can get an ink sac through the fishing quest. It has EMC so you can 'dupe' them in the transmutation table.

**Comment by flann** [comment]
Yeah, I ended up using a morb to catch squids in my squid farm, then running the morb through a centrifugal separator with a enstabulation apparatus augment to get the ink. That turned out to be a good way to get leather from cows, too, since they don't seem to drop anything when you kill them, either.

I'm still curious about which mod or configuration is turning off the drops, though.

**Comment by flann** [comment]
Well, I guess this is by design, so I'll close this.
