### ISSUE TITLE
handing in 16.000 overclockers

### ISSUE THREAD

**Issue by sjonnieh** [FTBTeam/FTB-Sky-Adventures#155]
ok so i automated the overclockers for $$$ and now i want to hand them in but everything needs to be handed in single can we make it so we can hand in multiple at once else i need to click the thing 2000+ times.

**Comment by EastArctica** [comment]
make an auto hotkey script
should look like this

```
SendMode Input ; Much faster execution
SetWorkingDir %A_ScriptDir%

^P:: ; Command to start (Ctrl+P)
	MouseClick, left, X, Y ; executes a left click on cords X, Y (aka turns in quest)
	Sleep 10
	MouseClick, left, X, Y ; executes a left click on cords X, Y (aka takes money)
	Sleep 10
	MouseClick, left, X, Y ; executes a left click on cords X, Y (aka takes other money)
return
+P::ExitApp ; Closes the script (Shift+P)
```
Edit: To find your X and Y cords use the AHK script below it is a little laggy but it works

[Cords.zip](https://github.com/FTBTeam/FTB-Sky-Adventures/files/2545039/Cords.zip)

**Comment by sjonnieh** [comment]
thanks for the reply but i dont know how to do this scripting thing.

**Comment by EastArctica** [comment]
Here ya go 
https://youtu.be/CbKmmgKxc8U
made it just for you

**Comment by sjonnieh** [comment]
hey thx for the vid .

**Comment by tfox83** [comment]
He is working on a mass turn in with quests in the latest dev
