### ISSUE TITLE
Klein Star Sphere has no JEI Crafting recipe

### ISSUE THREAD

**Issue by tootiecornet4** [FTBTeam/FTB-Sky-Adventures#157]
Modpack Version: 1.2.1

Issue: Klein Star Sphere has no JEI visual recipe, however can still be crafted. 

Link to Log or Crash File Paste: N/A 

Is it Repeatable?: N/A

Mod/s Affected: JEI

**Comment by iKurama** [comment]
https://github.com/FTBTeam/FTB-Sky-Adventures/issues/48
