### ISSUE TITLE
Quest book issue

### ISSUE THREAD

**Issue by AlexTeplyh** [FTBTeam/FTB-Sky-Adventures#158]
* **Modpack Version**: 1.2.0

* **Issue**: When you complete all quests in "Storage solutions" tab in the quest book, it is not marking the tab with a green checkmark. My last quest was AE2 singularity.

* **Is it Repeatable?**: Yes. I've reloaded world and nothing changed

**Comment by remco082000** [comment]
This is fixed in 1.2.1, see #91
