### ISSUE TITLE
Single player crash while using Thermal Foundation's Forge Lexicon

### ISSUE THREAD

**Issue by lsilich04** [FTBTeam/FTB-Sky-Adventures#159]
* **Modpack Version**: 1.2.1

* **Issue**: Browsing through the Forge Lexicon volume (a transformed Akashic Tome) caused a crash shortly after interacting with the "i" button on the left and clicking repeatedly on an entry, specifically blockHardenedGlass in this case

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/fe6ccdde

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Thermal Foundation

**Comment by tfox83** [comment]
fixed in latest dev
