### ISSUE TITLE
UU matter quest takes 1 millibucket

### ISSUE THREAD

**Issue by Exobe** [FTBTeam/FTB-Sky-Adventures#16]
* **Modpack Version**: 1.0.0

* **Issue**: The repeatable UU matter quest takes 1 millibucket, and I can confirm it actually takes a stone barrel with 1 millibucket.

* **Is it Repeatable?**: Yes

![uu matter quest bug](https://user-images.githubusercontent.com/32541469/47114502-38936800-d219-11e8-9f55-eea10a6f2cca.png)

**Comment by tfox83** [comment]
fixed in dev
