### ISSUE TITLE
Mod Pack crash when loading Applied Energistics 2

### ISSUE THREAD

**Issue by Kit-Pan** [FTBTeam/FTB-Sky-Adventures#161]
* **Modpack Version**: Version 1.1.0- latest version on Twitch Launcher

* **Issue**: The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Applied Energistics 2 (appliedenergistics2)

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/d4dc66df

* **Is it Repeatable?**: I have rebooted my computer multiple times, always with the same issue. However, earlier this morning I was able to load up just fine. Not sure if it is a new change that has caused this...

* **Mod/s Affected**: Supposedly AppliedEnergistics2

**Comment by tfox83** [comment]
Please try a fresh install with latest version of the pack.
