### ISSUE TITLE
Quest "Klein Star Omega" can be completed with any lower tier Klein Stars

### ISSUE THREAD

**Issue by CometicRush** [FTBTeam/FTB-Sky-Adventures#163]
* **Modpack Version**: FTB Sky Adventures 1.2.1

* **Issue**: You can just submit Klein Star Ein for the quest "Klein Star Omega".

* **Link to Log or Crash File Paste**: -

* **Is it Repeatable?**: Yes, I guess.

* **Mod/s Affected**: ProjectE, FTB Quests

* **Known Fix**: I don't have any specific idea about this. Sorry.

**Comment by tfox83** [comment]
Fixed in dev.
