### ISSUE TITLE
Player data rolled back after completing quest "Klein Star Omega"

### ISSUE THREAD

**Issue by CometicRush** [FTBTeam/FTB-Sky-Adventures#164]
* **Modpack Version**: FTB Sky Adventures 1.2.1

* **Issue**: 
After I complete the quest "Klein Star Omega", exit the world and then re-enter that world. And then all my items are gone. (Actually some wooden tools I might have used early were there.)

This happened after I discovered the issue I posted -- I thought that not submitting proper item make items disappear at first.
So I made Klein Star Omega, submitted, but same thing happened.

* **Link to Log or Crash File Paste**: No crash reports were created.

* **Is it Repeatable?**: Yeah, I tried with Klein Star Ein twice and with Klein Star Omega.

* **Mod/s Affected**: I don't know exactly, but I guess ProjectE and FTB Quests?

* **Known Fix**: I can't think any of the breakthroughs.

**Comment by tfox83** [comment]
I am not able to reproduce, if playing SSP please try a fresh install.
