### ISSUE TITLE
crashes on nether

### ISSUE THREAD

**Issue by EVSkyFall** [FTBTeam/FTB-Sky-Adventures#165]
* **Modpack Version**: 1.2.1

* **Issue**: Minecraft crashes when entering nether or doing somethig in nether

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/7352d9ff

* **Is it Repeatable?**: yes

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by tfox83** [comment]
please try a fresh install, I am not able to reproduce
