### ISSUE TITLE
loot crate consumed but no reward in inventory

### ISSUE THREAD

**Issue by gtxjgk** [FTBTeam/FTB-Sky-Adventures#166]
-->

* **Modpack Version**: 1.2.1

* **Issue**: loot crate is consummed but there is no new reward  in inventory and also no crash
where does loot values of loot crate  is there in .minecraft 

* **Link to Log or Crash File Paste**: NO CRASH!!!! 

* **Is it Repeatable?**:  yes 

* **Mod/s Affected**:  DO not know

* **Known Fix**:

**Comment by MCCatboyTV** [comment]
https://www.dropbox.com/s/045akugogi33gmy/2018-11-04%2015-13-02.mp4?dl=0

this is a link to the video i made of the opening of a legendery lootchest.

**Comment by HybridJK** [comment]
I am on the same server and the same thing happens to me. Maybe it's a server side issue?

**Comment by tfox83** [comment]
Am not able to reproduce and just opened a full stack of them.
