### ISSUE TITLE
recipie Conflict

### ISSUE THREAD

**Issue by gtxjgk** [FTBTeam/FTB-Sky-Adventures#167]
* **Modpack Version**:1.2.1

* **Issue**: recipie conflict between wooden hammer and chisel and bits  wooden wretch

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**:yes try to craft wooden hammer from ex nhilo

* **Mod/s Affected**: 

* **Known Fix**: Use stone hammer

**Comment by i3130002** [comment]
Having the same problem in here. 

Tried 

- Disabling chisel and bits didn't worked

- Disabling wrench from mod configuration of chisel and bits also didn't worked

Please provide a help as 1- This is a beginner item and people need to use it 2- This is also a quest item.

**Comment by tfox83** [comment]
![image](https://user-images.githubusercontent.com/4246308/48576863-793ed980-e8ca-11e8-9a40-444bab7627f2.png)
![image](https://user-images.githubusercontent.com/4246308/48576905-91aef400-e8ca-11e8-8b57-aff2bf73d795.png)

**Comment by tfox83** [comment]
Am not seeing the conflict.

**Comment by i3130002** [comment]
![image](https://user-images.githubusercontent.com/11602376/48676844-90f3b780-eb81-11e8-834d-be0982ac44b7.png)


FTB-Sky-Adventures 1.2.1(From TLuncher 2.48)

**Comment by tfox83** [comment]
Please do a fresh install, that recipe fix was in the scripts folder since before release.  Sounds like your scripts didn’t download/install properly.  Same goes for server if playing on a server as those recipes will override your client.

**Comment by tfox83** [comment]
Also have no idea what TLuncher is, but it might not be installing the scripts properly.  We only support the FTB launcher and Vanilla Launcher (Twitch uses the vanilla launcher)

**Comment by i3130002** [comment]
> ave no idea what TLuncher is, but it might not be installing the scripts properly. We only support the FTB launcher and Vanilla Launch

This is an all in one Luncher to download moded minecraft from [here ](https://tlauncher.org/en/)


> Please do a fresh install, that recipe fix was in the scripts folder since before release. Sounds like your scripts didn’t download/install properly. Same goes for server if playing on a server as those recipes will override your client.

There should be a problem with packet then, I have no access to official install (Sanctions against my country !) 

Thanks by the way
