### ISSUE TITLE
Different dyes have different EMC values

### ISSUE THREAD

**Issue by SilencedGoose** [FTBTeam/FTB-Sky-Adventures#168]
* **Modpack Version**: 1.2.1

* **Issue**: Different colours of dyes have different EMC values, meaning that the EMC value of anything dyed changes depending on what colour the dye is. This seems pointless since all of the dyes take the same amount of effort to get.

* **Is it Repeatable?**: Yes, just look at the EMC values.

**Comment by knoteye** [comment]
I noticed that as well, I assumed that the increase in EMC is with colors that need to be mixed. It takes two components to make that color, so it is more expensive. I am not sure if it is intended or not.

**Comment by metalim** [comment]
Leaving "in a perfect world" aside, why is that an issue? What does it break?

**Comment by tfox83** [comment]
Its intended
