### ISSUE TITLE
Balance: Repeatable Quest Enzyme too easy for that reward.

### ISSUE THREAD

**Issue by Redstymp** [FTBTeam/FTB-Sky-Adventures#169]
* **Modpack Version**: 1.2.1

* **Issue**: The Setup for the repeatable quest with enzyme is far too easy imo. Simply chaining two incubators. The first one just needs a little bacteria 5mb or so, then it can produce bacteria indefinetely.
Now you just need a second incubator, wheich you fill with sugar and get (almost) free enzymes.
Compared to the "harder" repeatable quests of the empowered crystal block and the overclocker upgrades, its ridiculous easy.

* **Is it Repeatable?**: Yes,

* **Mod/s Affected**: Binnie's Genetics, FTB Quests

* **Known Fix**:  Remove the repeatable quest for enzyme, make the crafting recipe/chain harder, ask for more items or reduce the reward

**Comment by twsx** [comment]
Can confirm that I abused this in both of my playthroughs. With a very much unimpressive setup of 3 lines of 3 incubators, you already make Enzyme faster than you can turn it in.

**Comment by Redstymp** [comment]
I abused 1 incubator producing bacteria from bacteria (0mb -> 5mb) feeding into 3 incubators which produced the enzyme. 5 minute setup for easy money. Only thing you need to do is feed it sugar but it has low emc so no real problem.
If the newer Version for FTB-Quests gets added it is even more broken since you can just turn it in and collect the rewards with 1 Buton click.

**Comment by tfox83** [comment]
removed in dev
