### ISSUE TITLE
ExtraUtilities Golden Lasso not craftable + Mod suggestion

### ISSUE THREAD

**Issue by Onigeshi** [FTBTeam/FTB-Sky-Adventures#17]
* **Modpack Version**: 1.0.0
* **Issue**: Golden Lasso from Extra Utilities not craftable
* **Mod/s Affected**: extrautilities

Is this intended? I looked in the crafttweaker scripts/extrautilities config ( in the config its enabled ) and didn't find anything about removing or disabling the golden lasso... So im confused about it not being craftable on purpose or its bug.. 

Also, would be nice to add Toast Control, those tips are really annoying.. for me at least.. I added it myself, but maybe it could be added "officialy"..

**Comment by lachian** [comment]
Lassos are still craft able, just the recipe is missing in JEI. 4 golden nuggets in the corner, 4 string in between, make sure you have 8 levels and it crafts. 

Sounds like an old bug like https://github.com/rwtema/extrautilities_old_issues/issues/1003

**Comment by tfox83** [comment]
Toast control is added in, also as lachian said they are still craftable, just a long standing bug making them not visible.
