### ISSUE TITLE
Animals aren't spawning.

### ISSUE THREAD

**Issue by LordHephaestus** [FTBTeam/FTB-Sky-Adventures#172]
* **Modpack Version**: Version 1.2.1

* **Issue**: Animals aren't spawning. I have no problem getting squids or hostile mobs to spawn but no chickens, pig, or cows. I made a large grass area for them to spawn in but nothing. The starting water chicken and the clay chicken from the quest rewards spawned when used but no other chickens have spawned.

![image](https://user-images.githubusercontent.com/44727332/47953049-7bee1600-df3d-11e8-85b5-d7420765ab6f.png)

**Comment by Ravalli03** [comment]
Having the same issue, I haven't been able to spawn any animals, ie chicken, for the eggs to progress the Chickens Mod.

**Comment by knoteye** [comment]
Check the biome your area is built in.
From the wiki
Animals do not spawn in desert, beach or ocean biomes, with the exception of rabbits and squid, and only mooshrooms will spawn in mushroom fields biomes. Rabbits can only spawn in desert, flower forest, snowy tundra, taiga, giant tree taiga, and snowy taiga biomes, and mooshrooms can only spawn in mushroom fields biomes.

**Comment by LordHephaestus** [comment]
Thanks. That was the problem My spawn is forest but I am completely surrounded by deep ocean and beach. but I did find one planes area and was able to span some animals.
