### ISSUE TITLE
Crash upon loading AE2 advancements

### ISSUE THREAD

**Issue by CometicRush** [FTBTeam/FTB-Sky-Adventures#173]
* **Modpack Version**: FTB Sky Adventures 1.2.1

* **Issue**: When selecting AE2 on Advancements, Minecraft client stops and crash (almost) immediately.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/03dbf735

* **Is it Repeatable?**: Yes, I think. I tried it about 3~4 times.

* **Mod/s Affected**: Better Advancements, Applied Energistics 2(?)

* **Known Fix**: I don't have any good idea about this.

**Comment by iKurama** [comment]
https://github.com/FTBTeam/FTB-Sky-Adventures/issues/116
https://github.com/FTBTeam/FTB-Sky-Adventures/issues/142

**Comment by CometicRush** [comment]
Oh, ok. I think this is a duplicated issue. Thank you!
