### ISSUE TITLE
End Cake to Nowhere

### ISSUE THREAD

**Issue by fasttrak48** [FTBTeam/FTB-Sky-Adventures#174]
* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**:

**Comment by fasttrak48** [comment]
Not sure why it dumped my outline but..
 Modpack ver. 1.2.1
Issue: Crafting the end cake and placing in the world does not actually end up teleporting you to the end. I tried manual crafting in a crafting table, using the trans table to reproduce the cake and also placing the cake on numerous surfaces does not seem to fix the problem.

**Comment by iKurama** [comment]
https://github.com/FTBTeam/FTB-Sky-Adventures/issues/115 - It's a cake.

**Comment by fasttrak48** [comment]
And one that in this modpack, can't be eaten.

I wasn't sure if a more standard end portal was available in this mod-pack and it is not, no evil tear available and you need a chorus fruit to build an end rod. It may be just a cake but it is required if you plan on getting the dragon egg, heart and breath with out hacking them into the game.

**Comment by ChylerBH** [comment]
@fasttrak48 Try being hungry and using it - this has caught me out before out and has been listed here too.

**Comment by fasttrak48** [comment]
Ahh, never considered hunger for this mod and actually being low on it to eat. I will try and post back. Thank you.


Thanks, ChylerBH, that is what the trouble was, hunger with the gem armour keeps saturation pegged. Take off armour run in circles eat the cake ;-P
