### ISSUE TITLE
Chicken Duplication

### ISSUE THREAD

**Issue by BloodedWine** [FTBTeam/FTB-Sky-Adventures#175]
* **Modpack Version**: 1.2.1 

* **Issue**: Roost Chicken Catcher can duplicate chickens 

* **Link to Log or Crash File Paste**:NA 

* **Is it Repeatable?**: Yes, If you have a keyboard/mouse/autohotkey macro that sends the 'use' button very quickly you can dupe chickens. It happens in single player and on a server. 
https://github.com/timrwood/roost/issues/23 

* **Mod/s Affected**: Roost

* **Known Fix**: Make a delay between chicken catcher use, like ender pearls

**Comment by BlitzAce71** [comment]
the duped chickens disappear after interacting with them when it happens to me. I use shift+click to move them from the breeder to inventory, and when doing that you'll see one of the two breeder slots retain the chickens and send them. you can then grab them again and it looks like a dupe, but when you try to pick up the duped chickens they'll disappear. you might be seeing a different behavior, but that's how it works for us on Roost 1.12-1.3.0
