### ISSUE TITLE
botania flower

### ISSUE THREAD

**Issue by ZKlack** [FTBTeam/FTB-Sky-Adventures#176]
* **Modpack Version**: 1.2.1
* **Issue**: when I placed endoflame with a diamond builder wand it was missing the texture and when I broke it, it dropped botania flowers
* **Link to Log or Crash File Paste**: didn't crash
* **Is it Repeatable?**: yes
* **Mod/s Affected**: Botania (r1.10-356)
* **Known Fix**: I don't know

**Comment by tfox83** [comment]
Do not use builders wands on entities.
