### ISSUE TITLE
Solid experience from chickens + auto placer from actually additions

### ISSUE THREAD

**Issue by fakegamingnerd** [FTBTeam/FTB-Sky-Adventures#177]
-->

* **Modpack-version 1.2.1 I think or the version where loot bag openers were reintroduced.

The issue is that when the autoplacer tries to place solid experience from chickens, the xp drops at spawn.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by tfox83** [comment]
fixed in dev
