### ISSUE TITLE
Can't craft Draconic chest

### ISSUE THREAD

**Issue by knoteye** [FTBTeam/FTB-Sky-Adventures#178]
Modpack Version 1.2.1

Issue; Can't craft Draconic Chest, tested with all tiers of injectors, triple checked recipe. Can craft other items with fusion crafting.
 
Mods affected, Draconic Evolution

**Comment by twsx** [comment]
At what exact step does it fail for you?

Note: I can craft it just fine in 1.2.1

**Comment by Redstymp** [comment]
Is your fusion crafting on the required level? What is your setup?

**Comment by knoteye** [comment]
I totally derped and missed a furnace. Someone ban me from the forums lol. Thanks for responding.

**Comment by knoteye** [comment]
Thanks for the assistance. ID10T error
