### ISSUE TITLE
Increasing memory allocated to the game causes crash

### ISSUE THREAD

**Issue by Kobting** [FTBTeam/FTB-Sky-Adventures#18]
* **Modpack Version**: 1.0.0

* **Issue**: Increasing memory allocated to the game causes ThaumCraft to cause a crash

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/d0f5ca15

* **Is it Repeatable?**: Every time I increase the memory allocated to the game it causes this crash. 
    - First install increased memory before starting game crashed. Uninstalled launched without increasing and game starts up. Close and increase again the game crashes.
Allocating 4GB have 16GB RAM total
* **Mod/s Affected**: ThaumCraft

I realize this could just be a specific problem to my computer.

**Comment by wyndman** [comment]
You are not alone in this. I've the exact same crash. Currently have 8 out of 16GB assigned to Minecraft.

**Comment by tfox83** [comment]
This is an issue with you not running the version of forge the pack is shipped with.

**Comment by Kobting** [comment]
Download from the twitch app had it at forge-14.23.5.2770 from the start. Might be a problem with how the twitch app deals with downloads though.
