### ISSUE TITLE
Infinite EXP Dupe??

### ISSUE THREAD

**Issue by dj-holy** [FTBTeam/FTB-Sky-Adventures#180]
Modpack Version:1.2.1

Well it looks like when using a formation Plane from AE2 in a subnetwork (exportbus to interface into Formation Plane) the Solid Experience from Chickens Mod can be dropped as EXP but it wont be used up. Which means there is Infinite EXp coming out of the formation Plane.

AE2 and Chickens/Roost

**Comment by tfox83** [comment]
fixed in dev
