### ISSUE TITLE
Cant use blazing pyrothium in TiC Smeltery

### ISSUE THREAD

**Issue by TheLexxxor** [FTBTeam/FTB-Sky-Adventures#182]
Modpack Version:1.2.1

Issue: 
I wanted to melt dark metal boots in the TiC Smeltery to get dark iron. What, according to JEI, needs a temperature of over 1400 °.
Everywhere in the internet is written that you can use blazing pyrothium. But my smeltery says the blazing pyrothium is not a fuel.

Mod/s Affected: Ender IO and tinkers construct

Known Fix: allowe blazing pyrothium as an fuel for the Smeltery

**Comment by tfox83** [comment]
It is current not supported due to cross mod issues.
