### ISSUE TITLE
Stuck at a 0% loading screen

### ISSUE THREAD

**Issue by nekrozofken** [FTBTeam/FTB-Sky-Adventures#183]
* **Modpack Version**:  FTBSkyAdventures-1.2.1-1.12.2.zip

* **Issue**: Stuck at 0% after attempting to open world

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/e18b941f

* **Is it Repeatable?**: Yes every time I try to open the Pack

* **Mod/s Affected**: Unknown

* **Known Fix**: NA

**Comment by tfox83** [comment]
Please try a fresh install
