### ISSUE TITLE
Infinite Fluids

### ISSUE THREAD

**Issue by Telvyr** [FTBTeam/FTB-Sky-Adventures#184]
Version: 1.2.1

Putting a Thermal Expansion Portable Tank with at least 2 buckets of liquid into a forestry bottler fills the internal tank of the bottler but does not remove liquid from the portable tank. The bottler then can be filled with cans to remove infinite fluid. as in my case infinite honey.

I have tested this bug with water, seed oil, honey and destabilised redstone. all of which behave as above

Mods involved: Thermal Expansion, Forestry

**Comment by Ravalli03** [comment]
This has been fixed in forestry_1.12.2-5.8.2.366

**Comment by tfox83** [comment]
Fixed in dev.
