### ISSUE TITLE
PortalAgent error makes modpack unplayable

### ISSUE THREAD

**Issue by Master-Jynx** [FTBTeam/FTB-Sky-Adventures#185]
* **Modpack Version**: 
1.2.2

* **Issue**: 
Im trying to play this modpack on an SMP server run on the Complex Gaming FTB network
They use 2 overworlds, 1 for Spawn and the other for the Player Islands, but are not able to 
get this modpack to work as intended.
 using the Create Team button to place a player on a team and reate their island fails.
https://github.com/SpongePowered/SpongeForge/issues/2266
That link referes to the teleport error returned, that was reported as a Sponge issue, but is an FTB issue.
Instead they use Sky Claims which has has commands for void island management they have to use instead.
When the delete or reset commands are used a new is created, but it is malformed and unplayable
https://prnt.sc/lbzq1p
Sometimes, using Exit Team will correct this, but not often.
I understand they are not using the modpack as intended, but until FTBU's teleport agent bug is fixed, this modpack is not playable in a ForgeSponge multi-world enviroment

 **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**: 
read the github link supplied and the related issue

**Comment by drakkensong21** [comment]
Its sponge what do you expect

**Comment by iKurama** [comment]
Sponge is not supported. Sponge changes how mods are working, resulting in not being able to reproduce them ourselves.

**Comment by Master-Jynx** [comment]
Please tell me that was a joke!?
I'm just a player on Complex Gaming's network.
And I told you how to recreate it.
Use Sky Claims, which has its own commands to create , delete, and reset islands.
It bypasses FTB's Team GUI.
and your mod uses FTB's Team GUI to do the same thing, plus it resets the Quests.
Using Sky Claims is causing some majors bugs in FTBS mods, that make the game 100% unplayable.
and yet they are trying to create fixes that will stabilize the setup, instead of using your recommended setup.
Why?
Because SpigotMC is garbage, compared to ForgeSponge.
ForgeSponge has the plugins they need to manage their servers, profile the environment, to find bugs and reduces lag.
It's more advanced, has more mods, plugins and even more mod authors supporting it, than SpigotMC has
SigotMC is server oriented, a Bukkit fork
ForgeSponge is a Forge FML coremod with Plugin Support

You're telling to switch to SpigotMC ,without the plugins they need, because you don't want to fix your teleport bug?

Just get the bug fixed, make sure that you are teleporting players to the correct Dimension !

**Comment by iKurama** [comment]
If one edits the modpack in the slightest or host it with anything other than the given "pack", it can't be supported. If something is wrong in Singleplayer and you haven't edited the pack, the bug can most likely be reproduced.

**Comment by tfox83** [comment]
Sorry I cannot support sponge.
