### ISSUE TITLE
Roost Mod Negative Progress On Chicken Breeding And Production

### ISSUE THREAD

**Issue by toxiblib** [FTBTeam/FTB-Sky-Adventures#186]
* **Modpack Version**: 1.2.1

* **Issue**: chickens place in roosts or breeders frequently create negative progress towards an item or breed

* **Is it Repeatable?**: happens on its own usually more often with higher tier chickens
![2018-11-05_10 50 05](https://user-images.githubusercontent.com/44771114/47993996-fad38200-e0e8-11e8-9c38-92544fb9a1c1.png)
![2018-11-05_10 52 26](https://user-images.githubusercontent.com/44771114/47993997-fad38200-e0e8-11e8-95cd-9d33714e8c86.png)

* **Mod/s Affected**: roost
 

EDIT: Appears to be a visual bug as it will tick down to a random negative number like -150.2% and the jumps up to 170% ish.
It continues going down to 100% and then works.

I cant tell if this is affecting the actual time it take to complete or not.
it may be worth adding something to WAILA to see its progress that way.

**Comment by iKurama** [comment]
https://github.com/FTBTeam/FTB-Sky-Adventures/issues/98

**Comment by Kratzwurst** [comment]
in Version 1.3.0 by roost will it be fixed, New Version is available

*The bug with high tier chickens reporting strange progress numbers in breeders has been fixed.

https://minecraft.curseforge.com/projects/roost/files/2635449

**Comment by tfox83** [comment]
Fixed in dev.
