### ISSUE TITLE
RF teleporter from the End causes severe world lag

### ISSUE THREAD

**Issue by 512Productions** [FTBTeam/FTB-Sky-Adventures#187]
* **Modpack Version**: 1.12.2

* **Issue**: Using the RF teleporter to return from the end causes world lag and prevents breaking signs or enemies from reacting properly as well as item usage glitches.

* **Link to Log or Crash File Paste**: No crash, just world stops updating like it should.

* **Is it Repeatable?**: Yes. No matter how I enter the End, teleporter or end cake, if I leave through the teleporter the issue returns. If I leave by the normal end portal, there is no issue, so it is not a matter of the end still loading chunks or processing something. 

* **Mod/s Affected**: RFTools interaction maybe?

* **Known Fix**: Leaving from the normal End portal after killing the dragon does not create this problem. You can still teleport in any way you want, but cannot use RFTools to leave the end even when using the handheld transmitter. Unsure if this is true for any other mod based teleporters.

**Comment by iKurama** [comment]
It goes for any minecraft version. When leaving a chunkloaded area and when loading new chunks (or chunks that aren't being loaded), it will cause lag.

**Comment by 512Productions** [comment]
> 
> 
> It goes for any minecraft version. When leaving a chunkloaded area and when loading new chunks (or chunks that aren't being loaded), it will cause lag.

Both ends are chunkloaded. The lag occurs when leaving the End with the teleporter, not when entering the End. The Overworld area is already loaded, has no new worldgen for any of the immediate area. Have been in the End for awhile, most of it is empty around the normal Dragon area. 

If I leave through the normal end portal, there is no lag of any kind. If I use the teleporter to leave, the world suffers large amounts of lag.

**Comment by tfox83** [comment]
This is a known issue with no fix at this time.  For now I suggest avoiding using the RF Teleporter until its fixed.
