### ISSUE TITLE
Advancement crash

### ISSUE THREAD

**Issue by WC9595** [FTBTeam/FTB-Sky-Adventures#189]
* **Modpack Version**: 1.2.1

* **Issue**: When I click on the advancement tab of Applied Energistics, the game stop respond and I need to restart the game.

* **Link to Log or Crash File Paste**: [https://paste.feed-the-beast.com/view/7160ad1b
](url)

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Applied Energistics

* **Known Fix**: Have not find one yet.

**Comment by DelfCo** [comment]
Dupe of #116 and #135
