### ISSUE TITLE
Breeder from Roost crashing on world loading

### ISSUE THREAD

**Issue by MiningPickaxe** [FTBTeam/FTB-Sky-Adventures#190]
* **Modpack Version**: 1.2.1

* **Issue**: Server crashes on startup, already tried removing one of the breeders, now it is the next one that is crashing.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/6bb90acb

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Roost

* **Known Fix**: Not found a fix yet

**Comment by iKurama** [comment]
In the config folder, open the forge file. "B:removeErroringTileEntities=false", try turn this to true, it usually works. (Do a backup just in case it screws up stuff :3)

**Comment by tfox83** [comment]
Fixed in next version.
