### ISSUE TITLE
Game crash when open it

### ISSUE THREAD

**Issue by alSahfer** [FTBTeam/FTB-Sky-Adventures#191]
Hello, my game's crash  when i intent open Minecraft, the problem is with the Sky Adventure modpack, i dont test other modpack.
This is the log in the console

https://paste.feed-the-beast.com/view/32ef7a3e

Sorry for my bad english, and thanks

**Comment by tfox83** [comment]
Please try a fresh install and check other packs.  I cannot reproduce this.
