### ISSUE TITLE
'Forge Mod Loader Missing Items' after updating

### ISSUE THREAD

**Issue by eddiebytes** [FTBTeam/FTB-Sky-Adventures#192]
* **Modpack Version**: 1.2.1

* **Issue**: When loading up my save after updating to 1.2.1, I got the 'Forge mod loader detected missing items' screen. It came up with 'base:wrench' and I don't want to load the world and potentially ruin my playthrough.

* **Link to Log or Crash File Paste**: 
![image](https://user-images.githubusercontent.com/38375277/48299733-309daf80-e4c9-11e8-911c-1a6c4a585a35.png)

* **Is it Repeatable?**: I quit and relaunched the pack but the problem still remains. As I said I just updated my world for 1.1.1 to 1.2.1.

* **Mod/s Affected**: I don't know what mod but it has something to do with base: ???

**Comment by tfox83** [comment]
That is intended, the mod removed the item.
