### ISSUE TITLE
Local Server not completing quest

### ISSUE THREAD

**Issue by bedoben** [FTBTeam/FTB-Sky-Adventures#193]
* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by bedoben** [comment]
Hi all,
I am playing version 1.2.1.
I setup an local server with, but quest in the beginning with 4 Oak wood isnt completing.
Then I setup an local server on the same PC but this also not completing.
Does anyone have the sam problem or know how to solve this.

**Comment by Sparkconater** [comment]
Modpack Version: 1.2.1

Issue: Local server hosted on Fadehost, can't click to complete quests. Items are in inventory

Link to Log or Crash File Paste: NA

Is it Repeatable?: Reloaded server and client - no change

Mod/s Affected:

Known Fix:

**Comment by Sparkconater** [comment]
In case you haven't solved this, I was able to fix this by joining a team.

**Comment by tfox83** [comment]
Correct, you must be on a team. Even if its your own team with you only in it.
