### ISSUE TITLE
Refine Storage Quest Needs Updated

### ISSUE THREAD

**Issue by ChosenArchitect** [FTBTeam/FTB-Sky-Adventures#194]
* **Modpack Version**: 1.2.1

* **Issue**: Refine Storage now has no use for the Cutting Tool and had moved to the Processor Binding now to make Processors.
* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Refine Storage, FTB Quests

* **Known Fix**:

**Comment by tfox83** [comment]
removed in dev.
