### ISSUE TITLE
Roost Collector

### ISSUE THREAD

**Issue by RobertLSnead** [FTBTeam/FTB-Sky-Adventures#197]
* **Modpack Version**: 
Modpack Version 1.2.1
* **Issue**: 
Unable to craft Roost Collector!
* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 
Yes, try to craft the Roost Collector.  Roost Chicken seems to be invalid!
* **Mod/s Affected**: 
Roost
* **Known Fix**: 
Fix recipe.

**Comment by twsx** [comment]
Can't reproduce; Works fine for me:

![.](https://i.imgur.com/RREnwIN.png)

**Comment by tfox83** [comment]
Same as twsx, no issues on my end either

**Comment by RobertLSnead** [comment]
Not sure what I'm doing wrong then?
I hatched a regular minecraft chicken and hit it with the chicken wand and it is telling me that it's missing the chicken.  If it worked for you, what was the process?

**Comment by RobertLSnead** [comment]
I've even tried with several types of roost chickens.

**Comment by RobertLSnead** [comment]
Also I noticed on the picture you have a auto craft system, try crafting in vanilla craft table or tinkers or even the craft stick!
