### ISSUE TITLE
Right Clicking Refined Storage 256k FLUID block crashes dedicated server in pack version 1.2.1

### ISSUE THREAD

**Issue by kreezxil** [FTBTeam/FTB-Sky-Adventures#198]
* **Modpack Version**: 
1.2.1

* **Issue**: 
Right clicking 256k fluid block from refined storage crashes dedicated server

* **Link to Log or Crash File Paste**: 
http://paste.ubuntu.com/p/45bnVDrg28/
http://paste.ubuntu.com/p/YZt6ZVjHvK/

* **Is it Repeatable?**: 
yes

* **Known Fix**:
Use 256k fluid disks instead!

Also posted at https://github.com/raoulvdberge/refinedstorage/issues/2082

**Comment by tfox83** [comment]
Fixed in latest
