### ISSUE TITLE
Roost 1.2.0 insane issue plz update to 1.3.0

### ISSUE THREAD

**Issue by Necrowo** [FTBTeam/FTB-Sky-Adventures#199]
FTB sky adventure 1.2.1

Percentage goes crazy in roost chicken breeders, roost any other roost's items
roost 1.2.0
Known fix : update to roost 1.3.0 the creator of the mod fixed it.
Thx :D

![unknown](https://user-images.githubusercontent.com/45075087/48567143-ab692f00-e8fc-11e8-8dc3-5bd4568bb498.png)

**Comment by tfox83** [comment]
Fixed in 1.3.0
