### ISSUE TITLE
FTB Sky Advetures crashes on loading

### ISSUE THREAD

**Issue by Ankido** [FTBTeam/FTB-Sky-Adventures#2]
* **Modpack Version**: 1.0.0

* **Issue**: Game crashes upon loading.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/b944bbbe

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Thaumcraft

* **Known Fix**: Not that I'm aware of.  Loaded game straight out of the box.  No optifine, no nothing just the modpack as it was downloaded from curse.

**Comment by aretzgaming** [comment]
I'm also getting the exact same error. I tried redownloading the server pack and uploading to my server again, still get the exact same crash report.

**Comment by luigigiannella** [comment]
Same here, don't know whether to remove it or wait for a fix, because I'm excited to play this pack

**Comment by tfox83** [comment]
You are not running the shipped version of forge.  Only the version that is shipped with the pack is supported
