### ISSUE TITLE
Undocumented downgraded mods from 1.2.1 to 1.3.0

### ISSUE THREAD

**Issue by LemADEC** [FTBTeam/FTB-Sky-Adventures#200]
* **Modpack Version**: 1.3.0

* **Issue**: IronChest, IndustrialCraft and ProjectE versions were downgraded compared to 1.2.1, yet the changelogs doesn't refer to those 3 mods.

* **Link to Log or Crash File Paste**: n/a

* **Is it Repeatable?**: yes

* **Mod/s Affected**: IronChest, IndustrialCraft and ProjectE

* **Known Fix**: update change logs or release hotfix?

**Comment by Possemaster** [comment]
I just upgraded my server to 1.3.0 and all seems fine. Only my Transmutation table does not accept any more items to store. Why is this? I can lean new items and take items out but I cannot put any more EMC back in.

**Comment by LemADEC** [comment]
This is one of the many side effects from downgrading mods in latest update.

**Comment by tfox83** [comment]
This was due to someone helping update packs, this was clearly not a good move on our part.  I have taken back over maintaining this pack and will assure mods arent downgraded without reason.  Look for 1.4.0 beta to release today.
