### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by avidgamer5918** [FTBTeam/FTB-Sky-Adventures#201]
* **Modpack Version**: 1.2.1
* **Issue**:just wondering but why is the mechanical user disabled?

* **Link to Log or Crash File Paste**: na
* **Is it Repeatable?**: na

* **Mod/s Affected**: extra utils 2

* **Known Fix**: na

**Comment by twsx** [comment]
Prevents automating sieves.
Maybe other reasons as well? Not sure.
