### ISSUE TITLE
No Way to get "Green"?

### ISSUE THREAD

**Issue by purloi** [FTBTeam/FTB-Sky-Adventures#202]
* **Modpack Version**: 1.2.1

* **Issue**: Can't get "Green Dye" or cactus / cactus green? 

3 of us have been playing for 4 days now. We can't seem to find a way to get green dye, cactus, green wool, etc. Did we miss something? This is needed before we can progress into many areas.

**Comment by twsx** [comment]
Options:
1. Sieve Dirt through String Meshes for a Cactus Seed (5% chance)
2. Slime with Botania's Alchemy Catalyst to get a Cactus
3. Environmental Tech's Botanic Miner gives you Cactus.
4. EnderIO's Organic Green Dye, as well as Botania's Floral Green Powder, both fulfill most purposes as well.

#1 is probably what you want. JEI doesn't make a link between ExNihilo seeds and what they actually plant. That disconnect is probably what made you not notice it. The others can be found through JEI.

**Comment by purloi** [comment]
Sure enough, I checked the Sieve and found cactus seeds. Thank you!
