### ISSUE TITLE
Thaumcraft Items not existing

### ISSUE THREAD

**Issue by rogunhqy** [FTBTeam/FTB-Sky-Adventures#203]
* **Modpack Version**: 1.2.1

* **Issue**: Cant do anything related to the thaumcraft mod without cheating the items in, theres no want so i cant get the thauminomicon, theres no crystals so i cant make the thaumometer.why have a bunch of quests related to items i cant get without cheating.

* **Link to Log or Crash File Paste**: Game doesnt crash

* **Is it Repeatable?**: Its not a bug that i activated

* **Mod/s Affected**: Thaumcraft

* **Known Fix**: Add the items needed or remove the quests

**Comment by twsx** [comment]
You can find plenty of the crystals in the Deep Dark.
A small amount of them can also be found on the obsidian pillars in The End.

The Wands don't exist in Thaumcraft 6, you start things off differently now, see https://ftb.gamepedia.com/Thaumcraft_6#Thaumonomicon

**Comment by rogunhqy** [comment]
But shouldn't they show up in the item list? Because they arent

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by james2kk** [comment]
it is easy to find at deep dark and the portal is cheap to craft

**Comment by SpraxDev** [comment]
You can also sieve netherrack to get crystals

**Comment by tfox83** [comment]
Sieving netherrack is the intended method.
