### ISSUE TITLE
ProjectE Ghost Items

### ISSUE THREAD

**Issue by WHowie** [FTBTeam/FTB-Sky-Adventures#205]
* **Modpack Version**: 1.2.1

* **Issue**: When placing certain items into the ProjectE Transmutation Table (Observed specifically for the Philosopher's Stone, Thermal Expansion Redstone Furnace (Basic), Steam Dynamo (Basic), and Chisel iChisel), a second copy of the item will appear in the table. If one copy of the item is forgotten, the other copy will remain visible and deduct EMC when clicked, but the item removed will immediately disappear. If the item is shift-clicked, it will be placed in the inventory, but when clicked, it will disappear. Restarting the game seems to make these ghost items disappear as well.

* **Link to Log or Crash File Paste**: No crash

* **Is it Repeatable?**: Yes

**Comment by AnttiMK** [comment]
Already reported to ProjectE (actually, been around for quite a while). See sinkillerj/ProjectE#1642.

**Comment by WHowie** [comment]
Good to know. Thanks

**Comment by tfox83** [comment]
Yes seems to be an issue with items that have meta values
