### ISSUE TITLE
Wireless Crafting Terminal - Java exception when trying to withdraw or deposit items.

### ISSUE THREAD

**Issue by XerShade** [FTBTeam/FTB-Sky-Adventures#207]
* **Modpack Version**: 1.3.0

* **Issue**: Players on my server were unable to use the Wireless Crafting Terminal for AE2, when I opened my server console I found it flooded with the error message attached.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/26adcfef

* **Is it Repeatable?**: Yes, made a completely new ME system, with a new wireless terminal, and all the parts, error still happened.

* **Mod/s Affected**: Wireless Crafting Terminal

* **Known Fix**: None, it's a code error.

**Comment by XerShade** [comment]
An update, someone on my server had this with the magnet, and it was preventing them from logging in. If anyone is unable to login to a server/world to need to delete the item from the player's inventory.

**Comment by dm8mydog** [comment]
this thread might be related: https://github.com/p455w0rd/WirelessCraftingTerminal/issues/295

**Comment by tfox83** [comment]
Fixed in 1.4.0
