### ISSUE TITLE
No mobs are spawning

### ISSUE THREAD

**Issue by Heumade** [FTBTeam/FTB-Sky-Adventures#208]
There are no Mobs spawning on my Island. I already checked the light Level and difficulty. I tried it in creative mode but no Mobs.....

**Comment by SakuraBliss** [comment]
same.

**Comment by dj-holy** [comment]
is it big enough? spawnrange around 16 blocks. or maybe a mega torch is placed?

**Comment by tfox83** [comment]
Mobs do spawn, give a large enough area and stand away.
