### ISSUE TITLE
Quests

### ISSUE THREAD

**Issue by ghost** [FTBTeam/FTB-Sky-Adventures#209]
* **Modpack Version**: 1.2.1

* **Issue**: None of the quests let me turn in the items even when i have them in my inventory/ hot bar.
I might just be stupid and not doing it right but when i click to turn the items in they dont work even when i have the specific items.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: All of the quests dont let me turn them in i have no idea why and im pretty sure its not a specific mod affecting them.

* **Known Fix**:

**Comment by tfox83** [comment]
Fixed in 1.4.0
