### ISSUE TITLE
End steel Ingot no emc value

### ISSUE THREAD

**Issue by Bentenmaru** [FTBTeam/FTB-Sky-Adventures#21]
* **Modpack Version**: FTBSkyAdventures-1.0.0

* **Issue**: End Steel Ingot doesnt have a emc value even though all ingredient has it but when you check it in JEI it use the various chisel version of end stone for recipe

* **Known Fix**: possible fix is that it has the right end stone to recieve emc from

**Comment by tfox83** [comment]
fixed in dev
