### ISSUE TITLE
EMC Limit?

### ISSUE THREAD

**Issue by dj-holy** [FTBTeam/FTB-Sky-Adventures#214]
Version 1.3.0

Not sure how much this is a BUg but since the Project-E has no update and the Update log doesnt have Info about a change. 
The EMC limit is reduced now to 2.147.483.647 

Maybe corrupted Long file?

**Comment by avidgamer5918** [comment]
ya its weird i am having the same issue

**Comment by gabnerd69** [comment]
Seems like the version of projecte the back was using which was 1.3.1B from 07/01/18 which has no limit on emc got rolled back somehow to 1.3.0 from 4/30/18 where there is a limit idk if it was intentional or a mistake  they changed the who way emc is stored in 1.3.1b and above

**Comment by tfox83** [comment]
This has been fixed in 1.4.0
