### ISSUE TITLE
Sky Adventures JEI exceptions

### ISSUE THREAD

**Issue by Nyquila** [FTBTeam/FTB-Sky-Adventures#215]
* **Modpack Version**: Sky Adventures 1.3.0
* **Issue**: It crashes every time I try and start the Game. This is a fresh install thru Twitch 
Says it Caught a exception from Just enough Items
* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/8f8d629b

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Just Enough items

* **Known Fix**: Unknown

**Comment by LilJ0NES** [comment]
i have same problem

**Comment by justclover** [comment]
As do I

**Comment by Kasyu** [comment]
I also have this problem, after looking through the crash report I noticed that it said that it ran out of memory at that point. So maybe increasing the memory allocation would work? However, I have no idea how I would do that. Edit: just remove the GC overhead limit.

**Comment by Themonkey180** [comment]
@Kasyu How do you remove the GC overhead limit?

> just remove the GC overhead limit.

**Comment by tfox83** [comment]
This has been fixed in 1.4.0, but make sure you are allocating at LEAST 4GB of RAM to java.
