### ISSUE TITLE
Metal Quests

### ISSUE THREAD

**Issue by voxpop9** [FTBTeam/FTB-Sky-Adventures#216]
* **Modpack Version**: 1.3.0

* **Issue**: Metal Quests like the Tin Quest does not accept other ore dictionary tin i.e. it only accepts Thermal Foundation Tin and not IndustrialCraft 2 Tin.

* **Is it Repeatable?**: Yes

**Comment by PlacidK** [comment]
Workarround -> throw in tinkers smeltery and cast an ingot.

**Comment by tfox83** [comment]
It is intended to only accept TF Tin at this time.  As PlacidK said you can melt down the tin from loot bags to produce the intended tin output from your machines/smeltery
