### ISSUE TITLE
Sky Adventures Quest Reward Duplication 

### ISSUE THREAD

**Issue by FakeBobbyHill** [FTBTeam/FTB-Sky-Adventures#217]
* **Modpack Version**: Sky Adventures V 1.3.0

* **Issue**: I had made a draconium ingot and was handing it in for my quest. For the first time since i started my playthrough, instead of manually collecting each reward I clicked on the money bag in the top corner. Instead of giving me $10 and a loot crate, it gave me a duplicate of every reward for every quest I had already completed and claimed. I ended up with over $500, seeds tools, a new wallet, and about 30 various loot crates. As I don't think this game breaking event was meant to happen I put everything into an iron chest and immediately reported it... in the wrong place, and was directed here. I'm sorry I don't have a log or whatever, or know the first thing about getting you one. Especially one from yesterday. My bad man. I wonder if it's because of the update? I did have to go into foamfix and turn off animated textures again.

* **Link to Log or Crash File Paste**: Sorry, I'm new to PCs and I don't know how to get that. I know it's very important.

* **Is it Repeatable?**: Unsure, I would assume you'd have to complete a few quests, claim them and then click the loot bag in the quest book. 

* **Mod/s Affected**:  

* **Known Fix**:

**Comment by tfox83** [comment]
This has been fixed in 1.4.0
