### ISSUE TITLE
Transmutation Table/Tablet Not Taking Items After Latest Mod Update

### ISSUE THREAD

**Issue by alio314** [FTBTeam/FTB-Sky-Adventures#218]
* **Modpack Version**: 1.3.0

* **Issue**: Not able to put items into transmutation table/tablet

* **Link to Log or Crash File Paste**: not crashing

* **Is it Repeatable?**: click on transmutation table/tablet, move item from inventory to EMC fire slot, item not going in

* **Mod/s Affected**: Projecte

* **Known Fix**:

**Comment by Helwyr** [comment]
Hi, I see that if you have too much EMC (~2,147,483,647) it becomes impossible to add items in the transmutation table.
(1.3.0)

**Comment by lowlightmc** [comment]
I have experienced this problem too, previously i could have like 3+ billions of EMC but now i can only take items out. I would realy like that problem to be fixed. And i think many others will too, because before it gets fixed i would have like 9999+ chests of EMC'able item i've been producing with my chickens.

**Comment by silasporth** [comment]
Since the last Update, a maximum amout of EMC was added.

**Comment by gabnerd69** [comment]
seems like the most recent version of projecte not the version the pack is using changed the way emc is calculated from an intager to longs making it possible for the number to become over 2.1 billion
in this last patch they seem to have somehow rolled back to the 4/30/18 release of project e where there is a limit as apposed to the 7/01/18 version that the pack was running which had no limit

**Comment by Draxhax** [comment]
Best part is that the changelog didn't even mention a version change to ProjectE. The change of the mod from 1.3.1B to 1.3.0 isn't documented nor is there an explanation of why it was downgraded.

**Comment by tfox83** [comment]
This has been fixed in 1.4.0
