### ISSUE TITLE
When shift inserting stack of speed upgrades into a transfer node, crash.

### ISSUE THREAD

**Issue by subnitrates** [FTBTeam/FTB-Sky-Adventures#219]
* **Modpack Version**: 1.3.0 

* **Issue**: When attempting to put a stack of speed upgrades into a transfer node that already contains a stack of speed upgrades, the game crashes.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/cb89a360 

* **Is it Repeatable?**: Yes 

* **Mod/s Affected**:  optional; if any mods are causing the direct issue please provide the name/version of the mod

* **Known Fix**: optional; if you know of a fix please let me know! Thanks

**Comment by Ozzymud** [comment]
While I do not get a crash, my client freezes, also freezes when I tried to shift click more pressure plates into the resonator. Both result in windows giving me the `program not responding` box and the only means of exiting is to close java. Nothing appears in the log, it stops at the same time as the shift-clicking freezes the game.

**Comment by VoidSentient** [comment]
I get the same issue. This is a mod issue though. Affected mod is Extra Utilities 2. This has happened on other instances also. I recommend reporting to the developer.

**Comment by tfox83** [comment]
This issue has been a bug for a long time and on the devs tracker.  I suggest inserting items in small quantities in ExU inv.
