### ISSUE TITLE
Wallet crashes game

### ISSUE THREAD

**Issue by LynxieVice** [FTBTeam/FTB-Sky-Adventures#22]
* **Modpack Version**: 1.0.0

* **Issue**: Minecraft crashes when you have the wallet open and your try to replace the wallet with another item via hotkeys

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/4ee392d3

* **Is it Repeatable?**: yes (even started a new game to check)

* **Mod/s Affected**: Good Ol' Currency Mod

* **Known Fix**: unknown

**Comment by Beardlessbrady** [comment]
Hey, this was fixed in the 1.3.6 version of the mod! An update should do the trick.

**Comment by tfox83** [comment]
fixed in next update, thanks
