### ISSUE TITLE
Missing Crafting Recipe of Energy Cells

### ISSUE THREAD

**Issue by Navios9009** [FTBTeam/FTB-Sky-Adventures#220]
* **Modpack Version**: 1.3.0

* **Issue**: The Energy Cells form Thermal Foundations do not have a crafting recipe except that of the first one.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Thermal Foundations

**Comment by abobunny** [comment]
You have to craft the base energy cell then use Thermals upgrade kits on them to upgrade capacity and send/receive speed.
