### ISSUE TITLE
Can's summit items for quests

### ISSUE THREAD

**Issue by TheSixthCrow** [FTBTeam/FTB-Sky-Adventures#222]
* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by comical-uk** [comment]
Hi, have you made a team?

**Comment by TheSixthCrow** [comment]
> Hi, have you made a team?

Yes I made a team and I also claimed the chunks around the island.

**Comment by tfox83** [comment]
I am not able to reproduce, please try a fresh install.
