### ISSUE TITLE
Craft Duplication

### ISSUE THREAD

**Issue by zerati** [FTBTeam/FTB-Sky-Adventures#223]
* **Modpack Version**: 1.3.0

* **Issue**: Craft Duplication

* **Link to Log or Crash File Paste**: NA

* **Is it Repeatable?**: Yes, i'll explain it step by step : (need to have at least 2 accounts)
-1rst: 1 player put the craft on the tinker's crafting Station
-2nd: the 2nd player enter the crafting station
-3rd: one of the 2 player remove every ingredients 
by doing this the player who remove the crafting ingredients have the ingredients but the second player
can see the craft result and take it.

* **Mod/s Affected**: Tinker's construct

* **Known Fix**: Don't Know

**Comment by Gepett0** [comment]
This even works with $$$ unfortunately. Kinda gamebreaking.

**Comment by tfox83** [comment]
Sorry I cannot support hacks via multiple accounts.
