### ISSUE TITLE
Inscriber presses no recipe?

### ISSUE THREAD

**Issue by Suntonk** [FTBTeam/FTB-Sky-Adventures#224]
* **Modpack Version**:1.3.0 

* **Issue**: how does one get an inscriber press when there are no meteorites, and no recipe that doesn't requre the press it

* **Link to Log or Crash File Paste**: no log

* **Is it Repeatable?**: yes just click on JEI recipes for presses

* **Mod/s Affected**: Applied energistics  2

* **Known Fix**:

**Comment by PlacidK** [comment]
Find the painted trapdoor ;)

**Comment by tfox83** [comment]
They are in a chest on the island.
