### ISSUE TITLE
Crash when attempting to fill craft using JEI in Crafting Grid - Magical Snow Globe

### ISSUE THREAD

**Issue by subnitrates** [FTBTeam/FTB-Sky-Adventures#225]
* **Modpack Version**: 1.3.0

* **Issue**: When attempting to fill in the crafting grid (refined storage) utilizing JEI with a "Magical Snow Globe" recipe, game crashes and shows the following error code.

"Connection Lost - Internal Exception: java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes"

This does NOT happen when auto filling with JEI other recipes.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/1e337c9c

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by JW-IT** [comment]
i have the same problem, but didn't open a new issue (only commented on a closed one)

following i link other issues/comments for reference
  * https://github.com/FTBTeam/FTB-Sky-Adventures/issues/58#issue-372164127
  * https://github.com/FTBTeam/FTB-Sky-Adventures/issues/160
  * https://github.com/FTBTeam/FTB-Sky-Adventures/issues/79

to add to my earlier post, i have 8+Gigs of ram allocated for java

**Comment by tfox83** [comment]
THis is fixed in 1.4.0 of the pack.
