### ISSUE TITLE
Crashed while loading for first time

### ISSUE THREAD

**Issue by Gamersen** [FTBTeam/FTB-Sky-Adventures#226]
* **Modpack Version**: 1.3.0

* **Issue**: Crashed while loading the game for the first time

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/def18851

* **Is it Repeatable?**: If this means, does it happen more than once, then yes.

**Comment by tfox83** [comment]
Please assign at least 4GB of RAM to JAVA for this pack
