### ISSUE TITLE
Chicken Analyzer quest

### ISSUE THREAD

**Issue by Bpaz187** [FTBTeam/FTB-Sky-Adventures#227]
Sky Adventures version 1.3.0 (launched through Twitch app)

When trying to claim the quest for the Chicken Analyzer it will only show 0% even with an entire inventory full of the correct item. This causes an entire tab on the quest book to be rendered useless.

**Comment by Bpaz187** [comment]
update: logged in after work and quest was randomly completed. Tried relogging prior and did not work. I will just take this as a win.

**Comment by Bass2style** [comment]
this questline is also broken here. tryed to log-off and on again, relaunching the pack, etc, the quest won't unlock. :/

**Comment by tfox83** [comment]
This appears to be fixed in 1.4.0 of the pack
