### ISSUE TITLE
Upgrading roost to 1.3.0 make breeders with chickens in it disappeared (with workaround)

### ISSUE THREAD

**Issue by progheal** [FTBTeam/FTB-Sky-Adventures#228]
* **Modpack Version**: 1.3.0

* **Issue**: 
The update of roost to 1.3.0 make chicken breeders with chickens in it prior to update disappeared. Empty breeders stays.
This is already a known issue in roost: timrwood/roost#46
Because empty breeders do not disappear, a workaround will be taking all chickens out of breeders before upgrading.
Therefore this is both a heads up to everyone (including the mod author) and also provides a workaround.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Roost

* Additional Note: Since many suggested roost 1.3.0 fixed many bugs (including the negative progress breeder bug, although I haven't encountered yet), I think working around that is better than downgrade.

**Comment by tfox83** [comment]
We are aware of the issues and need to upgrade to fix the outstanding issues.  Hopefully this issue has been resolved with the latest pack update releasing today.
