### ISSUE TITLE
Crash on game launch, texture stitching failure

### ISSUE THREAD

**Issue by ghost** [FTBTeam/FTB-Sky-Adventures#229]
* **Modpack Version**: 1.3.0

* **Issue**: Trying to launch the game fails at the texture stitching stage when it attempts to stitch the textures for blood magic. 

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/6119c1dc
* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Blood magic? 

* **Known Fix**:

**Comment by tfox83** [comment]
Unable to reproduce, please try a fresh install or wait for 1.4.0 to release later today
