### ISSUE TITLE
Can't submit item on Repeatable Quests

### ISSUE THREAD

**Issue by ghost** [FTBTeam/FTB-Sky-Adventures#232]
* **Modpack Version**: 1.3.0

* **Issue**: I can't submit the items for the Repeatable Quests, I tried with XP Reinforced Large Drum and the Witchwater Iron Drum, but no success. Both drums are full for sure, I even tried to craft a new one and do the same thing, but again no success

* **Is it Repeatable?**: Yes

**Comment by ghost** [comment]
So, I kinda fixed the problem.

* **Known Fix**: I used the editing mode from FTB Quests: "/ftbquests editing_mode", right-clicked on Witchwater quest -> "Complete Instantly", claimed the reward, after that the quest works as it should be, now I can submit the drums and repeat.

* **Is it Repeatable?**:  If you right-click on the Repeatble Quest page and "Reset Progress", the bug comes back and you can't submit the items again.

**Comment by tfox83** [comment]
Fixed in latest version
