### ISSUE TITLE
[BUG] Black Hole Tanks change liquid metadata (assuming)

### ISSUE THREAD

**Issue by BonaireDreams** [FTBTeam/FTB-Sky-Adventures#234]
* **Modpack Version**:  1.3.0

* **Issue**: Black Hole Tanks change liquid metadata (assuming)
Had an ender IO conduit going from Coke oven to an Iron Barrel for creosote. Was able to pull creosote out of barrel with a bucket and use in recipe to make treated wood. Swapped it out with a Black hole tank for extra space. Pulled a bucket of creosote out of the BH tank and was unable to craft treated wood. I was also unable to click that bucket back into the Barrel, but it did go back in the BH tank. Then tried piping the creosote from the barrel to the tank, and tank to barrel, neither worked.  
Another player on the server noticed the same thing with mob essence going into a BH tank. He was unable to put that bucket of essence into any machine (fluid transposer etc). If he first clicked the fluid onto the ground, and then picked it back up into the bucket it works.

* **Link to Log or Crash File Paste**: No Crash

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: 

* **Known Fix**: None

**Comment by tfox83** [comment]
Hmm thats a strange one, Ill get that over to the IF dev to see if he can take a look, thanks.

**Comment by tfox83** [comment]
Ok looks like this was fixed in latest version of IF.  That will be released in 1.4.0 update of the pack later today.
