### ISSUE TITLE
I'm fall in void... lost Akashic book, how get back

### ISSUE THREAD

**Issue by AskariCassetete** [FTBTeam/FTB-Sky-Adventures#235]
* **Modpack Version**: 1.3.0

* **Issue**: I'm fall in void... lost Akashic book, how get back (tomb doesn't appair)

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Akashic

* **Known Fix**: create a command to give the book with good config (the /give via gamemode 1 it's not good; no book in book).

**Comment by Bass2style** [comment]
it appairs also empty, but the tome it craftable with a book and a bookshelf, craft seems shapeless. (but you need a bit of advancement in the game to get another.), but i think there is a bug with the abillity to find the books/manuals.

you can also restore your inventory with /ob_inventory restore <player> <the wanted tomb with a -death at the end> (the other inventory should also work, but idk what the difference between the two.)

**Comment by AskariCassetete** [comment]
Where I can see "xxx-death"  ? I have only "D" or "last death"

**Comment by AskariCassetete** [comment]
I go in creative mod (open lan, etc...)

**Comment by tfox83** [comment]
You will need to get it out of your tombstone or run the command to recover your lost items from death.
