### ISSUE TITLE
Mac Server install issues with some FTB packs

### ISSUE THREAD

**Issue by Grimjahk** [FTBTeam/FTB-Sky-Adventures#236]
* **Modpack Version**:

FTB Pack Server install Batch file

* **Issue**: 

I run my server on a MacPro that has more than enough RAM and has no issues running once launched, but the files that are often provided with the server set seem to be bugged. I usually have to do a work around or three to get the server started. About 50% of the servers I have tried to set up went smoothly, 30% were successful after tweaking the files, and 20% I was never able to launch.

Sky Adventures was one of the 30% where I was able to get the server running, but not with the intended (included) method.

* **Is it Repeatable?**: 

Yes, the problem seems to stem from the source .sh file

**Comment by tfox83** [comment]
Sorry but I have no way to test mac servers.  I can try to pass this along, but I do know our server scripts are developed for Linux/Windows servers only.

**Comment by Grimjahk** [comment]
I’m happy to do test installs if that will help, I just don’t know enough to fix the code.
