### ISSUE TITLE
Ticking Particles

### ISSUE THREAD

**Issue by LiXDL** [FTBTeam/FTB-Sky-Adventures#237]
* **Modpack Version**: 1.3.0

* **Issue**: IC2 Mass Fabricator exploded and killed me in game, then the game stalled and crashed. 

* **Link to Log or Crash File Paste**: I keep getting 522 error when accessing FTB paste website, therefore I think I can only attach the crash report. Sorry for the inconvenience. 
[crash-2018-12-19_14.20.35-client.txt](https://github.com/FTBTeam/FTB-Sky-Adventures/files/2696729/crash-2018-12-19_14.20.35-client.txt)

* **Is it Repeatable?**: Yes; the game keeps crashing if I try to enter the world. 

* **Mod/s Affected**: Industrial Craft 2, 2.8.73-ex112, according to "installed mod".

* **Known Fix**:

**Comment by LiXDL** [comment]
Adding known fix:
The problem is actually caused by rain particle. I used NBTexplorer to stop the rain, and it worked. 
More specifically, the entry that is modified is under level.dat, Data, raining. The entry value was originally 1, setting it to 0 will fix the problem.

**Comment by tfox83** [comment]
I will report this to the dev, also the pastebin site has been restored.  Thanks

**Comment by 016Nojr** [comment]
Works for me, pack version 1.5
