### ISSUE TITLE
Loot crates have no loot table

### ISSUE THREAD

**Issue by Angelus022695** [FTBTeam/FTB-Sky-Adventures#238]
* **Modpack Version**: 1.3.0 -->

* **Issue**:  Loot crates have no loot table according to a message in chat. They also dont open

* **Link to Log or Crash File Paste**: no crash resulted

* **Is it Repeatable?**: yes I've tried several instances of the world and they all say the same thing

* **Mod/s Affected**: not sure

* **Known Fix**:

**Comment by tfox83** [comment]
If you dont unlock the pack and update mods on their own this wouldnt be an issue.  In the unmodified version of 1.3.0 this is not an issue.  In 1.4.0 the loot system has been overhauled to work with the newer loot tables.
