### ISSUE TITLE
Can't Turn In Diamond Chest Transporter 

### ISSUE THREAD

**Issue by ttechr** [FTBTeam/FTB-Sky-Adventures#24]
**Modpack Version**:
Version 1.0.0

**Issue**:
Can not turn in the Diamond Chest Transporter for that quest. I do not think it is detecting it correctly. 

![2018-10-18_11 44 47](https://user-images.githubusercontent.com/1749896/47167276-14dd2a00-d2cc-11e8-86fc-29536bba5da4.png)
![2018-10-18_11 45 01](https://user-images.githubusercontent.com/1749896/47167277-14dd2a00-d2cc-11e8-88fd-4fa19e725fb2.png)

**Comment by ttechr** [comment]
Just found out that when I pulled one out of the Transmutation Table that one worked, but not the one that was made from scratch.

**Comment by tfox83** [comment]
Yea was an issue with damage values, I set them to ignore during turn in.

**Comment by twsx** [comment]
@tfox83 Just in case this was only fixed for that specific quest: Environmental Tech quests suffer from the same problem
