### ISSUE TITLE
AE 2 inscriber presses.

### ISSUE THREAD

**Issue by Bpaz187** [FTBTeam/FTB-Sky-Adventures#240]
* **Modpack Version*- 1.3.0 (through twitch app

* **Issue**: <!-- Early Game oops.

* **Mod/s Affected**: <!--AE2

Okay. So early game... I guess the easiest way to put it i fell and died with the presses in my inventory. Mistakes were made and the void claimed them forever. 

Fast forward much time later. Restarting wouldn't be an option. Is there NO alternative way to get these in sky adventures other than the hidden chest in the start? 
Please advise

**Comment by dm8mydog** [comment]
if you had them in your inventory, then they are in the gravestone ... go down there using water/jetpack/angel ring and pick them up.

**Comment by Bpaz187** [comment]
> if you had them in your inventory, then they are in the gravestone ... go down there using water/jetpack/angel ring and pick them up.

Yeah... That happened really early game. When i dropped down my water column right as I broke the gravestone (for some reason it had no block under it, only pack I ever played where that was the case) a squid came down and i fell out of the bottom of the water and watched my items falling after me. 
What I'm trying to figure out is if there is a late game way to get these presses as starting over wouldn't be an option now. I can't use Applied storage at all now I'm guessing and should just move on to the next pack?

**Comment by tfox83** [comment]
At this time there is only the way to get them from the beginning, we have no plans to change that.
