### ISSUE TITLE
How to turn off death markers?

### ISSUE THREAD

**Issue by TechnicProblem** [FTBTeam/FTB-Sky-Adventures#241]
* **Modpack Version**: 
1.3.0
* **Issue**: 
I get death markers consisting of white D's on a transparent grey background. I can't seem to find an option to turn them off. I have a lot of them in my base and I want to get rid of them. Does anybody know which mod is doing this?

* **Is it Repeatable?**: 
Happens every time I log in.
* **Mod/s Affected**: 
I don't know which mod is causing this issue.
* **Known Fix**: 
I don't know a fix for this.

I'm sorry if this is the wrong place to submit this.

**Comment by tfox83** [comment]
The mini map adds them, just open the mini map options and clear them.
