### ISSUE TITLE
Crashing with Gendustry

### ISSUE THREAD

**Issue by niclukman** [FTBTeam/FTB-Sky-Adventures#242]
* **Modpack Version**: 1.3.0

* **Issue**: Minecraft crashes on startup due to Gendustry

* **Link to Log or Crash File Paste**: https://pastebin.com/N54fStmw

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Gendustry

* **Known Fix**: Nope

**Comment by tfox83** [comment]
Please try a fresh install.  This is not an issue for myself or any of my testers.
