### ISSUE TITLE
InventoryTweaks hide objects in hands

### ISSUE THREAD

**Issue by Lexon78** [FTBTeam/FTB-Sky-Adventures#243]
* **Modpack Version**: 
1.3.0

* **Issue**: 
If i place last item from my hands, then Inventroy Tweaks playe to this slots new items, but sometime are this object invisible - I must click to this slot with mouse and object have "texture"

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 
Yes

* **Mod/s Affected**: 
InventoryTweaks-1.63.jar
* **Known Fix**: 
click to this slot by mouse, or place this object on ground.

**Comment by tfox83** [comment]
I am not able to reproduce this issue, but you can try changing this to false in the InvTweaks.cfg file enableAutoRefill=true (line 7)
