### ISSUE TITLE
What chunkloading in this modpack on server? (FTB utilities are off and still chunkloading)

### ISSUE THREAD

**Issue by Lexon78** [FTBTeam/FTB-Sky-Adventures#244]
* **Modpack Version**: 
1.3.0

* **Issue**: 
Server build. If we disable chunkloading area in FTB Utilities, then something still chunkloading all ours islands. This persists server restart. My base is 2 days without chunkloading in FTB Utilities (only claimed area) and still my automated production runing. We don't know what block chunkloading. Anybody of us don't use other know chunkloader.

* **Is it Repeatable?**: 
Yes

* **Mod/s Affected**: 
FTBUtilities-5.3.0.53.jar ?

**Comment by Explosiontime202** [comment]
Maybe your machines are in the spawn chunks, they are loaded all time the server is running.

**Comment by Lexon78** [comment]
No. This problem have many islands in this modpack on our server.

**Comment by tfox83** [comment]
There are a few mods that force load things on servers to prevent crashes, some are Controllers from AE2, Flux Network blocks... to name a few.
