### ISSUE TITLE
Netherwart chicken

### ISSUE THREAD

**Issue by bentu578** [FTBTeam/FTB-Sky-Adventures#246]
On a server, when breeding 16 10,10, 10 Netherwart chickens and 16 10,10,10 Diamond chickens to get Ender Pearl chickens in the breeder, I sometimes get a 1,1,1 Neatherwart chicken.

* **Modpack Version**: 1.3.0

* **Issue**: When breeding 16 10,10, 10 Netherwart chickens and 16 10,10,10 Diamond chickens to get Ender Pearl chickens in the breeder, I sometimes get a 1,1,1 Netherwart chicken.

* **Link to Log or Crash File Paste**: none

* **Is it Repeatable?**: unknown. I changed the chickens(deleted them and got new), changed breeders, went back to original breeder, changed positions, and have not been able to duplicate. Tried for about an hour

* **Mod/s Affected**: roost-1.12-1.3.0

* **Known Fix**: change chickens?

**Comment by tfox83** [comment]
This should be fixed in 1.4.0

**Comment by bentu578** [comment]
Excellent, thank you
