### ISSUE TITLE
Help pls

### ISSUE THREAD

**Issue by RussianBoy123** [FTBTeam/FTB-Sky-Adventures#247]
When I want to create an ordinary world, I get emptiness, what to do?

**Comment by Lexon78** [comment]
Its only for Skyblock. Only default generating world will be OK.

**Comment by RussianBoy123** [comment]
I chose any type of world everywhere was empty except Skyblock

**Comment by tfox83** [comment]
Only skyblock worlds are supported and available in this pack.
