### ISSUE TITLE
Immersive Engineering conveyer belts from a transmutation table are unusable 

### ISSUE THREAD

**Issue by RJHaytree** [FTBTeam/FTB-Sky-Adventures#248]
* **Modpack Version**: 1.3.0

* **Issue**: When taking an Immersive Engineering conveyor belt out of a transmutation table, the conveyor belt is untextured and unusable. This has apparently been an issue on the previous version as well (according to those on my server).

* **Evidence**: https://puu.sh/CpaKz/3b0fffc972.mp4 (This video is in singleplayer)

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Immersive Engineering, ProjectE

**Comment by tfox83** [comment]
Removed EMC values from them as ProjectE doesnt support NBT data.
