### ISSUE TITLE
Thaumcraft crahes game on startup.

### ISSUE THREAD

**Issue by ImTwistedBro** [FTBTeam/FTB-Sky-Adventures#25]
* **Modpack Version**: 1.0.0

* **Issue**: The game crashed whilst there was a severe problem during mod loading that has caused the game to fail.
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thaumcraft (thaumcraft)

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/01f86d02

* **Is it Repeatable?**: Happens everytime i try booting up the game. Tried reinstalling to no effect.

* **Mod/s Affected**: Looks like Thaumcraft.

* **Known Fix**: None so far. Will update.

**Comment by tfox83** [comment]
Please use the forge version shipped with the pack.

**Comment by ImTwistedBro** [comment]
Which version is that then? I just installed and launched, didn't change anything.
