### ISSUE TITLE
I appear falling into the void all the time.

### ISSUE THREAD

**Issue by Dyffros** [FTBTeam/FTB-Sky-Adventures#252]
* **Modpack Version**: 

* **Issue**: I fall into the void when I enter a world that I have just generated. 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: Yes 

* **Mod/s Affected**: 

* **Known Fix**: 

When I create a world, when I generate it, I appear falling into the void.

**Comment by tfox83** [comment]
Please try a fresh install.  I am not able to reproduce this.
