### ISSUE TITLE
Akashic Tome 

### ISSUE THREAD

**Issue by Wrath6661** [FTBTeam/FTB-Sky-Adventures#253]
* **Modpack Version**: 1.3

* **Issue**: tome was a digital guide, and I swept it into the transmutation table and poof was gone.

* **Link to Log or Crash File Paste**: none as this wasn't a crash

* **Is it Repeatable?**: yes I made a new world and tested in creative 

* **Mod/s Affected**: 

* **Known Fix**: make the tome contain all available books upon crafting

**Comment by Dahu88** [comment]
I had the same issue with the 1.4.0 version of the modpack, I lost my Akashic Tome and cannot recreate one.

**Comment by cookta2012** [comment]
You can always make a new one....

**Comment by Dahu88** [comment]
There's a a recipe indeed, but when I craft it and use it, it's empty ... so useless

**Comment by 016Nojr** [comment]
EMC has been removed from the tome in the latest version
