### ISSUE TITLE
Crash when opening quantum storage unit

### ISSUE THREAD

**Issue by TheMingo888** [FTBTeam/FTB-Sky-Adventures#255]
* **Modpack Version**: 1.4.0

* **Issue**: When a quantum storage unit is right-clicked by any player, their client immediately crashes (the server does not crash, if the player is on a server). This happens regardless of what item has been put into the unit, if any.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/3a7a37f7

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Quantum Storage

* **Known Fix**: Unknown

**Comment by TheMingo888** [comment]
This appears to already have been fixed by the Quantum Storage devs: https://github.com/gigabit101/QuantumStorage/issues/184

**Comment by metaknight1992** [comment]
They know about it, but they haven't released a working fix yet. Also, that's my post!

**Comment by LeeCannonFodder** [comment]
This is making the pack or at least my base no longer playable for me, because I used mostly quantum storage unit to store Items.

**Comment by Dahu88** [comment]
The mod devs released a fix some times ago. Can it be updated in the modpack ?
