### ISSUE TITLE
**Issue** Too much entity on an island makes the server lag

### ISSUE THREAD

**Issue by BloodyFireXs** [FTBTeam/FTB-Sky-Adventures#256]
* **Modpack Version**: FTB SkyAdventures-1.4.0-1.12.2 ( CasualCraft - EU )

* **Issue**: too much entity

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: this is already two days that the server has trouble because of it

* **Mod/s Affected**: 

* **Known Fix**: remove all or remove half of their mob tower

**Comment by tfox83** [comment]
That is on the server owner to fix.  I cant control how players build things.
