### ISSUE TITLE
Quest Book consumable items

### ISSUE THREAD

**Issue by BasilChristofis** [FTBTeam/FTB-Sky-Adventures#258]
* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by BasilChristofis** [comment]
I just updated my game and found my quest book reset, and all the items mostly turned into consumables in their quests.

**Comment by RupsjeNG** [comment]
me to… hope this willl chage into detecting items...
