### ISSUE TITLE
Super Circut Maker Addition

### ISSUE THREAD

**Issue by attu21** [FTBTeam/FTB-Sky-Adventures#259]
I have noticed a lot of great machinery that can be automized quickly, but a lack of the mod super circuit maker which offers the best of both worlds in terms of compact circuits and infinite possibilities without having complicated recipes or just missing blocks such as a pulser which does not exist :

Modpack: FTB Sky Adventures 1.4.0

**Comment by drcrazy** [comment]
there is no super circuit maker for 1.12
