### ISSUE TITLE
 server level type

### ISSUE THREAD

**Issue by Rumple4life** [FTBTeam/FTB-Sky-Adventures#26]
* **Modpack Version**: 

* **Issue**: I'm not sure what level type to set the world to, I spawn into the void. 
after this happened I changed the level type to voidworld, deleted the world and still fall into the void no island.

**Comment by tfox83** [comment]
You must use the included world that is shipped with the server as this contains a spawn platform.

**Comment by Rumple4life** [comment]
Appreciate the help, I'm not sure why the world file didn't load the first time, I deleted the old world file again then uploaded the world file from the pack, works now, thanks!
