### ISSUE TITLE
Gravestone in The End unobtainable

### ISSUE THREAD

**Issue by Arsakios** [FTBTeam/FTB-Sky-Adventures#260]
* **Modpack Version**: 1.4.0

* **Issue**: When Dying in the End the Gravestone spawns deeply in the Void (around y= -200) making it unobtainable. 

* **Is it Repeatable?**: Died 3 Times getting my Items back. Even in Creative there is no chance to get back the items.

**Comment by Kasyu** [comment]
you can use absorption 30 and regen 10 in survival to fall down infinitely down into the void.

**Comment by Arsakios** [comment]
Does this work without Commands? How could i get this without Commands?

**Comment by Kasyu** [comment]
You can’t get to anywhere in the void without commands.

**Comment by Kasyu** [comment]
If you have commands disabled, you can enable them by opening to lan with allow cheats on.
