### ISSUE TITLE
Refined Storage controller crashes on updating to 1.4.0

### ISSUE THREAD

**Issue by dbulm2** [FTBTeam/FTB-Sky-Adventures#261]
* **Modpack Version**: 1.3.0 - 1.4.0

* **Issue**: Updating my server to 1.4.0, the server crashed due to a Refined Storage controller. I removed the controller, but replacing it causes the server crash again. 
Note: I added Refined Exchange to the pack when updating it, but it wasn't causing the crash.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/1f48fa8d on launch, https://paste.feed-the-beast.com/view/56d74dcd on placing the controller

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Refined storage.

**Comment by cookta2012** [comment]
I would suggest checking to make sure that you are using the correct Refined Exchange for the correct Refined Storage version. It could be a API issue.

**Comment by dbulm2** [comment]
Possibly, I've since deleted the server since we were basically finished with the pack anyway.
