### ISSUE TITLE
Crash after update.

### ISSUE THREAD

**Issue by twankledeez** [FTBTeam/FTB-Sky-Adventures#262]
* **1.4.0**

* **Crashes on startup**

* **https://paste.feed-the-beast.com/view/d93ba269**

* **Yes**

* **Mod/s Affected**: 

* **Known Fix**: 

Everything was working fine until I updated the pack through twitch last night. Since then It won't start up. I've tried "fixing Minecraft" in Twitch, deleting and reinstalling the pack, removing and reinstalling Java, pointing the launcher to the "real" version of Java, and of course restarting my computer. Nothing makes it work. Also, Stoneblock updated yesterday as well, and now it doesn't work either. It just runs Java in the background and never starts.

**Comment by Danymaddox** [comment]
Same problem here. Every time I try to start my profile it crashes instantly. This happens since the last update, no fix known. 
Lastest log: https://pastebin.com/7byasc4r

**Comment by cookta2012** [comment]
Remove OptiFine

**Comment by Danymaddox** [comment]
I'm not using optifine

**Comment by cookta2012** [comment]
Your Pastebin line 23
If you are having troubles with it loading I have an i3. I will paste the JVM args I use you may have to play with them to get them to work, but Optifine does break this pack.

![Capture](https://user-images.githubusercontent.com/1284410/54241299-6b067000-44ee-11e9-99fd-547c7b2c08e2.PNG)

Not the point. Here is what I use for

JVM ARGS: `-XX:InitiatingHeapOccupancyPercent=10 -XX:AllocatePrefetchStyle=1 -XX:+UseSuperWord -XX:+OptimizeFill -XX:LoopUnrollMin=4 -XX:LoopMaxUnroll=16 -XX:+UseLoopPredicate -XX:+RangeCheckElimination -XX:+CMSCleanOnEnter -XX:+EliminateLocks -XX:+DoEscapeAnalysis -XX:+TieredCompilation -XX:+UseCodeCacheFlushing -XX:+UseFastJNIAccessors -XX:+CMSScavengeBeforeRemark -XX:+ExplicitGCInvokesConcurrentAndUnloadsClasses -XX:+ScavengeBeforeFullGC -XX:+AlwaysPreTouch -XX:+UseFastAccessorMethods -XX:+UnlockExperimentalVMOptions -XX:G1HeapWastePercent=10 -XX:G1MaxNewSizePercent=10 -XX:G1HeapRegionSize=32M -XX:G1NewSizePercent=10 -XX:MaxGCPauseMillis=100 -XX:+OptimizeStringConcat -XX:+UseParNewGC -XX:+UseNUMA -XX:+UseCompressedOops -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:SurvivorRatio=2 -XX:+DisableExplicitGC`

Then set the render distance to like 6 or 8 chunks

![Image](https://ibin.co/4ZyskraRUtKC.png)
