### ISSUE TITLE
Quests have been reset

### ISSUE THREAD

**Issue by Batthew627** [FTBTeam/FTB-Sky-Adventures#263]
* **Modpack Version**: Latest Version* 
**Issue**: I had completed numerous quests in this pack but when i updated the pack all of my quests have been reset.

* **Link to Log or Crash File Paste**: n/a

* **Is it Repeatable?**: yes other people have also had the same issue

* **Mod/s Affected**: i assume FTB:Quests

* **Known Fix**:

**Comment by nathaniwasuik** [comment]
This has also affected me but it happened when I updated the server from 1.3 to 1.4. Tried to find what caused it but couldn't.

**Comment by LeeCannonFodder** [comment]
> This has also affected me but it happened when I updated the server from 1.3 to 1.4. Tried to find what caused it but couldn't.

Myself as well.  Also when I turned in two stacks of Solar panels the quest chimed and listed in the upper right corner for each panel for the next 15 minutes.  I have 52 stacks of witchwater barrels to also turn in.  That will be fun.  

Please can you make a way like shift or ctrl click to turn in a stack or all that is in player's inv with one click.

**Comment by mt1lee** [comment]
Got the same problem. Also is it just me or all the quests consume item after update?

**Comment by LeeCannonFodder** [comment]
All quest are reset (unfinished).

 

I put $1000 in my inv.  When I open the quest book and clicked the tab to sell items the quest to spend a $1000 to make money was done but the $1000 I put in my inv was still there (not taken).  I sold two stacks of solar panels and the I got the chime and the massage on the top right corner of the screen for quest completed for each item sold.  It took me about 2 minutes to sale the two stacks but took 15 for the chiming and massages to quit.

 

I will logon and check other quests to see if items are consume or not.

 

Sent: Saturday, January 19, 2019 at 9:43 PM

**Comment by AlleinSoldat** [comment]
In addition to the initial issue of all quests being reset, I have also experienced all items being consumed. Which also includes all of the high tier items like the Soularium Jetplate, which was not consumed before the update.

**Comment by LeeCannonFodder** [comment]
I did some testing some quest consume items some don't, most did.  The quest book does not say if it will or will not be consumed.  Some quest get completed when I place items in my inv.

**Comment by Kasyu** [comment]
> Got the same problem. Also is it just me or all the quests consume item after update?

that's actually a bug, the quest consuming/not consuming things have been inverted from what they were in 1.3, so the food ones dont consume items, but the ones like the crucible and sieve and such are consumed.

**Comment by 016Nojr** [comment]
Quests being reset is was most likely a mod related issue during an update.
