### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by StarZxz** [FTBTeam/FTB-Sky-Adventures#265]
## Modpack Version
1.4.0 
[https://www.feed-the-beast.com/projects/ftb-sky-adventures/files/2658207]
## Description
I also downloaded the server and the client and run it on the same computer. When the server runs successfully, I can use the client connection to enter the server game. My friends can also, but after a few minutes, my friends and I will automatically Disconnected from the server, the game told me that the connection was broken. Whenever this happens, there will always be a sentence in the background: "[Server thread/WARN] [net.minecraft.server.MinecraftServer]:Can't keep up! Did the system time change, or is the server overloaded? Running XXXXms behind, skipping XX tick(s)", but after waiting for a while, I can enter the server again, and then I will be removed from the server. The background pops up like this one. Is my computer memory overflowing? Still other questions? Please help me solve this problem! thank you very much!
## Computer configuration
System:Windows10 64x |
CPU:AMD Athlon X4 760K Quad Core 3.8GHz |
GPU:Nvidia GeForce GTX 1050 Ti |
Memory chips:4G DDR3 1600MHz + 8G DDR3 1600MHz |
SSD:120G （The server and client are stored）
## Game log
https://paste.feed-the-beast.com/view/2ed36076
## Client config
JAVA max RAM：6144MB  |
JAVA PARAMETERS：-Xmx6144m -Xms512m -XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
## Server config
rem Do not touch
set MCVER=1.12.2
set JARFILE=minecraft_server.%MCVER%.jar
set LAUNCHWRAPPERVERSION=1.12
set LAUNCHWRAPPER=net\minecraft\launchwrapper\%LAUNCHWRAPPERVERSION%\launchwrapper-%LAUNCHWRAPPERVERSION%.jar
set FORGEJAR=FTBserver-1.12.2-14.23.5.2796-universal.jar

rem can be changed by user
set MIN_RAM=512M
set MAX_RAM=5120M
set JAVA_PARAMETERS=-Xmx5120m -Xms512m -XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
## Java Version
jre1.8.0_201 64x
## Mods change
Add:[https://minecraft.curseforge.com/projects/i18nupdatemod/files/2623852]and[https://minecraft.curseforge.com/projects/just-enough-characters/files/2646589]
There is no delete，
after testing not to modify the results of the same
## other
I am a Chinese, so I may make many grammar mistakes, please forgive me, I will try my best to cooperate with you！

**Comment by StarZxz** [comment]
By the way, the added mod is the client mod, which is not put into the server MODS folder.

**Comment by SeraphJACK** [comment]
Normally, your Minecraft server will do _Game Tick_ 20 times in a second, in other words, each tick should take less than 50ms. When the server has done a tick and find out that it takes a lot more time than 50ms, it'll skip a few ticks and show you this warnings.

So generally, **it's your CPU overloaded, not the pack's issue**.

**Comment by SeraphJACK** [comment]
Possible Solution:
- ~~Purchase a better CPU~~
- Profile with _Lag Goggles_ (在mcbbs上就能找到，森林蝙蝠搬运的), and then find the lag tileentities and remove them.
