### ISSUE TITLE
No loot from loot crates

### ISSUE THREAD

**Issue by liampearson96** [FTBTeam/FTB-Sky-Adventures#266]
* **Modpack Version**: 1.4

* **Issue**: loot crates give no reward. After updating to 1.4 can no longer open loot crates. Upon trying to open them, it does the animation but no item appears, no reward is given. 

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/3ccffea1

* **Is it Repeatable?**: yes

* **Mod/s Affected**: ftb quests

* **Known Fix**: n/a

**Comment by 016Nojr** [comment]
Working for me on pack version 1.5.0
