### ISSUE TITLE
Every time I try to play it does this

### ISSUE THREAD

**Issue by lucaspwe** [FTBTeam/FTB-Sky-Adventures#268]
1.12 FTB Sky Adventures
Idk what this is

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)

It happens every time I load it up

Just enough items

**Comment by lucaspwe** [comment]
This happens on multiple FTB mod packs Idk why

**Comment by ghost** [comment]
assign more RAM in the Twitch launcher settings. You'll need at least 3GB, preferably 4.

**Comment by Kasyu** [comment]
> assign more RAM in the Twitch launcher settings. You'll need at least 3GB, preferably 4.

you actually need a minimum of 4GB, not 3,

**Comment by xGamerxGirlx** [comment]
So did allocating more ram help the problem?

**Comment by triffman33** [comment]
Only if you have enough, if you have 6GB then assign 4 but if you have less than that you probably won't be playing any of the bigger modpacks.
