### ISSUE TITLE
Missing libraries and eula.txt

### ISSUE THREAD

**Issue by Aquerr** [FTBTeam/FTB-Sky-Adventures#269]
* **Modpack Version**: 1.4.0

* **Issue**: Looks like **FTBInstall.bat** is not installing server correctly. After downloading server files i started **ServerStart.bat** and it stopped where it can't find **eula.txt** and then it prompts an error about libraries. Running script multiple times does not help.

When I run **FTBInstall.sh** and then **ServerStart.bat** then it is working. Looks like **FTBInstall.bat** is not downloading full **minecraft_server.1.12.2.jar** but **FTBInstall.sh** is doing it. 😱

Tested on **Windows**.

* **Link to Log or Crash File Paste**:
![image](https://user-images.githubusercontent.com/15029008/51860776-d29b9e00-233a-11e9-80e2-c6b5f7d5c1c9.png)

* **Is it Repeatable?**: Yeah. Download server files, run **ServerStart.bat**.

* **Mod/s Affected**: None.

* **Known Fix**: Running **FTBInstall.sh** seems to work.

**Comment by triffman33** [comment]
Did you set the eula to true after that?

**Comment by Aquerr** [comment]
Eula.txt has been generated after running FTBInstall.sh and so I was able to set it to true then. However it has not been generated while running FTBInstall.bat. (Probably because of the exception in the console that you can see on the screenshot). Don’t know if I am the only one who find this problem.
