### ISSUE TITLE
Inverted quest requirements

### ISSUE THREAD

**Issue by Kasyu** [FTBTeam/FTB-Sky-Adventures#271]
* **Modpack Version**: 1.4

* **Issue**: The quest log consumes items that aren't supposed to be consumed, and doesn't consume items that are supposed to be consumed

* **Repeatable**: yes

* **Mod Affected**: FTB Quests

If you could please fix this, that would be great. it really screws up progress

**Comment by Walendar** [comment]
I have fixed the quest-related file until a more permanent solution comes along. Replace the \FTB Sky Adventures\questpacks\normal.nbt with a file from attached archive.
[normal.zip](https://github.com/FTBTeam/FTB-Sky-Adventures/files/2835327/normal.zip)


EDIT: An issue with loot crates has arisen. Fixing it now.
EDIT2: Fixed. Here's the new file.
[normal.zip](https://github.com/FTBTeam/FTB-Sky-Adventures/files/2835377/normal.zip)
