### ISSUE TITLE
Quantum storage crashes my game!

### ISSUE THREAD

**Issue by Adrian112212** [FTBTeam/FTB-Sky-Adventures#272]
* **modpack version: 1.4.0
* **Issue**: When you open the quantum storage your game crashes.
* **Is it Repeatable?**: I tried to put some stuff into the quantum storage and then my game crashed, i tried it twise
* **Known Fix** : Delete the modpack from Sky Adventures!

Tnx if you fix it!

**Comment by ainz666** [comment]
https://github.com/FTBTeam/FTB-Sky-Adventures/issues/255
