### ISSUE TITLE
Crash when loading at launch

### ISSUE THREAD

**Issue by robotalec** [FTBTeam/FTB-Sky-Adventures#273]
* **Modpack Version**: 1.4.0

* **Issue**: Crash when loading the just enough items recipes half way done

* **Link to Log or Crash File Paste**:
 The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)
* **Is it Repeatable?**: Unknown
* **Mod/s Affected**: Just Enough Items

* **Known Fix**:

**Comment by xGamerxGirlx** [comment]
I have the same problem, have you found a fix besides just removing that mod and the other ones relative to it?

**Comment by Linc7991** [comment]
What does the next line say? If it says `Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded`, you ran out of memory. Increase your memory allocation to Minecraft if you have it.

**Comment by 016Nojr** [comment]
^^
