### ISSUE TITLE
Game crashes while initializing

### ISSUE THREAD

**Issue by MrWolfington** [FTBTeam/FTB-Sky-Adventures#274]
* **Modpack Version**: 1.4.0

* **Issue**: The game crashes while initializing. Game crashed twice and on third attempt seems to have fixed itself, posting this anyway just as a notification to the developers.

* **Link to Log or Crash File Paste**: The game crashed whilst initializing game
The game crashed whilst initializing game
Error: net.minecraft.client.renderer.StitcherException: Unable to fit: bloodmagic:models/alchemytable - size: 256x256 - Maybe try a lowerresolution resourcepack?
* **Is it Repeatable?**: Yes, happened twice in a row. Tried it a third time and it seems to have fixed itself.

* **Mod/s Affected**: BloodMagic

* **Known Fix**:

**Comment by Linc7991** [comment]
The error is saying the texture is too large for your graphics card (If you have one).
