### ISSUE TITLE
Server unable to start

### ISSUE THREAD

**Issue by andrewackerman** [FTBTeam/FTB-Sky-Adventures#276]
* **Modpack Version**: 1.4.0 (Tried with previous versions, same issue)

* **Issue**: Every time I try to start a new server using the [downloaded server files](https://www.feed-the-beast.com/projects/ftb-sky-adventures/files/2658211), it reaches a point where it says there are 2 missing registries and asks if I want to proceed. If I say yes, the server then warns me that there are 57 missing entries. Saying yes to this takes the server to the point where I would think it's up and running, but I cannot connect to it. I have verified that I am able to start and connect to a vanilla server, so I don't think it's any firewall or router settings.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/15138acf

* **Is it Repeatable?**: It happens every time I try to start a new server

* **Mod/s Affected**: N/A

* **Known Fix**: None

**Comment by andrewackerman** [comment]
Tried again today, got to the same point. If I try to connect to the server, Minecraft gets to the "Logging in..." phase, but then eventually times out while the server makes no indication that I tried to log in at all. On the second attempt, The server briefly popped up with the message that I connected, but then crashes with the following log:

https://paste.feed-the-beast.com/view/a167b426

This is a machine that I have been able to successfully host a vanilla forge server as well as a SevTech server.

**Comment by andrewackerman** [comment]
I was able to get the server to launch by increasing the RAM and PERMGEN values in the bat files.

**Comment by triffman33** [comment]
Yeah you have the max ram set to 2gb in that crash report which is no where near enough. If you're hosting locally you can connect to it via typing "localhost" into the ip bar instead of an ip but if not i'm not really any good at the ip forwarding stuff.

**Comment by andrewackerman** [comment]
I Increased the RAM from 2GB to 8GB. The thing is, 2GB was the default in the batch files that came with the server files in the download. It's a bit troubling that the default RAM allocation is nowhere near enough for what the server actually needs.
