### ISSUE TITLE
GAME CRASHES ON STARTUP! WHILE LOADING MODS

### ISSUE THREAD

**Issue by mugzzey** [FTBTeam/FTB-Sky-Adventures#277]
* **Modpack Version**: 1.4.0

* **Issue**: game crashes on startup

* **Link to Log or Crash File Paste**: The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)

* **Is it Repeatable?**: it happens every time I can't load it I've tried 5 times now

**Comment by triffman33** [comment]
Any log? Also you need at least 4GB assigned to mc to run semi successfully but if you have any less than 6GB on your machine you probably won't be able to play any bigger packs.

**Comment by mugzzey** [comment]
ahh gotcha How to you assign more ram

**Comment by Linc7991** [comment]
On the Twitch client, Go to Settings -> Minecraft. Then there's a slider that will have memory allocation.

**Comment by Games-Crack** [comment]
you must have installed java X64 than you can assign more ram (memory).
