### ISSUE TITLE
Server unable to start

### ISSUE THREAD

**Issue by ADeer78** [FTBTeam/FTB-Sky-Adventures#278]
* **Modpack Version**: 1.4.0

* **Issue**: Every time I start the server it fails to start.  Same issue as https://github.com/FTBTeam/FTB-Sky-Adventures/issues/276  Says there are 2 missing registries and asks if I want to proceed. If I say yes, the server then warns me that there are 57 missing entries

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/c90ec92e

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: unknown

* **Known Fix**: Allocate more ram.

I have adjusted set MAX_RAM=4096M under settings.bat, no change. Went up to MAX_RAM=6144M  and it still only uses 1.5Gb. there are no other memory options in this file. I have tried adding set MIN_RAM=2056M set MAX_RAM=5120M set PERMGEN_SIZE=1024M and it will allocate more ram but it still give the same error. 

My settings.bat https://paste.feed-the-beast.com/view/537ea264

**Comment by 016Nojr** [comment]
Please provide new logs as they are outdated now if I need to look at it, there's also a new pack version.
