### ISSUE TITLE
game chrash

### ISSUE THREAD

**Issue by MrSmiley22** [FTBTeam/FTB-Sky-Adventures#280]
* **Modpack Version**: <FTB Sky Adventures>

* **Issue**: <game chrashes when loading>

* **Link to Log or Crash File Paste**: <https://paste.feed-the-beast.com/view/f7f07b7e>

* **Is it Repeatable?**: <yes>

**Comment by Linc7991** [comment]
Ran out of memory. Dedicated more memory to Minecraft in the Twitch launcher settings.

**Comment by Games-Crack** [comment]
its stuck at Just Enough Items (jei) you can try to remove it!
it maybe gets running again
