### ISSUE TITLE
Some books are uncraftable, with any enchanter or loot bag drops

### ISSUE THREAD

**Issue by Solverbolt** [FTBTeam/FTB-Sky-Adventures#283]
* **Modpack Version**: 
Sky Adventures 1.4.0
* **Issue**: 
Enchanter is not showing all recipes for all books, Also, Sieve Fortune Book never drops, even from loot bags, not sure if that was intended, but as terrasteel is not that easy to get, until a player can manage to make it, they are stuck. 
* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 
Just go into JEI or the Enchanter, a large number of books that i know were encoded a long while ago with Sieve | Ex Nihilo are missing
* **Mod/s Affected**: 

* **Known Fix**:

**Comment by 016Nojr** [comment]
Most likely intentional
