### ISSUE TITLE
Some blocks being replaced by other blocks/things

### ISSUE THREAD

**Issue by Someone12543** [FTBTeam/FTB-Sky-Adventures#284]
The Modpack Version is 1.4.0 as of posting this

Ok... so it's been a while since I've played this modpack (3-4 months), and some updates have been made while I was gone. I'm not sure if the updates were the cause, but before I joined my world, is asked me if I wanted to back up the save file. I said "If it's asking me this, there something must be wrong"

The moment I joined my world... I saw everything... Everything was different.
All my multiblock structures (smeltery and exp tanks) had been... transformed?... into (what I think to be) random blocks...

The thing is... the structures still work as intended, but I can't interact with their interface (except for the smeltery, which stopped working completely), for example: the chickens still produce their designed resources, and the ender I/O conduits and chests still work perfectly... Except that they're not even conduits or chests anymore... They turned into some kind of obelisk and lantern...

I have NO CLUE how this bizarre event happened... But I can just go in creative mode and fix the issue. Of course it's gonna take some time, but to get back my world, it's worth it.
I'm not sure if this issue can be fixed, or maybe if it was just me, but it's still an issue, which is why im posting it here.

If I can remember, I'm gonna list the items that got replaced and what they got replaced by (followed by the screenshots of course)

1
![screen shot 2019-02-23 at 1 03 16 pm](https://user-images.githubusercontent.com/47923692/53289381-39fb1100-3774-11e9-8076-5dca03c842e3.png)
All my roosts turned into "Item barrel connectors" but still worked just fine

2
![screen shot 2019-02-23 at 1 00 01 pm](https://user-images.githubusercontent.com/47923692/53289379-39627a80-3774-11e9-92d9-449ba9da4e13.png)
My energy condensers turned into "Feral flame lanterns" and my ender I/O conduits turned into "Inhibitor Obelisks" but, again, still worked just fine

3
![screen shot 2019-02-23 at 1 01 09 pm](https://user-images.githubusercontent.com/47923692/53289380-39627a80-3774-11e9-931e-3fc4a9549ae2.png)
My smeltery became... whatever the hell this is...

4
![screen shot 2019-02-23 at 12 55 40 pm](https://user-images.githubusercontent.com/47923692/53289386-3a93a780-3774-11e9-89f9-2bdc2dd9e8ed.png)
And, as you can see, it's floor completely disappeared

5
![screen shot 2019-02-23 at 12 54 32 pm](https://user-images.githubusercontent.com/47923692/53289383-39fb1100-3774-11e9-8205-a3ef030654ea.png)
My (coming soon) Tier 8 Draconic Core, which only had the Draconium Blocks built to it, turned into... uh... these. The stabilizers turned into strongboxes, and are now 3x3 -1 in the middle

6
![screen shot 2019-02-23 at 12 56 43 pm](https://user-images.githubusercontent.com/47923692/53289387-3a93a780-3774-11e9-859c-f040b134221b.png)
This set of stairs was supposed to be my tinker area. And that one block... I completely forgot

7
![screen shot 2019-02-23 at 12 57 18 pm](https://user-images.githubusercontent.com/47923692/53289388-3a93a780-3774-11e9-8708-93e318dcb2f2.png)
These missing textures were once my (Patient) Loot Bag openers, with the conduits revolving to recycle the bag. It was also how I unlocked the Nether Star in my Transmutation Table (good times)

8
![screen shot 2019-02-23 at 12 57 54 pm](https://user-images.githubusercontent.com/47923692/53289390-3a93a780-3774-11e9-8f31-e6e1ee480157.png)
These were my exp tanks, once full of experience (hence why I'm not even lvl 1 as of posting these screenshots). They're still full of exp... but I cannot insert or extract any of it

9
![screen shot 2019-02-23 at 12 58 25 pm](https://user-images.githubusercontent.com/47923692/53289391-3b2c3e00-3774-11e9-8e52-532f1a364082.png)
These are my chicken breeders, still working as great as ever (or as fast as a Tier 4 chicken can breed), but apparently is now an "Antibarrel"

10
![screen shot 2019-02-23 at 12 58 48 pm](https://user-images.githubusercontent.com/47923692/53289392-3b2c3e00-3774-11e9-8614-6f41b34e3197.png)
This was supposed to be my Transmutation Table... Now I can store items in it... yay

11
![screen shot 2019-02-23 at 12 59 19 pm](https://user-images.githubusercontent.com/47923692/53289393-3b2c3e00-3774-11e9-964e-f71f3d4e489b.png)
So.. for some reason, these roosts that contained a lot of emerald chickens (for EMC farming) completely disappeared...

12
![screen shot 2019-02-23 at 12 59 53 pm](https://user-images.githubusercontent.com/47923692/53289394-3b2c3e00-3774-11e9-8dea-7c3651908cbb.png)
And the game still thinks it's there... as you can see by the shadows...

I also forgot to screenshot the borders of the island, which were "Dirt Brick fences" (that are in the starting island), and now are "Cyan something something..."

This whole thing is gonna take some time to clean up... But hey, at least im gonna get some extra EMC for all these items (that contain EMC).

Please let me know if this ever happened to you, or if you can relate with this in any way... Cuz this really hit me hard, making me panic immediately when I joined. I wanna make it clear that I enjoy the pack, and that this is only a minor obstacle that won't make me stop playing

**Comment by 016Nojr** [comment]
Most likely a very rare bug we almost never see happening, roll back to a previous backup, and play from there
