### ISSUE TITLE
Expensive items are consumed.

### ISSUE THREAD

**Issue by James1524** [FTBTeam/FTB-Sky-Adventures#286]
* **Modpack Version**: Lastest Version

* **Issue**: all expensive items are consumed.

* **Is it Repeatable?**: more than likely, others have been having the same issue

* **Mod/s Affected**: affects all the mods

* **Known Fix**: Haven't found a fix

![bugged](https://user-images.githubusercontent.com/48171302/53772009-b17a2000-3e99-11e9-8837-b9349027fb1f.png)

**Comment by 016Nojr** [comment]
I cant say for sure, but it's most likely intentional, the last chapter is def working as intended.
