### ISSUE TITLE
Server wont start

### ISSUE THREAD

**Issue by Darkwiiyou** [FTBTeam/FTB-Sky-Adventures#287]
* **Modpack Version**:  1.4.0

* **Issue**: Server stops seconds after start

* **Link to Log or Crash File Paste**: https://pastebin.com/cSeF7mX0

* **Is it Repeatable?**: Yes.

* **Mod/s Affected**: Null

* **Known Fix**: Delete old mod files.

Edit: I went into the mod folder and realized I have the old mods along side the new mods.

**Comment by Darkwiiyou** [comment]
Resloved. I had duplicates of each mod due to in improper update on my end.

**Comment by cookta2012** [comment]
Please close the issue.
