### ISSUE TITLE
No Starting multiplayer islland

### ISSUE THREAD

**Issue by TkMacg** [FTBTeam/FTB-Sky-Adventures#289]
* **Modpack Version**: 1.12.2

* **Issue**: i am using apex hosting to make a multiplayer server for this mod pack but the starting island does not appear and i just fall into the void and die
description

**Comment by pierrekilly** [comment]
Same here with an Aternos server. Have you found a solution?

**Comment by Impacnyy** [comment]
Same. I am using Aternos server too and there is no starting island.

**Comment by Impacnyy** [comment]
Found the solution!!! Do: go to inventroy on the left corner there is "my team" click on it and set a team and you get TPed to the island instanly
