### ISSUE TITLE
FTB Sky Adventures locks up when Shift-Left Clicking items into Extra Utilities 2 input slots

### ISSUE THREAD

**Issue by ZippityDoodah** [FTBTeam/FTB-Sky-Adventures#290]
FTB Sky Adventures 1.4.0 1.12.2

When Shift-Left Clicking items from the character inventory into some Extra Utilities 2 devices, it causes Minecraft to lock up. Resulting in having to the end the task (Windows 10), and then reload the pack. This happens in both Single Player and Multiplayer. The most recent occurrence for me was when I attempt to Shift-Left Click a stack of Polished Stone into a Resonator (Extra Utilities 2) device, while some Polished Stone already existed in the input slot. This seems to only occur if some items already exist in the input slot. If the input slot is empty, then Shift-Left Clicking items into the empty input slot works fine.

No Crash Report, that I'm aware of, since the game required ending the task, with no actual Crash (with a proper exit) of the client.

It is repeatable in both Single Player and Multi Player modes. Regardless if Creative mode or Survival mode.

Extra Utilities 2 1.12-1.9.8

Not savvy enough with Java and Forge to determine a fix or cause. The only workaround is to avoid Shift-Left Clicking any items from my inventory directly into a Extra Utilities device when items already exist in the input slots of the GUI for that device. Which takes getting used to, since Shift-Left clicking is a mainstay function to move stacks into the input of most Minecraft devices, from ones inventory, for ease of filling the input of that device.

**Comment by cookta2012** [comment]
First I assume you are using the Twitch launcher so here we go.
copy the following

%homepath%\Documents\Curse\Minecraft\Instances

Press (Windows Button) + R ( or just open a run prompt)
Paste the copied text "%homepath%\Documents\Curse\Minecraft\Instances"
Open the folder of the Sky Adventures that you are using
Open a folder called "logs"

Now online find a paste website. (I like hastebin.com)

Open the "latest.log" and copy and paste it online and please provide the link.
I will try to help. 😃 

Edit: 

I just did this and it happened to me too. https://hastebin.com/ukiyozuhaw.md

**Comment by cookta2012** [comment]
I just did this and it happened to me too. https://hastebin.com/ukiyozuhaw.md

**Comment by cookta2012** [comment]
It looks like it is a rendering issue mabey because the server is still running.

**Comment by ZippityDoodah** [comment]
It doesn't cause the Server to crash, that I'm aware of, when playing Multiplayer. It causes the client itself to freeze up. I just went ahead and tested it again, this time in Single Player. If say there is a stack of 25 items in the Input Slot of the EU2 device and I place just a small amount using Shift-Left Click but not enough to bring it to the max stack size of 64, it works fine. But if I attempt to Shift-Left Click more then is needed to bring the stack to full size, then the client freezes up. So I think it was to do with stack sizes in these EU2 devices. All other devices just bring the stack size to full and the remaining stays in your inventory. It seems as though Extra Utilities 2 devices don't like having you Shift-Left Click items into the input slot that might bring the stack size over the standard 64. So it causes the game to freeze.


I attempted to copy/paste the information you wanted into both the hastebin.com site as well as pastebin.com websites, but the size exceeds the allowed limits without paying for membership on those sites. Can you suggest another? I can try cutting off the beginning section of the data to try and cut it down to a more reasonable size if that would still give you the information you desire?

**Comment by ZippityDoodah** [comment]
[latest.log](https://github.com/FTBTeam/FTB-Sky-Adventures/files/2962889/latest.log)

**Comment by ZippityDoodah** [comment]
Update - The same thing occurs when trying the Shift-Left Click any Upgrades into the Extra Utilities 2 devices. If the amount you Shift-Left Click would exceed the maximum number of upgrades the device can handle (such as Shift-Left Clicking 4 max Speed Upgrades when the device already has a few in it already) then it freezes up the client as well, requiring you to end the task.

**Comment by cookta2012** [comment]
That's the same thing that occurred with me when I attempted to do it.
