### ISSUE TITLE
Impossible to connect to Servers

### ISSUE THREAD

**Issue by Bernasss12** [FTBTeam/FTB-Sky-Adventures#296]
* **Modpack Version**: 1.4.0

* **Issue**: Unable to connect to servers

* **Link to Log or Crash File Paste**: Not applicable

* **Is it Repeatable?**: Yes, I haven't been able to connect to any server yet.

Every time I try to connect to any server the Minecraft client freezes and starts not responding until it comes back with the message that it failed to connect because the connection timed out. The game unfortunately doesn't crash and so I don't have a log to read/share as I lack the knowledge to debug a problem without any logs.
I am pretty sure this is a problem with this specific modpack because I've been playing FTB Ultimate Reloaded on a private server without a problem and even though sometimes the game gets non-responsive it almost never crashes.

Thanks for your time in advance

**Comment by 016Nojr** [comment]
We're able to connect to servers, and have been for beta testing, so unless logs are provided we cant fix it.
