### ISSUE TITLE
Impossible to get a Chorus Flower?

### ISSUE THREAD

**Issue by willurd** [FTBTeam/FTB-Sky-Adventures#298]
* **Modpack Version**: 1.4.0

* **Issue**: I'm currently working on the Compound Bow quest. The only thing I need for it is Chorus Flowers, but there doesn't seem to be any way to get the first one:

  * You can get them from the Void Botanic Miner, but the tier 1 structure requires Chorus Flowers to make.
  * You can get them from farming, obviously, either manually or automatically with Forestry (as JEI reports) or any other farming mod, but you need Chorus Flower #1 for that.
  * You can get them from Botania by throwing a Popped Chorus Fruit into a mana pool, but I can't find a way to get the first Popped Chorus Fruit or Chorus Fruit.
  * I tried the Extra Utilities 2 Quantum Quarry with a "The End" biome marker, but its theoretical "The End" biome appears to be a void biome with no chorus plants.
  * I found a [German Youtuber who got his first Chorus Flower from sifting crushed endstone through a string mesh](https://www.youtube.com/watch?v=uVA0ly1I25s&feature=youtu.be&t=1106), but this seems to be disabled in the current version. It's both not in JEI and not possible to sift crushed endstone through string (I tried it. I also tried sifting a bunch of crushed endstone through diamond, but all I got was draconium dust as JEI says).
  * I went to some end cities but didn't find any chorus plants in chests.
  * There's no Chorus Flower that you can buy in the Reward Store.
  * There's no quest that gives Chorus Flowers.

It looks like maybe the only way to get them is to make $20,000 and buy the Tome of Knowledge and EMC them in, but that feels like a bug to me, not intentional design.

I suppose it could be possible to get them from loot boxes, but I can't imagine something that is required to complete a quest would be gated behind loot box RNG.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: N/A

* **Known Fix**: Maybe Chorus Flowers were removed from the string mesh loot table by accident?

**Comment by 016Nojr** [comment]
Recipe is there in pack version 1.5.0
