### ISSUE TITLE
Modpack crashes whenever it is loading Just Enough Items recipes

### ISSUE THREAD

**Issue by FridayTheDog** [FTBTeam/FTB-Sky-Adventures#299]
* **Modpack Version**: 1.4.0
* **Issue**: Whenever the modpack loader is loading"Memory Used / Total /2869 MB  TOP BAR, Loading - Finishing up  6/7 TOP MIDDLE BAR, LoadComplete - Just Enough Items 19/197 BOTTOM MIDDLE BAR , Loading Recipes -  150472/23022 BOTTOM BAR". It seems to crash and  go to the Minecraft Launcher.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/66ccb894

* **Is it Repeatable?**: If you mean say the issue again yes, demonstrating it I have to find a way to record it.

* **Mod/s Affected**: I'm pretty sure it is Just Enough Items seeming as the mod loader seems to crash on this mod when it is loading the recipes.

* **Known Fix**: Sorry I don't know a solution to this problem.

**Comment by TheRealAzzA** [comment]
From the crash report, it seems to be that you are running out of memory. I think you have more memory allocated to Minecraft than your PC actually has to allocate but I could be wrong. In the launcher (I'm guessing you're using the new one) go to "installations" then to "FTB Sky Adventures", click on it and then click "more options" at the bottom and under "JVM Arguments" look for "-Xmx" and change the number after it to "2048" then save it and try to launch the game
