### ISSUE TITLE
The multiplayer map distributed with 1.0 is not in sync with the modpack.

### ISSUE THREAD

**Issue by ProsperCraft** [FTBTeam/FTB-Sky-Adventures#3]
* **Modpack Version**: 
1.0.0
* **Issue**: 

When you load the modpack for the first time forge complains about items it needs to remove from the map.

* **Link to Log or Crash File Paste**: 
https://gist.github.com/ProsperCraft/338cadc77b9ca5f2109455dc57a8ae21

* **Known Fix**: 
Run once with your 1.0.0 modpack and re-upload.

**Comment by tfox83** [comment]
Its due to a structure file and even in the latest version it throws that FML confirm.
