### ISSUE TITLE
Game keeps having freeze frames

### ISSUE THREAD

**Issue by aapjeG** [FTBTeam/FTB-Sky-Adventures#30]
* **Modpack Version**: Version 1.0.0 (Minecraft version 1.12.2)

* **Issue**: My game keeps having freeze frames almost every 5 seconds and it keeps on going, it happens after a little while when I started a game (singleplayer or multiplayer).

* **Is it Repeatable?**: Yes, every time when I launch the game it happens

**Comment by ProsperCraft** [comment]
This happens when you don't allocate enough ram to the pack, give it more ram like 8-10 gigs and you will no longer have this issue.  Provided your computer has enough ram.

**Comment by TheFlash787** [comment]
Please note that I wouldn't even recommend 8-10GB even if you had 16GB available. That is just unnecessary and silly. I can run the mod-pack with below 3GB perfectly fine. If allocating more RAM didn't fix it, perhaps give Optifine a go. 👍

**Comment by ProsperCraft** [comment]
Note if you add optifine it invalidates all of your crash reports if you want to help submit them and get bugs fixed.

**Comment by tfox83** [comment]
I suggest 4-6GB of RAM without a texture pack.  I am not able to look into this anymore with a profile report of maybe a log.  Feel free to reopen if you have this issue again with that amount of ram allocated and can provide more details.  Thanks
