### ISSUE TITLE
Stone Barrel

### ISSUE THREAD

**Issue by Mordanae** [FTBTeam/FTB-Sky-Adventures#303]
The game will not recognize my stone barrel and crucible.  I have them in my inventory but does not seem to recognize them so I can't continue the quests in the game.

**Comment by nilPadisha** [comment]
Click the quest manually and hit "Autocomplete quest".
If that doesn't fix it, for the crucible you need an **unfired** crucible.

**Comment by 016Nojr** [comment]
Works for me in pack version 1.5.0
