### ISSUE TITLE
Unable to favorite items

### ISSUE THREAD

**Issue by Dexy2811** [FTBTeam/FTB-Sky-Adventures#304]
* **Modpack Version**: 1.4.0

* **Issue**: When trying to favorite an item in JEI by pressing A its not letting me

* **Link to Log or Crash File Paste**: don't have any logs or crash files to paste

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Only JEI as far as i know 

* **Known Fix**: Update JEI Mod

**Comment by nilPadisha** [comment]
Try opening Mod Settings and finding JEI Mod.
You should be able to set your keybind for JEI Mod to set favorites.
