### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by FlameOregu** [FTBTeam/FTB-Sky-Adventures#306]
After I download the file, I don't know where to put it. If i put it in versions, it doesn't appear. I don't know how to use it since it's such small of a file and I thought it might be something like a version since when I go into it's mod folder that it has, it only has around 2. Where am I supposed to put this file? If you know how to resolve this issue, please contact me. Thanks.

**Comment by nilPadisha** [comment]
Hey, this github is just a placeholder for issue tracking.
If you want to play FTB Sky Adventures, you can download the FTB launcher on their official website.
After opening the launcher select Sky Adventures in the mod pack list & launch.

https://www.feed-the-beast.com/
