### ISSUE TITLE
Can't launch the modpack. Get console error.

### ISSUE THREAD

**Issue by Onfimarist** [FTBTeam/FTB-Sky-Adventures#308]
* **Modpack Version**: 1.4.0

* **Issue**: Whenever I click on the launch button to launch the modpack, it starts launching but then gets an error in the console without minecraft being launched.

* **Link to Log or Crash File Paste**: https://sourceb.in/ddf0d9c3e7

* **Is it Repeatable?**: Yes I can

* **Mod/s Affected**: N/A

* **Known Fix**: N/A

**Comment by 016Nojr** [comment]
Try reinstalling the pack
