### ISSUE TITLE
Server issues

### ISSUE THREAD

**Issue by Salio24** [FTBTeam/FTB-Sky-Adventures#309]
* **Modpack Version**: FTBSkyAdventures Server 1.4.0

* **Issue**: Server report many red errors

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/7435f88f

* **Is it Repeatable?**:  Yes

* **Mod/s Affected**: N/A

* **Known Fix**: N/A

**Comment by 016Nojr** [comment]
If you're still playing, try update the pack.
