### ISSUE TITLE
Ender Generator taking more items than visible

### ISSUE THREAD

**Issue by MarioGmLp** [FTBTeam/FTB-Sky-Adventures#31]
Modpack Version: 1.0.0

Issue: Ender Generator keep eating ender Pearls and eyes, no matter if a stack is already inside
I just have a somply Setup:

Drawer Whit Ender Pearls
Hopper
End Generator

The Generaot keep taking pearls all the time, inside only appear 1 but the number on the Drawer keep falling

Link to Log or Crash File Paste: Dont crash the game

Is it Repeatable?: yes

**Comment by iKurama** [comment]
Same goes for Culinary generator. It ate a whole diamond chest full of chicken..

**Comment by Hiagg** [comment]
This happens with literally every exu machine. Can't automate the enchanter for speed upgrades because the items disappear no matter what if you try and put in more items while there's something else in the slot. Doesn't even stack them

**Comment by tfox83** [comment]
Yes this is being worked on in dev.

**Comment by tfox83** [comment]
this fix is now in the next update of the pack in dev
