### ISSUE TITLE
Server Crash because of ServerHangWatchdog

### ISSUE THREAD

**Issue by jhihi00** [FTBTeam/FTB-Sky-Adventures#312]
ServerHangWatchdog detected that a single server tick took 0.60 seconds

My friend is hosting a Feed The Beast Sky Adventure server. The server was fine in the last few days. However, he said the server crashed today with the crash report below:

https://gist.github.com/jhihi00/0618ca443983530953d7841a614ad400

He has tried to alter the max tick to -1 but the server still crashed. Also there is no crash log after he set the max tick to -1. What can we do?

**Comment by 016Nojr** [comment]
If you're still playing, try updating to the latest version and see if it's still happening
