### ISSUE TITLE
OreExcavation not working on server

### ISSUE THREAD

**Issue by UncleSalty77** [FTBTeam/FTB-Sky-Adventures#317]
Running FTBSkyAdventures-1.4.0-1.12.2.zip hosted by Nodecraft January 26, 2021
OreExcavation-1.4.133.jar
OreExcavation works fine on single player worlds but for some reason isn't working on the server changing any in-game setting. Any help or ideas for a fix would be appreciated.

**Comment by 016Nojr** [comment]
Please update to pack version 1.5.0, Ore Excavation has been replaced with FTB Ultimine
