### ISSUE TITLE
Storage Disk Recipe Little Bug in 1.1.0?

### ISSUE THREAD

**Issue by Onigeshi** [FTBTeam/FTB-Sky-Adventures#34]
* **Modpack Version**: 1.1.0
* **Issue**: the new recipe for the 64k storage has next problems:
1. the 64k fluid storage disk gives the 64k component that is used to craft the disk for items ( http://prntscr.com/l7qh5u , http://prntscr.com/l7qh9k ) not the one that is used to craft the fluid disk ( http://prntscr.com/l7qh29 ) 
2. difference in EMC ( http://prntscr.com/l7qhex , http://prntscr.com/l7qhi8 ) but I guess this should be a compromise to get it to work..

**Comment by tfox83** [comment]
fixed in dev
