### ISSUE TITLE
Request user friendly Currency Recipes

### ISSUE THREAD

**Issue by PiggyWhiskey** [FTBTeam/FTB-Sky-Adventures#35]
The Currency Recipes are quite complex and make it difficult to convert between different values.
I've got $422 and change in various currencies and just trying to combine my coins is a nightmare. Having to convert up and down to get the recipe ingredients.

Can we have a standard set of recipes.
5x 1 cent = 1x 5 cent
2x 5 cent = 1x 10 cent
5x 5 cent = 1x 25 cent
4x 25 cent = 1x 1 dollar coin
1x 1 dollar coin = 1x 1 dollar note
5x 1 dollar note = 1x 5 dollar note
etc etc

With the reverse recipes as well.

This way we can convert to a easy to manage value when trying to claim the Currency Rewards.

**Comment by tfox83** [comment]
all the coins are removed in next version making this much more simple
