### ISSUE TITLE
Infinite EMC Loop

### ISSUE THREAD

**Issue by halosamuel44** [FTBTeam/FTB-Sky-Adventures#36]
* **Modpack Version**: 1.0.0

* **Issue**: Magma Block's EMC is 3 times lower than Magma cream's. Pulverizing a Magma Block gives you 4 Magma creams, making a profit of ~1000 EMC. Repeat for infinite EMC.

* **Is it Repeatable?**: Yes
* **Mod/s Affected**: ProjectE
* **Known Fix**: Change Magma Block's EMC value so that it is 4 times that of Magma Cream

**Comment by tfox83** [comment]
increased EMC of magma block to 1356 next update, thanks.
