### ISSUE TITLE
Starfield Creator

### ISSUE THREAD

**Issue by Slowpoke101** [FTBTeam/FTB-Sky-Adventures#38]
* **Modpack Version**: <Sky Adventures 1.1.0

* **Issue**: Starfield Creator way to cheap to make for the reward in repeatable quests

**Comment by ghost** [comment]
I agree, for less than 1M EMC you can create basically create the tome.

**Comment by PiggyWhiskey** [comment]
Basically: 3,136 EMC = $50
1,254,400 EMC = Tome of Knowledge.

**Comment by tfox83** [comment]
Has been removed in dev
