### ISSUE TITLE
Error when starting MP Server

### ISSUE THREAD

**Issue by Shadowstriker0s** [FTBTeam/FTB-Sky-Adventures#39]
* **Modpack Version**: FTBSkyAdventuresServer_1.0.0

* **Issue**: Forge Mod Loader detected missing/unknown registrie(s).

There are 2 missing registries in this save.
If you continue the missing registries will get removed.
This may cause issues, it is advised that you create a world backup before continuing.

Missing Registries:
ironbackpacks:upgrade
ironbackpacks:types

Run the command /fml confirm or or /fml cancel to proceed.
Alternatively start the server with -Dfml.queryResult=confirm or -Dfml.queryResult=cancel to preselect the answer.>

**Comment by RedstoneParkour** [comment]
This is what happens with a FML server when certain blocks or items are missing from a world. 
Restart your server and run '/fml confirm' to remove these entries and continue normally.
But still, make a world backup by copying the world.
I am not part of the FML team (if that exists).

**Comment by Shadowstriker0s** [comment]
Sounds good, I wasn't completely sure because there already was a "World" folder after extracting the files.

**Comment by RedstoneParkour** [comment]
Well you didn't say that you just installed the server so i expected that it was a server that generated a world

**Comment by shadus** [comment]
The server zip file actually contains a world, if you /ftb confirm the entries there is a second set of them that come up as missing as well, lot of basic items missing even, like xp potions, etc.  Not sure if this a bug or working as intended.

**Comment by RedstoneParkour** [comment]
I also don't know

**Comment by tfox83** [comment]
This is working as intended, due to changes with mod updates you will likely always have to do a /fml confim whenever loading the default world.  There is no way around that in dev.

**Comment by Shadowstriker0s** [comment]
Awesome, thanks for looking into it!
