### ISSUE TITLE
Clumps no longer depends on B.A.S.E

### ISSUE THREAD

**Issue by walker-dev** [FTBTeam/FTB-Sky-Adventures#41]
* **Modpack Version**: Any

* **Issue**: B.A.S.E is no longer required by clumps as of 1.12, 

* **Mod/s Affected**: B.A.S.E, Clumps

* **Known Fix**: Remove B.A.S.E from pack

**Comment by walker-dev** [comment]
same with  Shadowfacts' Forgelin not relying on shadowMC anymore

**Comment by tfox83** [comment]
both removed in dev, thanks.  fml confirm will throw due to base:wrench being removed, which is fine.
