### ISSUE TITLE
Version 1.0.0 crash logs

### ISSUE THREAD

**Issue by Magesw** [FTBTeam/FTB-Sky-Adventures#42]
* **Modpack Version**: 
1.0.0

* **Issue**: 
Server crashes

* **Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/1957523c

* **Is it Repeatable?**: 
Assume so as it is has happened a couple times and is the same crash

* **Mod/s Affected**: 
I am not sure

* **Known Fix**: 
Not sure

**Comment by tfox83** [comment]
Please try a fresh install.  I cant reproduce this crash in SMP or SSP.  Thanks

**Comment by Magesw** [comment]
> Please try a fresh install. I cant reproduce this crash in SMP or SSP. Thanks

It was a fresh server install as of 4.5-5 days ago. I will just keep a lookout for it again.
