### ISSUE TITLE
Shift click into Furnace Generator deletes items

### ISSUE THREAD

**Issue by bgleadle** [FTBTeam/FTB-Sky-Adventures#43]
* **Modpack Version**: 1.0.0

* **Issue**: When there's items already in the burn slot of the Extra Utilities 2 Furnace Generator and you attempt to shift click more of the same item in it just deletes what you shift click in. This has happened with Coal and Alchemical Coal. 
- Ensure there's at least 1 item in the burn slot
- Shift click any number more into the furnace generator and it will just disappear 

* **Link to Log or Crash File Paste**: No crash, not sure where the log would be.

* **Is it Repeatable?**: Repeatable every time

* **Mod/s Affected**: extrautils2-1.12-1.9.6

* **Known Fix**: Unknown

**Comment by walker-dev** [comment]
Fix is beeing worked on by rwtema, should be fixed in next release.
https://github.com/rwtema/Extra-Utilities-2-Source/commit/36ce3a05bbe2c2ca76bb71898312b43899e10241

#31

**Comment by bgleadle** [comment]
Ah should have been smarter and looked for that first :|

**Comment by tfox83** [comment]
this fix is now in the next update of the pack in dev
