### ISSUE TITLE
Over-Powered EMC: Beat Game in 2 Hours

### ISSUE THREAD

**Issue by rShyvers** [FTBTeam/FTB-Sky-Adventures#44]
1 Dirt(1 EMC) > 1 Akashic Tome > Dragonic Tablet(8200 EMC)

Rinse and Repeat

**Comment by RedstoneParkour** [comment]
Dragonic Tablet does not exist anymore.

**Comment by iKurama** [comment]
As in you have to manually go through each book and as in that you can bypass IC2, Thaumcraft, Botania and BM?
Less clickbait next time please.

**Comment by Salnex** [comment]
Seems like a very slow and manual way to generate emc

**Comment by tfox83** [comment]
That recipe for the tome has been removed in this pack in dev
