### ISSUE TITLE
Most quests should ignore NBT

### ISSUE THREAD

**Issue by predakanga** [FTBTeam/FTB-Sky-Adventures#45]
Most quest items should ignore NBT for the turn-in, for two main reasons.

Functional:
Certain items have NBT tags upon creation, but the quest requires an item with no tags.
Example: Gargantuan Flux Storage (Tech Tree tab)

Convenience:
Many items use NBT to store their settings, but you might craft them before the quest is available, or simply forget to turn them in before placing and using them. This results in having to re-craft the item just for the quest, an annoying experience.
Examples:
- Watering cans (Food tab - crafted before the quest is available)
- Most machines - (Actually Additions, Thermal Expansion, Ender IO, Industrial Foregoing are all affected)

**Comment by tfox83** [comment]
Majority of the items are set to ignore NBT, I must of missed that one.  Thanks

![image](https://user-images.githubusercontent.com/4246308/47317810-52f58900-d5ff-11e8-851d-f08e0c450438.png)

**Comment by tfox83** [comment]
Disabled damage on the watering cans as well
