### ISSUE TITLE
MP server problem

### ISSUE THREAD

**Issue by Vudul** [FTBTeam/FTB-Sky-Adventures#46]
* **Modpack Version**: 1.0.0

* **Issue**: I don't know why but when I start my MP server there's no quests books and there is another
 Island than on the Singleplayer.

**Comment by ProsperCraft** [comment]
I didn't have this problem on my multiplayer server, did you download the server download and start with that? 

Also, the modpack is now on 1.1.0 try setting it up fresh?

**Comment by Mordaii** [comment]
I had this problem when I left and made a new team.  
I was able to bind my open quest to a key-bind (Z for example) and it was my workaround.

**Comment by Vudul** [comment]
I change modpack version and the problem still exist. I dont have quest book and There is another island without nothing. But on singleplayer everything is Ok

**Comment by Vudul** [comment]
Any ideas?

**Comment by CBree** [comment]
I had a similar problem... my world actually wasn't there and all I did was fall to my death. I launched in single player and copied that save to my server to get it to work.

**Comment by Vudul** [comment]
It doesn't work. Quest books disappeared and half of island didnt load

**Comment by CBree** [comment]
To open the quest book  it's either CTRL+G or CTRL+B. It's one of those. But this software is really buggy, but it's also new, so bare with the dev, I'm sure it will get fixed.

**Comment by tfox83** [comment]
Please make sure you are using the world that is shipped with the server when you start.
