### ISSUE TITLE
Lootbag dupe = EMC

### ISSUE THREAD

**Issue by ghost** [FTBTeam/FTB-Sky-Adventures#47]
* **Modpack Version**: 1.0.0

* **Issue**: Create a bag storage with 1 single iron ingot/chest and some stone, insert any lootbag and hover over it. Press any empty slot number (1-9). Do this with artifact bags and you'll never run out.

* **Is it Repeatable?**: Yes!

* **Mod/s Affected**: LootBags-1.12.2-2.5.7 - Latest

* **Known Fix**: Issue is known by the author, disable the bag storage block.

**Comment by iKurama** [comment]
https://github.com/Malorolam/LootBags/issues/155
