### ISSUE TITLE
Can't Make Project E Omega Kleign Star

### ISSUE THREAD

**Issue by Zodsmar** [FTBTeam/FTB-Sky-Adventures#48]
* **Modpack Version**: 1.0.0>

* **Issue**: Any Kleign Stars above the base one have no recipe.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Project E

* **Known Fix**:

**Comment by tfox83** [comment]
Its an issue with JEI not showing them, its just 4 first in a crafting table to tier them up and so on. Will see if they can get them showing properly next update

**Comment by Zodsmar** [comment]
Ah ok thanks!
