### ISSUE TITLE
Chickens/ Hatchery Crash 

### ISSUE THREAD

**Issue by Misa1029** [FTBTeam/FTB-Sky-Adventures#51]
[https://pastebin.com/embed_js/V6rkssK8](url)

This happened twice about 30 to 45 minutes apart. Had a Chicken in the net, forgot to Shift + right click into nesting pen, tried to exit by pressing ESC, screen freezes, then crashes.

**Comment by tfox83** [comment]
The crash link is an invalid link for me

**Comment by JayPeaSize** [comment]
Had to copy the link and manually paste it in. Re-pastebinned for you: https://pastebin.com/gTTHj68A

**Comment by tfox83** [comment]
fixed in next version
