### ISSUE TITLE
Powered spawners useless

### ISSUE THREAD

**Issue by DrGamingNL** [FTBTeam/FTB-Sky-Adventures#52]
* **Modpack Version**: 1.1.0

* **Issue**: Unable to get broken spawners

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: EnderIO

* **Known Fix**: 

There seems to be no way to craft a broken spawner. There is also no way I know of to get one: Nether fortresses seem to be disabled.

**Comment by lachian** [comment]
There are regular spawners in the Deep Dark (vanilla monster spawner rooms and vanilla mining shaft cave spider sapwners) but you're right, hunting for them is a lot harder than just flying around the Nether. I guess you can just set a builder down and cross your fingers and hope it quarries a spawner.

**Comment by DrGamingNL** [comment]
Oh thanks hadnt thought about that.
