### ISSUE TITLE
Sand through a string mesh -- is it working properly?

### ISSUE THREAD

**Issue by DelfCo** [FTBTeam/FTB-Sky-Adventures#53]
* **Modpack Version**: 1.0.0

* **Issue**: I know, it could just be that RNGesus hates me. But I've put something like thirty or forty sand through a string mesh and haven't received a single drop from it yet. That doesn't seem to match with the drop rates shown. Could you take a look and make sure the probabilities are configured properly? I'm thinking (hoping, because this is grindy enough without RNGesus hating me) maybe someone accidentally specified .10% instead of 10% or something?

* **Link to Log or Crash File Paste**: Not a crash. No log.

* **Is it Repeatable?**: I've restarted my world three times, seen this in all three.

* **Mod/s Affected**: Ex Nihilo? Hard to look at the mod list when you put a browser in-game, over top of the game.

* **Known Fix**:

**Comment by PiggyWhiskey** [comment]
Sand through a String Mesh will only get you Cocoa Beans. 3% drop rate
If you want resources, use Gravel.

**Comment by lachian** [comment]
Check sieving JEI recipes, they have been changed in this pack.

**Comment by DelfCo** [comment]
I made a mistake, and was looking at the stats for dust rather than sand. Closing before more people see my error.
