### ISSUE TITLE
Refined Storage parts have EMC

### ISSUE THREAD

**Issue by Venrixia** [FTBTeam/FTB-Sky-Adventures#54]
* **Modpack Version**: 1.1.0

* **Issue**: 64k storage part and 64k fluid storage part along with their respective cells have a emc value under 3000 emc

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Project E & Refined Storage

* **Known Fix**: Remove the emc value of the affected items with /projecte removeEMC and reload the config with /projecte reloadEMC

**Comment by tfox83** [comment]
Fixed in dev
