### ISSUE TITLE
Immersive Excavator not generating ores

### ISSUE THREAD

**Issue by Stanley975** [FTBTeam/FTB-Sky-Adventures#55]
Modpack Version: 1.1.0

Issue: Immersive Engineering Excavator doesn't produce any ores in an ore chunk.

Mod/s Affected: Immersive Engineering

**Comment by mooretec** [comment]
If I remember right the IE Excavator requires some base to be build just put some stone around it's base and it should start working.

**Comment by ProsperCraft** [comment]
Yes, Mooretech is correct, you need to put a couple layers of dirt under the wheel so it can get a bite into the soil, then it will work.

**Comment by Stanley975** [comment]
Thanks
