### ISSUE TITLE
Player data not cleared when island is remade.

### ISSUE THREAD

**Issue by ProsperCraft** [FTBTeam/FTB-Sky-Adventures#56]
I don't know if this is intended but players can bypass the inventory wipe when leaving a team by simply putting the items in their enderchest, Alchemical bags, or putting everything in a transmutation tablet, as everything learned is saved, and the EMC.

If possible I would suggest player gets kicked on leaving a team with the message to rejoin for a fresh start, and their playerfile get deleted.

**Comment by tfox83** [comment]
That is correct, the way that data is stored you would need an admin to delete the actual player file in the server.  A mod cant accomplish this without being really dirty.  I will talk to the dev about adding a message, thanks.
