### ISSUE TITLE
Environmental Tech Solar Array Controller Tier 1 can't be broken/picked up

### ISSUE THREAD

**Issue by ffgda** [FTBTeam/FTB-Sky-Adventures#59]
* **Modpack Version**: 1.0.0, 1.1.0

* **Issue**: I created an Environmental Tech Solar Array Controller Tier 1 with the Transmutation Table, placed it down and tried to break it with both the Environmental Tech Assembler (by shift-right-clicking) and my Tinkers Construct Pickaxe. I'm not able to.

* **Link to Log or Crash File Paste**: -

* **Is it Repeatable?**: Yes, I created another one with the Transmutation Table and the same issue occurs.

* **Mod/s Affected**: Environmental Tech

* **Known Fix**: -

**Comment by ffgda** [comment]
I just found a work-around: after starting to assemble the Solar Array by placing a single Structure Frame, I was able to break the Solar Array Controller.

**Comment by ghost** [comment]
I can confirm this; every controller does this on every tier.

**Comment by tfox83** [comment]
fixed in dev
