### ISSUE TITLE
Snow not acting like rain and filling barrels 

### ISSUE THREAD

**Issue by NicelysBabyGirl** [FTBTeam/FTB-Sky-Adventures#6]
* **Modpack Version**: FTB Sky Adventures version1.0.0
* **Issue**: snow is not acting like rain and filling barrels with water

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by tfox83** [comment]
fixed in next version
