### ISSUE TITLE
Question About Wither Skeletons/Wither Dust

### ISSUE THREAD

**Issue by IulianDan** [FTBTeam/FTB-Sky-Adventures#60]
Modpack Version: 1.0.0

Issue: So i've been stuck at a point where i just don't know how to get Wither Skeletons/Wither Dust. Since the nether is a void i don't really know where i could find them. Am i stupid/missing something? Please Help.

Link to Log or Crash File Paste: not important

Is it Repeatable?: not important

**Comment by ffgda** [comment]
https://ftbwiki.org/Witch_Water

**Comment by IulianDan** [comment]
Thx
