### ISSUE TITLE
Energy cells has no recipe

### ISSUE THREAD

**Issue by SkellyGR** [FTBTeam/FTB-Sky-Adventures#61]
* **Modpack Version**: 1.0.0

* **Issue**: I tried to make flux infused jetplate but I can't see any energy cells recipe when I click on them, I also tried typing it's name on the search box and it doesn't find anything with that name.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Thermal expansion
* **Known Fix**: I don't know any fix :/

**Comment by Eifekk** [comment]
Just tested, make an Energy Cell (Basic) and use the Thermal Foundation Upgrade kits to upgrade it when it's placed it the world, as with other Thermal Expansion machines.

![download](https://user-images.githubusercontent.com/44320296/47256831-bc4d8e80-d47d-11e8-929f-a3239d4e4dc6.png)
![download 1](https://user-images.githubusercontent.com/44320296/47256832-beafe880-d47d-11e8-8919-ceaa5135c18d.png)

**Comment by ProsperCraft** [comment]
Thermal changed at one point during 1.12.2.
You have to make the basic everything, then upgrade or convert it.

Also the items are enchantable as well, make sure you enchant them.

**Comment by tfox83** [comment]
That is the correct method as ProsperCraft and Eifekk stated above.
