### ISSUE TITLE
Chaos shard unobtainable

### ISSUE THREAD

**Issue by Eifekk** [FTBTeam/FTB-Sky-Adventures#62]
* **Modpack Version**: 1.1.0

* **Issue**: There is no recipe to craft the Chaos Shard from Draconic Evolution and it is unobtainable via the usual method as there's no world gen for the chaos islands to spawn. This has halted my progression in Draconic Evolution.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes/Persistent

* **Mod/s Affected**: Draconic Evolution

* **Known Fix**: Add a crafting recipe to make the Chaos Shards.

**Comment by Kusouwu** [comment]
killed a chaos dragon the islands are really far

**Comment by Eifekk** [comment]
> killed a chaos dragon the islands are really far

they spawn even with the void world?

**Comment by Kusouwu** [comment]
yes

**Comment by Eifekk** [comment]
any of the other structures spawn? like so we can get an elytra?

**Comment by iKurama** [comment]
You can buy the shards too. If you go into Botania and craft starfield creators (if extra rewards are unlocked, but these are repeatable)
