### ISSUE TITLE
Chickens

### ISSUE THREAD

**Issue by Angelus022695** [FTBTeam/FTB-Sky-Adventures#63]
* **Modpack Version**:1.0

* **Issue**: No regular chickens will spawn so you cant progress into chickens any further then the chickens you have to buy.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: Chickens

* **Known Fix**:

**Comment by iKurama** [comment]
They do spawn, you just need a big patch of grass. Even donkeys do.

**Comment by walker-dev** [comment]
[default_chickens.zs.txt](https://github.com/FTBTeam/FTB-Sky-Adventures/files/2498384/default_chickens.zs.txt)

**Comment by Mokradin** [comment]
Or you can use your philosopher stone to transmute (passive) mobs.

**Comment by DelfCo** [comment]
Note that what you get on a big patch of grass varies with what biome it's in. If someone's on a Deep Ocean biome, they might not get chickens.

That said, I found a chicken in my primitive mob grinder a little while ago. Alas, it did not drop an egg.

**Comment by isavegas** [comment]
Had the same issue. Looks like they've fixed the issue; it just hasn't been pushed to CurseForge. #19 

I suggest just using the honor system: spawn some in and throw away a hatchery egg whenever you use one. Once you register it in a transmutation table, you'll be golden anyway. 👍

**Comment by tfox83** [comment]
Public Beta 1.1.0 has an egg recipe using the carpenter.
