### ISSUE TITLE
Thaumonomicon

### ISSUE THREAD

**Issue by IulianDan** [FTBTeam/FTB-Sky-Adventures#64]
* **Modpack Version**: 1.0.0

* **Issue**:  I'm here to ask about the Thaumonomicon. I can't seem to find a way to obtain it. Since the Akashic Tome can't transform into the Thaumonomicon and it doesn't seem to have a crafting recipe
i don't know what to do. Maybe i'm just blind or something idk. Same thing for the Thaumometer.

* **Link to Log or Crash File Paste**: 'BLANK'

* **Is it Repeatable?**: 'BLANK'

* **Mod/s Affected**:  Thaumcraft?

**Comment by walker-dev** [comment]
have you read the book when you obtain those fancy crystals?

**Comment by IulianDan** [comment]
Yes but how do you obtain them?
I know there are some on the island but you need 3 different ones.

**Comment by Mokradin** [comment]
you need to sieve to get them, and place in the world to harvest

**Comment by IulianDan** [comment]
Oh, ok thx.
