### ISSUE TITLE
RS 64k disks from quest rewards bugged

### ISSUE THREAD

**Issue by grav0r** [FTBTeam/FTB-Sky-Adventures#65]
Refined Storage 4x 64k Storage Disk is a nice quest reward, but it has zero storage space, so its worthless..
The crafted 64ks work.

**Comment by iKurama** [comment]
https://github.com/FTBTeam/FTB-Sky-Adventures/issues/13

**Comment by tfox83** [comment]
That was fixed in 1.1.0 with a recipe to pull the part from the disk and recraft with correct NBT.  Also fixed better in dev for next version.
