### ISSUE TITLE
"Salis Mundus" not working

### ISSUE THREAD

**Issue by IulianDan** [FTBTeam/FTB-Sky-Adventures#66]
* **Modpack Version**: 1.0.0

* **Issue**: Salius Mundus is supposed to transform stuff into other stuff (eg. Cauldron -> Crucible, Workbench -> Arcanic Workbench) yet it doesn't seem to do that.

* **Link to Log or Crash File Paste**: 'Blank'

* **Is it Repeatable?**: 'Blank'

* **Mod/s Affected**: "Thaumcraft"

* **Known Fix**: I don't know

**Comment by iKurama** [comment]
Did you sleep after obtaining a crystal, so that you would get a book?
