### ISSUE TITLE
Quest Book 

### ISSUE THREAD

**Issue by DinnerBeef** [FTBTeam/FTB-Sky-Adventures#67]
* **Modpack Version**: All 

* **Issue**: No way to get the quest book if you lost it(yes i know there is one in your inv)

* **Is it Repeatable?**: yes any one that you play you can get it back

* **Mod/s Affected**:  FTB Quests

* **Known Fix**: Add a recipe and a emc value to the book

**Comment by iKurama** [comment]
You can use the keybinds to open one. When you go into your inventory, up top next to the guides, you can enter the questbook too.

**Comment by DinnerBeef** [comment]
yea i know but the book is still nice to have

**Comment by tfox83** [comment]
Added in dev, thanks for the heads up

![image](https://user-images.githubusercontent.com/4246308/47316051-0445f000-d5fb-11e8-8ee4-7bdb0685620f.png)
