### ISSUE TITLE
EnderIO Silicon doesn't work in Thermal Expansion Induction Smelter

### ISSUE THREAD

**Issue by DelfCo** [FTBTeam/FTB-Sky-Adventures#68]
* **Modpack Version**: 1.0.0
* **Issue**: Trying to make Electrical Steel in the Induction smelter using the Silicon I get from chickens. No go. Gotta have the other kind of silicon. Shouldn't the two be interchangeable?

* **Link to Log or Crash File Paste**: No log or crash file.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Idunno, is Thermal Expansion explicitly not using other forms of silicon? It looks like I could have avoided this problem by making an Alloy Smelter. It seems to take both kinds of silicon.

* **Known Fix**: ???

**Comment by Salnex** [comment]
Too add to this issue. Despite what jei suggests recipes in the induction smelter only take thermal hardened glass. Not fused quartz

**Comment by tfox83** [comment]
I unified all silicon types EMC in dev.  As well as added recipes to convert the types due to not being able to force change some drop types
