### ISSUE TITLE
Quests that can't be turned in. (Flux controller and Plug)

### ISSUE THREAD

**Issue by Grimjahk** [FTBTeam/FTB-Sky-Adventures#69]
* **Modpack Version**: 
1.0.0 Server version 2 players.
* **Issue**: 
Cannot turn in Flux Controller or Flux Plug from Tech Tree
* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 
Yes
* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Mokradin** [comment]
The solo version have the same issue, so i have a temporary fix: Teach them in your transmutation tablet, close it, and pick the items again, it works for me.

**Comment by SilverWolf147** [comment]
This also seems to be a problem with the Swiftwolf's Rending Gale Ring.  I made two of them and can't complete the quest.

**Comment by Grimjahk** [comment]
OK, work-around did it.

**Comment by tfox83** [comment]
Ok set flux stuff to ignore NBT as well as Rending Gale ring.
