### ISSUE TITLE
Aqua crystals listed twice in Ex Nihilo drop list

### ISSUE THREAD

**Issue by TheSaucyWelshman** [FTBTeam/FTB-Sky-Adventures#7]
* **Modpack Version**: 1.0.0

* **Issue**: Thaumcraft aqua crystals have 2 drop entries, all others only have 1. Not a huge deal but this means you have a higher chance at aqua crystals than any other when they should be equal.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**:  Yes

* **Mod/s Affected**:  Thaumcraft, Ex Nihilo

* **Known Fix**: Remove one set of aqua crystal drops from the config

**Comment by tfox83** [comment]
fixed in dev
