### ISSUE TITLE
Cannot level up Iron chickens

### ISSUE THREAD

**Issue by ironrainomega** [FTBTeam/FTB-Sky-Adventures#70]
Unable to level up iron chickens

* **Modpack Version**: 1.0.0

* **Issue**: Since breeding 2 iron chickens together can yield refined iron chickens, I'm unable to level up iron chickens. Have tried for over an hour now.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Chickens

**Comment by MarioGmLp** [comment]
You can use a Iron Chicken and a Rooster and let them get naughty Lol

**Comment by tfox83** [comment]
Correct, I was able to level them up with seeds and/or a rooster.
