### ISSUE TITLE
Legendary Loot Crate is way too OP for getting the Transmutation Tablet

### ISSUE THREAD

**Issue by Zodsmar** [FTBTeam/FTB-Sky-Adventures#71]
* **Modpack Version**: 1.1.0

* **Issue**: I unlocked the transmutation Tablet and got the Legendary Loot Crate. I bet it is rare to get but I ended up getting a Red Matter Furnace (10 Million EMC) Basically after that it took me like 2 hours or less to gain then another 10 million. Since then Ive put maybe 10 hours into the pack not even and I have over 250 Million EMC and Gem armor and basically every end game item possible to get with EMC.
The only quests I have done are the ones I have to grind to build because building it once then EMC is not possible so its just grindy.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: 

* **Known Fix**: Remove Red Matter Furnace from Legendary Lootbag or make it an Epic for that quest

**Comment by DinnerBeef** [comment]
you know that is kinda that point of that loot crate

**Comment by iKurama** [comment]
It's a legendary crate for a reason. It costs 750 for a reason too.

**Comment by tfox83** [comment]
intended
