### ISSUE TITLE
Gold Ingots to demon metal makes getting EMC extremely easy

### ISSUE THREAD

**Issue by AgentTennessee** [FTBTeam/FTB-Sky-Adventures#73]
* **Modpack Version**: 1.1.0

* **Issue**:  Demon Ingots have 3 million EMC and all you have to do is throw gold into lava surrounded by netherbrick. This should be lowered significantly.

* **Is it Repeatable?**: Yes
* **Mod/s Affected**: ProjectE, Extra Utilities
* **Known Fix**: Change demon ingots emc value to much lower

**Comment by IulianDan** [comment]
Maybe the Demon Ingots should have the same EMC value as gold so it's more fair

**Comment by IulianDan** [comment]
Are you sure you are playing on the 1.1.0 version of the pack and not 1.0.0?
I'm in 1.1.0 and Demon Ingots don't even have any emc value.
https://gyazo.com/17b7a94e1b5f8c45a802aa740e2e7b28

**Comment by AgentTennessee** [comment]
Yeah, this was a fuck up on my part. Server admin added the EMC value while I was offline and I thought it was just some random oversight.
