### ISSUE TITLE
Item duplication with RS + rftools.

### ISSUE THREAD

**Issue by booblebobble** [FTBTeam/FTB-Sky-Adventures#75]
Version: 1.1.0

Issue: This, basically: https://youtu.be/sjS0b1ne4Kk

There seems to be a problem with using an rftools crafter as external storage in an RS system that makes it simple to infinitely dupe anything with a 'compressed' form (and no doubt other things).

Tried the exact same setup in 1.10 (Sky Factory 3) and it worked as expected with no bugs, and also tried an analogous setup in SA with AE2 instead of RS and it worked as expected.

**Comment by tfox83** [comment]
The devs are aware of this bug and since it relies on 3 different mods I am not sure an eta for a fix, I am going to close it here so it isnt visible.  Thanks.
