### ISSUE TITLE
Solidified Expierence

### ISSUE THREAD

**Issue by IulianDan** [FTBTeam/FTB-Sky-Adventures#76]
* **Modpack Version**: 1.1.0

* **Issue**: It seems like Solidified XP is not dropping from mobs. If there is any other way to get it then someone please tell me.

* **Mod/s Affected**: Actually Additions

**Comment by SilverWolf147** [comment]
You can use an experience solidifier from actually additions to get it.  It will collect dropped XP orbs and convert them to solidified experience.

**Comment by tfox83** [comment]
Use an experience solidifier
