### ISSUE TITLE
Hatchery Eggs recipe?

### ISSUE THREAD

**Issue by AnimeNerdDJBROS** [FTBTeam/FTB-Sky-Adventures#77]
* **Modpack Version**: 1.0.0

* **Issue**: The recipe shows up but when you try to use a hatchery egg to make regular chicken eggs it doesn't work.
* **Link to Log or Crash File Paste**: No crash or anything cuz the issue is just recipe and game, basically just might be a recipe not working, or please tell me if it was intended to not be able to.

* **Is it Repeatable?**: It's repeatable as it's just a problem recipe

* **Mod/s Affected**: The only mod affected obviously would be hatchery making it a lot harder to get an average chicken.

* **Known Fix**: No known fix

![b1](https://user-images.githubusercontent.com/42410080/47267980-c40e4100-d518-11e8-8629-ec018e43d918.PNG)

![b2](https://user-images.githubusercontent.com/42410080/47267984-cd97a900-d518-11e8-9732-486dabda20f3.PNG)

**Comment by isavegas** [comment]
Looks like the issue has been addressed and the fix will be in the next version uploaded to CurseForge: #19.

I suggest using the honor system and just spawning in some vanilla eggs for your crafting needs for now, throwing away hatchery eggs any time you do.

The transmutation table can help you avoid messing with that if you need them for recipes, once you've gotten that far and registered one with it, although you'll have to add the recipes using a Craft Tweaker script if you absolutely need the recipe for automation purposes or the like.

**Comment by tfox83** [comment]
Until that is properly fixed by the dev I added a egg recipe using seeds in the carpenter in v1.1.0
