### ISSUE TITLE
Pack crash issue

### ISSUE THREAD

**Issue by usamahhoosen** [FTBTeam/FTB-Sky-Adventures#79]
* **Modpack Version**: 1.1.0

* **Issue**: My pack instantly freezes and then crashes when I try to shift click a receipe in to the refined storage crafting grid.

* **Is it Repeatable?: Yes I tried with a few recipes and pack crashes every time

* **Mod/s Affected**: Refined Storage

**Comment by iKurama** [comment]
Crashlog <.<

**Comment by usamahhoosen** [comment]
I took the 15 mins before the crash. https://paste.feed-the-beast.com/view/3d5d98a3

**Comment by tfox83** [comment]
I will need the actual crash report that is generated and saved in minecraft/crash reports.  Thanks

**Comment by usamahhoosen** [comment]
That folder doesnt exist in my minecraft folder

**Comment by tfox83** [comment]
Do you have 4GB of ram assigned to java/pack?

**Comment by usamahhoosen** [comment]
I have 6GB allocated

**Comment by usamahhoosen** [comment]
I think I have narrowed down the issue. It only starts when I try to shift click the recipe for the Extra Utilities 2 Magical snow globe. Before that I can do other items without a problem.

**Comment by iKurama** [comment]
We still need the actual crashlog to help you.

**Comment by usamahhoosen** [comment]
What has to happen in order for the crash log to be generated?

**Comment by iKurama** [comment]
It is most likely inside /crashlogs/ or sometimes in the "Latest" log, depending on if the game has crashed in the latest game session.

**Comment by Tathra365** [comment]
[crash-2017-06-18_15.57.33-client.txt](https://github.com/FTBTeam/FTB-Sky-Adventures/files/2544916/crash-2017-06-18_15.57.33-client.txt)
I have this same issue and here's my crash report

**Comment by iKurama** [comment]
@Tathra365 "Minecraft Version: 1.8.8", "spigot & bungeecord" and "shaders" inside the crashlog suggests that this isn't supported.

**Comment by Tathra365** [comment]
@iKurama I'm running minecraft version 1.12.2, i have no idea what spigot or bungeecord are and i dont use shaders.

EDIT: Dunno what i did, but it seems to be fixed for me
