### ISSUE TITLE
Ex Nihilo Creatio (Solved)

### ISSUE THREAD

**Issue by SilverWolf147** [FTBTeam/FTB-Sky-Adventures#8]
* **Modpack Version**: FTB Sky ADventures 1.0.0

* **Issue**: The Auto Sifter, stone axels, and water wheels from Ex Nihlo Creatio have no recipes.

* **Link to Log or Crash File Paste**: N/A

**Comment by twsx** [comment]
This is not a bug.

	#remove items
	mods.jei.JEI.removeAndHide(<extrautils2:user>);
	mods.jei.JEI.removeAndHide(<exnihilocreatio:block_waterwheel>);
	mods.jei.JEI.removeAndHide(<exnihilocreatio:block_axle_stone>);
	mods.jei.JEI.removeAndHide(<exnihilocreatio:block_grinder>);
	mods.jei.JEI.removeAndHide(<exnihilocreatio:block_auto_sifter>);

They were intentionally removed.
Consider that auto sifting in combination with ProjectE would really break the back.

**Comment by TheSaucyWelshman** [comment]
"Consider that auto sifting in combination with ProjectE would really break the back."

But chickens are okay...

**Comment by twsx** [comment]
... but you would never bother to do chickens if you had Ex Compressum or Creatio's own automation. Or Bees. Or anything else for that matter.

**Comment by TheSaucyWelshman** [comment]
You might not, doesn't mean no one would. I never touched auto-sifting of any sort in Stoneblock despite there being many easy ways of doing it.
