### ISSUE TITLE
Thaumcraft

### ISSUE THREAD

**Issue by MjolnirMouse** [FTBTeam/FTB-Sky-Adventures#80]
* **Modpack Version**: first version and then the first beta update as well

* **Issue**: Vis crystals do now always spawn on starter island and the crystals that you get from sieving crushed netherack are not vis crystals therefore thaumcraft is not usable if you get an island with no vis. 
* **Link to Log or Crash File Paste**: no crash

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Thaumcraft

* **Known Fix**: My suggestion would be to change the crystals gathered sieving to the primal Vis crystals. Or create recipes to change the crystals gained sieving into the vis crystals

**Comment by isavegas** [comment]
You can find vis crystals in abundance in the deep dark. Once you mine your way down to the cavern floor, you should be able to collect plenty of crystals as long as you're adequately kitted out.

If you're unfamiliar with the deep dark, I highly suggest doing a little research into it before you visit, as it can be rather dangerous for people who don't know what to expect, for a number of reasons. Just keep in mind that while you might come across references to structures known as "houses of darkness" in the deep dark, they have been removed. I spent at least an hour looking for one.

**Comment by iKurama** [comment]
The crystal (clusters), are the ones you have to place down and then break. These clusters have EMC too.

**Comment by tfox83** [comment]
iKurama is correct.
