### ISSUE TITLE
Crash when browsing recipes in cooking for blockheads unfiltered book

### ISSUE THREAD

**Issue by mitchell-abbott** [FTBTeam/FTB-Sky-Adventures#81]
* **Modpack Version**: 1.0.0

* **Issue**: Viewing recipes in the unfiltered cooking for blockheads book causes crash

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/8ef6334a

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Cooking for Blockheads

**Comment by tfox83** [comment]
Do you have the actual crash report that is generated and saved in minecraft/crash reports ?

**Comment by mitchell-abbott** [comment]
No crash-report folder exists for my instance. The paste in the link was from the console when my instance crashed.
