### ISSUE TITLE
Loot bag recycler makes for overpowered EMC

### ISSUE THREAD

**Issue by Exobe** [FTBTeam/FTB-Sky-Adventures#82]
* **Modpack Version**:  1.0.0, 1.1.0

* **Issue**: I'm surprised I haven't seen a report here, as a number of Youtubers have shown off this "trick". You can input ash or some low EMC equivalent into the loot bag recycler and have it create bags. Loot bags contain a LOT of EMC, and with a setup like this you have no need to find another way of EMC generation.

* **Is it Repeatable?**: Yep

* **Mod/s Affected**: ProjectE, LootBags

* **Known Fix**: Loot bags are overpowered in most packs if there's a way to automatically open them, and while removing the mod altogether would anger many people, it should be considered. At the very least removing the loot bag recycler will fix the EMC loop.

**Comment by iKurama** [comment]
It's not even worth it to open anything that isn't white, as white has more variety compared to others (the others are exactly the same, just less.)

**Comment by tfox83** [comment]
Fixed in dev
