### ISSUE TITLE
No crafting recipe for the bigger Klein Stars

### ISSUE THREAD

**Issue by fguillod** [FTBTeam/FTB-Sky-Adventures#84]
* **Modpack Version**: 1.1.0-1.12.2 (world updated from 1.0.0-1.12.2)

* **Issue**: Except for the Klein Star Eins, the other Klein Stars do not have any recipes. I don't know if this is on purpose or not. Do I need to unlock all the transmutations with the book (20'000 $) to get them ?

* **Link to Log or Crash File Paste**: Nothing to provide

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: ProjectE

* **Known Fix**: None ?

**Comment by iKurama** [comment]
https://github.com/FTBTeam/FTB-Sky-Adventures/issues/48

**Comment by tfox83** [comment]
Duplicate to #48
