### ISSUE TITLE
Flat Transfer Node (Items) wrong EMC

### ISSUE THREAD

**Issue by ClassixX** [FTBTeam/FTB-Sky-Adventures#85]
* **Modpack Version**: 1.1.0

* **Issue**: Flat Transfer Node (Items) has inappropriate EMC value. The one for the Flat Transfer Node (Fluids) was fixed, but the one for items hasn't.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by tfox83** [comment]
fixed in dev
