### ISSUE TITLE
Extra Utilities 2 Enchanter

### ISSUE THREAD

**Issue by Caelzair** [FTBTeam/FTB-Sky-Adventures#86]
* **Modpack Version**: 
1.1.0
* **Issue**: 
Adding lapis to an extra utilities 2 enchanted that already has lapis in it, deletes the lapis you added instead of adding it to the stack.
* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 
yes
* **Mod/s Affected**: 

* **Known Fix**:

**Comment by iKurama** [comment]
https://github.com/FTBTeam/FTB-Sky-Adventures/issues/43

**Comment by tfox83** [comment]
closed due to duplicate

**Comment by Namoku** [comment]
This isn't fixed yet in the last release.
