### ISSUE TITLE
Ex Nihilo Creatio end cake doesn't seem to be working.

### ISSUE THREAD

**Issue by Yusunoha** [FTBTeam/FTB-Sky-Adventures#87]
Modpack Version: 1.1.0

Issue: I can't seem to travel to the end. I crafted the end cake from Ex Nihilo Creatio, but when I place it down and right click it I'm not getting teleported. 

I tried right-clicking it with ender pearls and eye of enders, but both didn't do anything. I thought it might've been related to not having travelled to the Nether yet, so I tried doing that first, but the cake still didn't do anything.

I tried placing the cake at different locations, but yet again, that didn't do anything.

Link to Log or Crash File Paste: There's no log or crash file, as the game doesn't crash.

Is it Repeatable?: Yes, as I can't get it to work.

Mod/s Affected: Ex Nihilo Creatio 1.12-0.2.4

Known Fix:

**Comment by Yusunoha** [comment]
nvm... it seems you need to actually be hungry before you can eat the end cake -_-

**Comment by tfox83** [comment]
Yes you have to be hungry :)
