### ISSUE TITLE
Akashic Tome EMC Bug

### ISSUE THREAD

**Issue by SomeRandomPetey** [FTBTeam/FTB-Sky-Adventures#88]
* **Modpack Version**: 1.0.0
* **Issue**: If you place the Akashic Tome that the player starts with in a transmutation table/tablet, you lose all of the stored books in the tome. Most likely will occur with the Morphing Tool too, however I have yet to test it.

* **Link to Log or Crash File Paste**: Does not crash the game, but deletes all the guide books.

* **Is it Repeatable?**: Simply put the tome in a transmutation table, and when you pull a new one out (must be from right side) it loses all it's nbt data because of how emc works.

* **Mod/s Affected**: ProjectE

* **Known Fix**: Remove the EMC Value of the tome.

**Comment by iKurama** [comment]
https://github.com/FTBTeam/FTB-Sky-Adventures/issues/44 - if anything doesn't work in 1.0.0, it might work in a new patch :)

**Comment by tfox83** [comment]
It has been removed in dev already.
