### ISSUE TITLE
TE quests allow 'turning in' wrong machine

### ISSUE THREAD

**Issue by isavegas** [FTBTeam/FTB-Sky-Adventures#89]
* **Modpack Version**: 1.1.0

* **Issue**: The quests for crafting Thermal Expansion machines ignore metadata, meaning that you can complete all of the affected quests with only one of the machines in your inventory. I had most of the machines in my inventory and spammed through all of the TE quests before realizing that I didn't have a fractioning still, even though I was able to complete the quest.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: FTB Quests, caused by bug in quest definitions

* **Known Fix**: Disable the `Ignore Damage` flag for all quests that have item tasks requiring `thermalexpansion:machine` and `thermalexpansion:device` variants.

**Comment by tfox83** [comment]
Fixed in dev
