### ISSUE TITLE
Potion generator not accepting potions

### ISSUE THREAD

**Issue by IsoEeli** [FTBTeam/FTB-Sky-Adventures#90]
* **Modpack Version**: 1.0.0

* **Issue**: Potion generator is not accepting any potions

* **Link to Log or Crash File Paste**:

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Extra Utilities 2

* **Known Fix**:

**Comment by tfox83** [comment]
This is fixed in 1.2.0 beta.
