### ISSUE TITLE
Storage Solutions not getting a complete checkmark.

### ISSUE THREAD

**Issue by Yusunoha** [FTBTeam/FTB-Sky-Adventures#91]
Modpack Version:  1.1.0

Issue: I finished all quests from the Storage Solutions tab, but the tab isn't getting a checkmark for having all the quests completed.
Here's a screenshot showing the problem. https://imgur.com/a/aIgECPg

Link to Log or Crash File Paste: None, as the issue isn't a crash.

Is it Repeatable?: Yes. I went into a creative world and completed all the quests from Storage Solutions and yet again there's no checkmark.

Mod/s Affected:  FTBQuests-1.2.1.62

Known Fix: Maybe there's a hidden quest that's not visible? The tab says 98% of the quests are completed, but all of the available and visible quests are completed.

**Comment by tfox83** [comment]
Gonna have @LatvianModder take a look at this

**Comment by LatvianModder** [comment]
Yeah, it's weird. Without extra quest it shouldn't be possible to not be complete. My theory is that there's 2 in one spot

**Comment by LatvianModder** [comment]
Guess I was correct lol
![](https://ss.latmod.com/pc/2018-10-24_11.19.43.png)
Another ME Security Terminal under Cell Workbench.

**Comment by tfox83** [comment]
fixed in dev
