### ISSUE TITLE
RS Wireless Crafting Grid dublicates Items

### ISSUE THREAD

**Issue by nafftan** [FTBTeam/FTB-Sky-Adventures#94]
* **Modpack Version**: 1.1.0

* **Issue**: Clearing the crafting fields of the Wireless Crafting Grid from Refined Storage by clicking X dublicates all Items in it.

* **Link to Log or Crash File Paste**: no crash

* **Is it Repeatable?**: yes. every item placed in the crafting fields and cleared with the X is added two times to the storage ... even 9 stacks of items

* **Mod/s Affected**: Refined Storage

* **Known Fix**:

**Comment by iKurama** [comment]
Incorrect affected mod.
https://minecraft.curseforge.com/projects/refined-storage-addons
'Refined Storage Addons'

**Comment by TheSaucyWelshman** [comment]
https://github.com/raoulvdberge/refinedstorageaddons/issues/38


It was RS but it's been fixed.  The fix is included in version 1.2.0 of Sky Adventures that was released a few hours ago as a beta

**Comment by tfox83** [comment]
correct, billybricker, thanks.
