### ISSUE TITLE
Thermal Expansion Induction Smelter does not accept any variant of Fused Quartz

### ISSUE THREAD

**Issue by ffgda** [FTBTeam/FTB-Sky-Adventures#95]
* **Modpack Version**: 1.1.0

* **Issue**: Even though Fused Quartz is ore dictionaried as blockGlassHardened and shows up in JEI as a substitute for Thermal Expansion Hardened Glass, it can't be inserted into the Thermal Expansion Induction Smelter.

* **Link to Log or Crash File Paste**: -

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Thermal Expansion/Ender IO

* **Known Fix**: -

**Comment by tfox83** [comment]
Its a known issue without a fix currently as overriding the recipe creates more issues.
