### ISSUE TITLE
Money farm, end game in a few hours of play time

### ISSUE THREAD

**Issue by Schildos** [FTBTeam/FTB-Sky-Adventures#96]
* **Modpack Version**: 1.0.0 (and newer?(untested!))

* **Issue**: Relatively simple money farm using draconic reactor cores.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: create a woot farm get a chaos dragon set up some auto crafting  - PROFIT

* **Mod/s Affected**: Woot / Draconic Evolution / FTBQuest?

* **Known Fix**: Disable the farming of Chaos Dragons in the woot config, should remove this farm

**Comment by tfox83** [comment]
removed choas dragon from woot factory in next version

**Comment by Kite1024** [comment]
Any suggestions as to where to get chaos shards after this fix?
