### ISSUE TITLE
Problem to launch the server file for 1.2.0 because of Openblock

### ISSUE THREAD

**Issue by ghost** [FTBTeam/FTB-Sky-Adventures#97]
* **Modpack Version**: 1.2.0 

* **Issue**:  Straight crash when launching the server in 1.2.0 

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/6f957fe0

* **Is it Repeatable?**: I don't know 

* **Mod/s Affected**: OpenBlock 

* **Known Fix**: Update OpenBlock to the latest version

**Comment by ghost** [comment]
There is a lot of mods missing on the client side too

**Comment by tfox83** [comment]
Please try a fresh install, I just double checked all the files, all the mods are present.
