### ISSUE TITLE
Chicken Breeder going into negatives

### ISSUE THREAD

**Issue by davidpanic** [FTBTeam/FTB-Sky-Adventures#98]
* **Modpack Version**: 
latest

* **Issue**: 
![image](https://user-images.githubusercontent.com/13370323/47398052-838a0f80-d732-11e8-8407-87d12ef8a1b6.png)
... it just keeps going down ...
![image](https://user-images.githubusercontent.com/13370323/47398119-ec718780-d732-11e8-939c-60fa624a54a8.png)

* **Link to Log or Crash File Paste**: 
n/a
* **Is it Repeatable?**: 
yes, but idk how to

* **Mod/s Affected**: 
Roost

* **Known Fix**: 
Sometimes removing the chickens and placing them back in works

**Comment by iKurama** [comment]
https://github.com/timrwood/roost/issues/13
Almost a year without any update, so not likely to be fixed.

**Comment by Mordaii** [comment]
I've reviewed ,in detail, the source code and authors explanation.  Using a bit of math I've created a workaround on my server. So I'll share what I did below.

In  _\config\chickens\morechickens.json we can update the  Lay Coefficient to eggs past tier 2 to stay within bounds of the bug described.  

For each chicken we identify the tier.. then apply the following co-efficients depending on the tier of the chicken.  The Lay coefficients below keep the max lay time within the positive bounds of the short data type(32,767).

Tier/Lay Co-efficient
1	1
2	1
3	0.909639
4	0.682229
5	0.545783
6	0.454819
7	0.389845
8	0.341115
9	0.303213
10	0.272892
11	0.248083
12	0.22741
13	0.209917
14	0.194923
15	0.181928

*EDIT - I believe after this is applied the chickens will need to be newly bred to take the new lay co-efficient.

**Comment by toxiblib** [comment]
any chance you could upload a file with these changes cause I cant make much sense of the config file

**Comment by Ahmaz** [comment]
FYI, mod owner has updated the mod to 1.3.0 which fixes the issue
[https://github.com/timrwood/roost/issues/13](https://github.com/timrwood/roost/issues/13)

**Comment by toxiblib** [comment]
Will there be an update to sky adventure to go along with this?

**Comment by tfox83** [comment]
fixed in next version
