### ISSUE TITLE
When a tree grows, the bottom block doesn't turn to a log.

### ISSUE THREAD

**Issue by TheFlash787** [FTBTeam/FTB-Sky-Adventures#99]
* **Modpack Version**: 1.0.0

* **Issue**: When a tree grows on the island, most of the time, the bottom block (sapling block) will not turn to wood and will just look like this: ![Example](https://files.modrealms.net/screenshots/01.32.51-24.10.18.png)
This can be incredibly annoying early game.

**Comment by iKurama** [comment]
I can't reproduce that, can you do that in 1.2.0?

**Comment by tfox83** [comment]
Usually that is an issue with lag and or server.  I am not able to reproduce that either.
